### PR TITLE
Modifying apiVersion for daemonset and adding selectors

### LINKED ISSUE #993: Update the yaml files.
**Describe the bug**
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.16.md#deprecations-and-removals
we have to use apps/v1 places like here 
https://github.com/falcosecurity/falco/blob/dev/integrations/k8s-using-daemonset/k8s-with-rbac/falco-daemonset-configmap.yaml#L1

**How to reproduce it**
1. use latest k8s 
2. apply the yaml files 

You will get below error 
 kubectl apply -f k8s-with-rbac/falco-daemonset-configmap.yaml
error: unable to recognize "k8s-with-rbac/falco-daemonset-configmap.yaml": no matches for kind "DaemonSet" in version "extensions/v1beta1"

**Expected behaviour**

**Screenshots**

**Environment**

- Falco version:

- System info:

- Cloud provider or hardware configuration:
- OS:

- Kernel:

- Installation method:

**Additional context**

### PR DESCRIPTION
**Pull request by rushabh268**
**What type of PR is this?**

/kind bug

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area integrations

**What this PR does / why we need it**:

This PR fixes the case where Falco daemonset cannot be deployed in Kubernetes 1.17+ due to incorrect apiVersion and missing selector for pods

**Which issue(s) this PR fixes**:

#993

Automatically closes linked issue when PR is merged.
Usage: `Fixes #993`.

Fixes #993 

**Special notes for your reviewer**:

This should fix the following errors:

```
root@int:~/falco/integrations/k8s-using-daemonset# kubectl apply -f k8s-with-rbac/falco-config/falco-daemonset-configmap.yaml
error: unable to recognize "k8s-with-rbac/falco-config/falco-daemonset-configmap.yaml": no matches for kind "DaemonSet" in version "extensions/v1beta1"

root@int:~/falco/integrations/k8s-using-daemonset# kubectl apply -f k8s-with-rbac/falco-config/falco-daemonset-configmap.yaml
error: error validating "k8s-with-rbac/falco-config/falco-daemonset-configmap.yaml": error validating data: ValidationError(DaemonSet.spec): missing required field "selector" in io.k8s.api.apps.v1.DaemonSetSpec; if you choose to ignore these errors, turn validation off with --validate=false
```

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by fntlnz** [comment]
Also @rushabh268 please sign-off your commit.
You can do that by adding `-s` when you do a commit:

E.g:

```
git commit -sm "your message"
```

or if you want to sign the last commit you did:

```
git commit -s --amend --no-edit
```

**Comment by rushabh268** [comment]
@fntlnz I have made the suggested changes and also made the necessary changes to integrations/k8s-using-daemonset/falco-event-generator-deployment.yaml. I have also signed off the last commit.

**Comment by rushabh268** [comment]
@leodido I think I made those changes here: https://github.com/falcosecurity/falco/commit/3e6e22bff43d507da5c6d10388aa2f2a6724902e

**Comment by fntlnz** [comment]
Removing this from the milestone since we have to make a community decision on how to handle those. Same comment as this one https://github.com/falcosecurity/falco/pull/1044#issuecomment-595215790

This kind of thing doesn't really need to cut a release.

:)

**Comment by leodido** [comment]
@leogr this is the PR I was mentioning to you before, too

**Comment by leodido** [comment]
Superseded by #1044 

/close

**Pull request closed without merging**
