### PR TITLE
update : support build for wasm 

### PR DESCRIPTION
**Pull request by Rohith-Raju**
**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

/area build

/area tests

/area CI

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
This PR adds support to WASM target. This is a preliminary work for Google Summer of Code
https://github.com/falcosecurity/evolution/issues/262
https://github.com/falcosecurity/libs/pull/1156

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
update : support build for wasm 
```

### CODE REVIEW

**Comment by Rohith-Raju** [comment]
CC: @jasondellaluce

**Comment by jasondellaluce** [comment]
I helped Rohith updating the branch and polishing the cmake changes. This should be ready for review!

**Comment by Rohith-Raju** [comment]
Fixed merge conflict.

**Review by FedeDP — APPROVED** [review]
/approve

Incredible job! Thank you very much!

**Pull request merged**
