### PR TITLE
refactor(userspace/engine): increase const coherence in falco engine

### PR DESCRIPTION
**Pull request by jasondellaluce**
**What type of PR is this?**

/kind cleanup

/kind design

**Any specific area of the project related to this PR?**

/area engine

**What this PR does / why we need it**:

This PR uses the `const` keyword with coherence across the falco engine interface and classes. Although this does not introduce any practical change, it is useful to make it more explicit which operations alter the state of the engine and which not.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jasondellaluce** [comment]
Supports (although it is not a strict requirement) the work needed to implement the features of https://github.com/falcosecurity/falco/issues/2074.

**Review by leogr — DISMISSED** [review]

**Review by FedeDP — DISMISSED** [review]
/approve

**Review by FedeDP — APPROVED** [review]
/approve

**Review by leogr — APPROVED** [review]
:+1:

**Pull request merged**
