### PR TITLE
update(OWNERS): add LucaGuerra to owners

### PR DESCRIPTION
**Pull request by LucaGuerra**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind documentation

After driving various Falco releases and helping maintainers in several areas, including main code, security and CI/CD, I think I can help more closely with the maintenance of this repo! As per our discussion during the core maintainers planning meeting on 2023-06-08 and the community call on 2023-06-21. :)

```release-note
NONE
```

### CODE REVIEW

**Comment by jasondellaluce** [comment]
+1

**Comment by Andreagit97** [comment]
+1 :tada:

**Comment by FedeDP** [comment]
+1! :scream_cat:

**Comment by incertum** [comment]
+1 @LucaGuerra ❤️ !!!

**Comment by leogr** [comment]
+1 :heart:

**Review by incertum — APPROVED** [review]
/approve

:partying_face:

**Review by leogr — APPROVED** [review]
:partying_face: :clap:

**Pull request merged**
