### PR TITLE
Static code analysis

### PR DESCRIPTION
**Pull request by fntlnz**
**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

/area build

**What this PR does / why we need it**:

This PR adds a static code analysis job to our CI pipeline.
The only implemented tool for now is cppcheck but in the way the structure is, we can add more steps.

By doing this we can also improve our scores in the CII best practices program. See #428 

The report will be generated on every PR under the `ci/circleci: static-analysis` CI pipeline.
Clicking on the pipeline and then on Artifacts > index.hml shows the report.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by leodido — DISMISSED** [review]
Simply amazing! 💯 🥇 

The only complaint is that, as you already know, after discussing this together, I would also have participated in bringing it into life! 😃

**Review by leogr — APPROVED** [review]
LGTM

/hold
since we may need to release the 0.26.1 soon (see #1418). 

Anyway, feel free to un-hold if you want to merge this in before the 0.27.0.

**Review by leogr — APPROVED** [review]

**Review by leodido — APPROVED** [review]

**Pull request merged**
