### PR TITLE
fix(permissions): Restrict to RO access to /dev on underlying host

### PR DESCRIPTION
**Pull request by farshad-hobsons**
**What type of PR is this?**
/kind bug
/kind design

**Any specific area of the project related to this PR?**
/area deployment
/area integrations

**What this PR does / why we need it**:
This PR improves the security posture of falco container deployment by only allowing readOnly access to `/dev` on underlying host. Following the [least-privilage access principle](https://en.wikipedia.org/wiki/Principle_of_least_privilege) is a nice to have, especially for a security tool itself.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
I tested this change locally on minikube. Falco container was able to correctly load kernel modules and start cleanly. I also tested the detection by falco when a privileged container is spawned.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by farshad-hobsons** [comment]
@leodido - any idea on how is the schedule to merge determined for approved PRs. 

In order to get the downstream falco helm-chart https://github.com/helm/charts/pull/17101 merged, it looks like [folks](https://github.com/helm/charts/pull/17101#issuecomment-531155432) would feel more comfortable if we merge this first.

**Comment by leodido** [comment]
I am at a conference these days and I'll not have time to look into the jenkins job failing. Looping in Lorenzo.

/assign @fntlnz

**Comment by fntlnz** [comment]
Hi @farshad-hobsons thanks for this PR, don't worry about that CI check, it's good as soon as Travis CI passes. I need to check this PR myself though. Will update asap.

**Comment by fntlnz** [comment]
Thanks for this @farshad-hobsons !

**Pull request merged**
