### PR TITLE
fix(userspace): switch to timer_settime API for stats writer.

### LINKED ISSUE #2645: Metrics are not created if http_output is enabled
**Describe the bug**

If `http_output` is enabled, then only one metric alert is created / only one line is written in the metrics log file regardless the set period.

**How to reproduce it**

Set config to:
```
http_output:
  enabled: true
  url: http://some.url
metrics:
  enabled: true
  interval: 1m
  output_rule: true
  output_file: /tmp/falco_stats.jsonl
```

**Expected behaviour**

Metrics alerts are created every minute and written to the `/tmp/falco_stats.jsonl` file every minute.

**Screenshots**

**Environment**

- Falco version: 
```
2023-06-21T03:38:30+0000: Falco version: 0.35.0 (x86_64)
2023-06-21T03:38:30+0000: Falco initialized with configuration file: /etc/falco/falco.yaml
Falco version: 0.35.0
Libs version:  0.11.2
Plugin API:    3.0.0
Engine:        17
Driver:
  API version:    4.0.0
  Schema version: 2.0.0
  Default driver: 5.0.1+driver
```

- System info: 
```{
  "machine": "x86_64",
  "nodename": "falco-syscall-b2h8x",
  "release": "5.15.89+",
  "sysname": "Linux",
  "version": "#1 SMP Sat Mar 11 10:24:08 UTC 2023"
}
```

- Cloud provider or hardware configuration: GCP
- OS: Debian GNU/Linux 11 (bullseye)

- Kernel: 
```
Linux falco-syscall-b2h8x 5.15.89+ #1 SMP Sat Mar 11 10:24:08 UTC 2023 x86_64 GNU/Linux
```

- Installation method: kubernetes

**Additional context**
Thread on kubernetes slack workspace: https://kubernetes.slack.com/archives/CMWH3EH32/p1686643450242449
@incertum @Issif @alacuku @jasondellaluce

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind bug

**Any specific area of the project related to this PR?**

/area engine

**What this PR does / why we need it**:

Switched to use `timer_settime` API in stats writer, as `setitimer` seems to have issues when built from our CI (glibc/gcc bugs?)

**Which issue(s) this PR fixes**:

Fixes #2645 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
fix(userspace): switch to timer_settime API for stats writer.
```

### CODE REVIEW

**Comment by FedeDP** [comment]
Refs #2645

**Comment by FedeDP** [comment]
Added some more debug prints!

**Comment by FedeDP** [comment]
It seems like the timer is ticking just twice (ie: once for the `timer.it_value` and once for the `timer.it_interval`). Digging into it.

**Comment by FedeDP** [comment]
Why do i always `git commit -sam` :angry:

**Comment by FedeDP** [comment]
Dropped debug prints; `timer_settime` API seems to be reliably working.

**Comment by FedeDP** [comment]
/cc @incertum @jasondellaluce 

To test, grab latest package produced by this PR CI, and do the same on master. You'll notice that on master, the tick is triggered just twice; on this PR it gets ticked continuously. (enable metrics with 1s timeout to quickly test)

**Comment by incertum** [comment]
> 

@FedeDP our hero !!! Fantastic job 🤩 I could replicate the issues on master and confirming this PR fixes the issues!
Well done, and thanks for planning a 0.35.1 release!

**Review by incertum — APPROVED** [review]
/approve

**Review by jasondellaluce — APPROVED** [review]
/approve

**Pull request merged**
