### PR TITLE
fix(dockerfile/no-driver): install ca-certificates

### PR DESCRIPTION
**Pull request by alacuku**
Signed-off-by: Aldo Lacuku <aldo@lacuku.eu>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

> /kind release

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area build

> /area engine

> /area tests

> /area proposals

> /area CI

**What this PR does / why we need it**:

The `falco-no-driver` image missed the `ca-certificates`. This PR installs them in the final build stage.

**Which issue(s) this PR fixes**:
#2274 #2395

Fixes #

**Special notes for your reviewer**:

I've built and tested the new image locally and it seems that the certificate issues are gone.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by alacuku** [comment]
see falcosecurity/libs#871

**Comment by Issif** [comment]
IMHO it's a critical issue for end users. It avoids to use some plugins and falcoctl correctly, could we think about a 0.34.1?

**Review by FedeDP — APPROVED** [review]
/approve

**Pull request merged**
