### PR TITLE
update: bump libs and driver versions

### PR DESCRIPTION
**Pull request by jasondellaluce**
**What type of PR is this?**

/kind cleanup

/kind feature

**Any specific area of the project related to this PR?**

/area build

/area engine

/area tests

**What this PR does / why we need it**:

This bumps the libs version and syncs with the recent AST definition changes that broke the previous interfaces, thus causing building failures.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

Waiting for the changes of https://github.com/falcosecurity/libs/pull/556 to get merged.

**Does this PR introduce a user-facing change?**:

```release-note
update: bump libs and driver versions to 6599e2efebce30a95f27739d655d53f0d5f686e4
```

### CODE REVIEW

**Review by FedeDP — APPROVED** [review]
/approve

**Comment by FedeDP** [comment]
uh codeql failed :/

**Review by leogr — APPROVED** [review]
:partying_face: :parrot:

**Pull request merged**
