### PR TITLE
rule(Disallowed K8s User): exclude allowed eks users

### PR DESCRIPTION
**Pull request by darryk10**
EKS uses some users for its need which generate noise for this rule. 
Reference: https://docs.aws.amazon.com/eks/latest/userguide/default-roles-users.html

Signed-off-by: darryk10 <stefano.chierici@sysdig.com>
Co-authored-by: Alberto Pellitteri <alberto.pellitteri@sysdig.com>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

> If contributing rules or changes to rules, please make sure to also uncomment one of the following line:

/kind rule-update

> /kind rule-create

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

> /area engine

/area rules

> /area tests

> /area proposals

**What this PR does / why we need it**:
EKS uses some users for its need which generate noise for this rule. This PR add a specific list for eks users to whitelists event related to this users.
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
rule(Disallowed K8s User): exclude allowed EKS users
```

### CODE REVIEW

**Review by MikeC-Sysdig — APPROVED** [review]

**Review by Kaizhe — APPROVED** [review]

**Review by jasondellaluce — APPROVED** [review]
/approve

**Pull request merged**
