### PR TITLE
update(docs): changelog for version 0.32.2

### PR DESCRIPTION
**Pull request by Andreagit97**
**What type of PR is this?**

/kind documentation

**Any specific area of the project related to this PR?**

/area engine

**What this PR does / why we need it**:

Add changelog for 0.32.2

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
update(docs): changelog for version 0.32.2
```

### CODE REVIEW

**Review by jasondellaluce — APPROVED** [review]
/approve

**Review by leogr — APPROVED** [review]

**Comment by jasondellaluce** [comment]
Closing and re-opening to trigger the CI

/close

**Pull request merged**
