### PR TITLE
Generate doxygen documentation

### PR DESCRIPTION
**Pull request by leodido**
**What type of PR is this?**

/kind documentation

/kind feature

**Any specific area of the project related to this PR?**

/area build

**What this PR does / why we need it**:

This PR introduces a way to build the **Falco development docs**. 🎉 

Docs for developers, and people that want to contribute to Falco, are a long-standing feature needed by our community. Thus, I decided to package this gift for our awesome community 🎁 

Namely, this PR:

- introduces a new target - ie., `GenerateDocs` - to generate **Doxygen** documentation
     - to work it requires `doxygen`, `jinja2`, and `pygments` installed on the machine
     - uses mosra/m.css (A no-nonsense, no-JavaScript CSS framework for content-oriented websites)
         - live demo of a possible final result [here](https://doc.magnum.graphics/magnum) 👈 
- introduces [CPM](https://github.com/TheLartians/CPM.cmake) (that I intend to use to simplify the way we handle all our dependencies)
     - it's a CMake module that adds dependency management capabilities to CMake
     - It's built as a thin wrapper around CMake's FetchContent module that adds version control, caching, a simple API
     - read more at the provided link for extensive documentation about it

### How to try it out

```console
cmake -Hdocumentation -Bbuild/docs
cmake --build build/docs --target GenerateDocs
```

Then open the `build/docs/doxygen/html/index.html` file in your browser.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

Things to do to consider it 100% done:

- [ ] add doxygen comments to our source code
- [ ] fine-tune the generated docs structure (navbars, etc.)
- [ ] fine-tune the generated docs content
- [ ] publish the HTML using a CI job (to discuss with the community how/where/etc.)
    - [x] community choose to put development docs on a new website (falcosecurity.dev)
    - [x] obtain falcosecurity.dev

/hold

**Does this PR introduce a user-facing change?**:

```release-note
new: Falco development docs at ...
```

### CODE REVIEW

**Comment by leodido** [comment]
Some screenshots of the current (not final) outcome:

image
image
image
image
image
image

**Review by leogr — COMMENTED** [review]
I love this :star_struck: 

Really nice and clean :+1: 

PS
I have adjusted the [license's badge link](https://github.com/falcosecurity/falco/pull/1513/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R6) that should fix the README rendering issue.

**Comment by leodido** [comment]
Update:

thanks to the CNCF (@caniszczyk) we now have `falcosecurity.dev` 🥳

**Comment by deepskyblue86** [comment]
Up!

**Comment by leogr** [comment]
Hey @leodido 

What do you think about unblocking this PR so that we can continue this effort in subsequent PRs?

Even though the current status of this PR does not achieve the final result, it seems to be working. Thus, IMO, it is worth merging it as-is now.
Wdyt? :smiley:

**Pull request closed without merging**
