### PR TITLE
rules: whitelist GCP's container threat detection image

### PR DESCRIPTION
**Pull request by clmssz**
**What type of PR is this?**

/kind rule-update

**Any specific area of the project related to this PR?**

/area rules

**What this PR does / why we need it**:

[Container threat detection](https://cloud.google.com/security-command-center/docs/how-to-use-container-threat-detection) is a feature of GCP security center that monitors cos nodes for changes and remote access attempts (it kinds of duplicate falco). It spawns a privileged DaemonSet in GKE clusters `kube-system` namespace, hence the need for  ignoring this image.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jasondellaluce** [comment]
Thank you for this, I think this works! @Kaizhe WDYT?

**Comment by Kaizhe** [comment]
More info about the proposed image: https://cloud.google.com/security-command-center/docs/how-to-use-container-threat-detection

**Review by jasondellaluce — APPROVED** [review]
/approve

**Pull request merged**
