### PR TITLE
docker minimal images need exact FALCO_VERSION

### PR DESCRIPTION
**Pull request by leodido**
Signed-off-by: Leonardo Di Donato <leodidonato@gmail.com>

**What type of PR is this?**

/kind bug

**Any specific area of the project related to this PR?**

/area build

**What this PR does / why we need it**:

Since `minimal` docker images fetch the falco binary from `bin` or `bin-dev` repositories they need to explicitly set the `FALCO_VERSION` variable.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by leodido** [comment]
This should (ideally) be merged before other PRs @kris-nova 

PTAL

**Comment by fntlnz** [comment]
@poiana why this is not merged?

**Comment by fntlnz** [comment]
Reopening to let poiana handle it, let's see

**Comment by fntlnz** [comment]
Oh the problem was that it was queued behind another PR. Now it's IN! Let's party :tada:

**Pull request merged**
