### PR TITLE
new: support specifying multiple cri paths options

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

/kind feature

> If contributing rules or changes to rules, please make sure to also uncomment one of the following line:

> /kind rule-update

> /kind rule-create

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

/area engine

> /area rules

> /area tests

> /area proposals

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

Must enter after https://github.com/falcosecurity/libs/pull/202.  

**Does this PR introduce a user-facing change?**:

```release-note
new: allow to specify multiple --cri options
```

### CODE REVIEW

**Comment by FedeDP** [comment]
@leogr  added a comment :)  
Can you re-approve? Thanks!

**Comment by leogr** [comment]
> @leogr added a comment :) Can you re-approve? Thanks!

I'll approve once https://github.com/falcosecurity/libs/pull/202. Anyway this LGTM!

/milestone 0.32.0

**Comment by FedeDP** [comment]
My fault, i posted the comment in the wrong PR :D

**Review by leogr — DISMISSED** [review]
/approve

**Review by leogr — APPROVED** [review]
/approve

**Review by jasondellaluce — APPROVED** [review]
/approve

**Pull request merged**
