### PR TITLE
new(ci): added an arm64 musl build.

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

/area CI

**What this PR does / why we need it**:

Since we do provide an x86_64 musl static package, we should also provide an arm64 one.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by FedeDP** [comment]
/milestone 0.36.0
We don't need it now; and we don't want to fight again with the CI at this stage.
Postpone to next version.

**Review by jasondellaluce — DISMISSED** [review]

**Review by leogr — DISMISSED** [review]

**Comment by FedeDP** [comment]
Rebased on top of master ;)

**Review by jasondellaluce — DISMISSED** [review]

**Review by Andreagit97 — DISMISSED** [review]
/approve

**Comment by FedeDP** [comment]
Rebased on master. Still need to add more arm64 nodes on test-infra. I am going to open the PR soonish :)

**Comment by FedeDP** [comment]
https://github.com/falcosecurity/test-infra/pull/1189 Opened!

**Comment by jasondellaluce** [comment]
I think `reusable_test_packages.yml` should be updated as well to avoid skipping static build tests for arm64!

**Comment by FedeDP** [comment]
/milestone 0.37.0

No time for this during this release cycle; this is not that important after all, we can live without it for another release cycle.

**Comment by FedeDP** [comment]
Rebased on top of master. Still waiting to get more self-hosted runners on test-infra cluster.

**Review by leogr — DISMISSED** [review]

**Review by incertum — DISMISSED** [review]
/approve

/hold 

@FedeDP please unhold when you feel it should be merged.

**Comment by FedeDP** [comment]
@Andreagit97 i enabled back driver loader tests on arm64 too, now! Since we now have actuated arm64 node that runs ubuntu, we should be able to run them!

**Comment by FedeDP** [comment]
> Error: JavaScript Actions in Alpine containers are only supported on x64 Linux runners. Detected Linux Arm64

Oh wow.
Feature request: https://github.com/actions/runner/issues/801

**Comment by FedeDP** [comment]
I will close this one since it cannot be supported right now; and open a new PR with only the `driver-loader` enablement for arm64 part.

**Pull request closed without merging**
