### PR TITLE
new(falco): add base_syscalls.all option to replace -A

### PR DESCRIPTION
**Pull request by LucaGuerra**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area engine

**What this PR does / why we need it**:

This adds `base_syscalls.all` replacing `-A`.

This PR has not yet been linted. If the lint PR is merged I will update.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
new(falco): add base_syscalls.all option to falco.yaml, deprecate -A
```

### CODE REVIEW

**Comment by FedeDP** [comment]
I like the idea; let's deprecated yet another CLI option!
/milestone 0.40.0

**Comment by LucaGuerra** [comment]
need to fix formatting / tests

**Comment by LucaGuerra** [comment]
@FedeDP done!

**Review by FedeDP — APPROVED** [review]
/approve

**Review by sgaist — APPROVED** [review]

**Review by FedeDP — APPROVED** [review]
/approve

**Pull request merged**
