### PR TITLE
update Civetweb 1.15 to support openssl 1.1

### LINKED ISSUE #1708: Falco webserver with SSL error: null context when constructing CivetServer
**Describe the bug**
Falco SSL webserver start up error msg
`Runtime error: Could not create embedded webserver: null context when constructing CivetServer. Possible problem binding to port. Exiting.`
This message only appears when setting enable_ssl to true and provide an ssl certificate with key.  Webserver will start properly when ssl is disabled.

**How to reproduce it**
Using latest helm chart with the following values set
  ssl_enabled=true
  certs.server.crt=./falco-cert/server.crt
  certs.server.key=./falco-cert/server.key
Falco secret is created with server.pem and mounted on falco container

**Expected behaviour**
Falco webserver is able to start properly when ssl enabled

**Environment**
- Falco version: 0.29.1
- System info:  k8s: 1.19.14
- Cloud provider or hardware configuration:
- OS:
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
- Kernel:
Linux ip-10-1-3-37 5.8.0-1038-aws #40~20.04.1-Ubuntu SMP Thu Jun 17 13:25:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Installation method:
Kubernetes helm chart installation

**Additional context**

Falco will start and run properly without ssl enabled.
This is not a port issue.  I've verified that the port is not in use but for troubleshooting purposes I tried 3 other non-standard unique port numbers.
I've also tried four different certificates including a sample provided on the CivietServer github repo, self-signed, self-signed with a RootCA, and published CA created cert.
I'm seeing the same problem with ssl enabled webserver on pervious versions of falco versions (0.29.0, 0.28.1).

### PR DESCRIPTION
**Pull request by FedeDP**
**wip**: this PR requires https://github.com/falcosecurity/libs/pull/91 to be merged on libs!!

**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

/area build

**What this PR does / why we need it**:

The PR does some things:
* update civetweb to latest release (1.15)
* properly move civetweb to its own cmake module
* properly build civetweb fully using cmake (instead of make)
* build civetweb disabling dynamic loading of crypto lib, linking instead openssl built with falcosecurity-libs (be it from system or a static library built with BUNDLED_DEPS). **This should fix lots of incompatibilities** that arose when eg: civetweb was built with openssl 1.0.0, but at runtime it found openssl1.1 on your system

**Which issue(s) this PR fixes**:

Fixes #1708 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
update: upgrade civetweb to v1.15
update: bump driver version to cb9bb5e4e0c5fe1542482af802d38a8da8f83c03
```

### CODE REVIEW

**Comment by LucaGuerra** [comment]
Are you compiling against a local libs repo? Perhaps the libs instance you're using has a different set of fields (maybe it's in this branch: https://github.com/falcosecurity/libs/pull/126 )

**Comment by FedeDP** [comment]
> Are you compiling against a local libs repo? Perhaps the libs instance you're using has a different set of fields (maybe you are in this branch: falcosecurity/libs#126 )

Yep but i am building against https://github.com/falcosecurity/libs/pull/91, thus that should makes no really differences!

**Comment by FedeDP** [comment]
Nevermind, falcosecurity/libs#91 was outdated; now rebased on master. This should fix the issue!

**Comment by FedeDP** [comment]
>  ci/circleci: musl — Your tests failed on CircleCI 

This test was fixed in https://github.com/falcosecurity/falco/pull/1753 PR.

**Comment by FedeDP** [comment]
Rebased on master; dropped `wip` commit.

**Comment by FedeDP** [comment]
@mstemm as you reviewed the libs part for this work, can you take a look at this one too?
Thanks!

**Comment by FedeDP** [comment]
Rebased on falco master + updated libs to use falcosecurity libs master.

**Review by leogr — APPROVED** [review]
:partying_face: 

LGTM

/approve

**Review by mstemm — APPROVED** [review]

**Pull request merged**
