### PR TITLE
sync: release 0.39.2

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind release

**Any specific area of the project related to this PR?**

/area build

**What this PR does / why we need it**:

Bump libs to 0.18.2 for a Falco bufgix release 0.39.2
Moreover, cherry picks CI changes in https://github.com/falcosecurity/falco/pull/3386
Finally, cherry picks https://github.com/falcosecurity/falco/pull/3408 to update falcoctl to latest v0.10.1.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
update(cmake): bump libs to 0.18.2
```

### CODE REVIEW

**Comment by FedeDP** [comment]
/hold
i will surely to port changes to CI to drop actuated here too, for sure.

**Review by LucaGuerra — APPROVED** [review]

**Review by leogr — APPROVED** [review]

**Pull request merged**
