### PR TITLE
fix(build): metrics compilation after refactoring into classes

### PR DESCRIPTION
**Pull request by Molter73**
**What type of PR is this?**

/kind cleanup

**Any specific area of the project related to this PR?**

/area build

**What this PR does / why we need it**:
Once falcosecurity/libs#1920 is merged, compilation of falco will be broken due to the `new_metric` method changing the class it lives in. This PR makes falco compatible with this change.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**: The commit that changes the libs cmake files will be dropped and replaced with a commit that properly updates the libs commit and SHA once falcosecurity/libs#1920 is merged, please disregard these changes until that merge occurs.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by FedeDP** [comment]
Thanks Mauro for taking care of this!

**Comment by Molter73** [comment]
I'm a bit confused as to why those driver tests are failing, these PRs don't do any changes to driver code or its corresponding userspace components. Any ideas?

**Comment by FedeDP** [comment]
It happens sometimes; probably mismatch between kernel headers package and runner kernel (or bugged headers package); rnothing to worry about for you! Restarted :)

**Comment by Molter73** [comment]
Kmod failed again, but I need to fix the cmake files after I merge the libs PR anyways. @FedeDP, what do you think? Am I OK to unhold the libs PR?

**Comment by FedeDP** [comment]
Yes no problem, the issue is not dependent on your changes!

**Comment by incertum** [comment]
@Molter73 we usually have the habit to bump both libs and driver during the dev phase. Few times we didn't do it and it caused compatibility issues. If you agree we can jsut continue bumping both together?

**Comment by Molter73** [comment]
Sorry it took a bit, I've bumped the driver version so it matches libs.

**Comment by Molter73** [comment]
I'm guessing the error I'm getting is related to this commit: https://github.com/falcosecurity/libs/commit/fac0ae442474bc1265d2ddc54a3f12557337a821

How do we want to handle it?

**Comment by FedeDP** [comment]
Yep! I already tagged Gerald in that PR to ask him to double check ;) 
Not a big deal, we can wait and then bump libs and driver here once the fix PR is merged.

**Comment by Molter73** [comment]
One of these days I'll get this PR to pass CI...

**Comment by Molter73** [comment]
I'm guessing the 3 issues are due to some change that bled in with the latest libs bump, I was having some issues linking unit tests locally, I'll look into them when I get a minute.

**Comment by Molter73** [comment]
@jasondellaluce looks like the unit test errors I got are due to some warning messages being changed in falcosecurity/libs#1831, could you double check I got those right in the last commit?

**Comment by Molter73** [comment]
Now it looks like ASAN is not very happy, tried to run the tests locally with a debug build and the errors seem related to falcosecurity/libs#1992, would appreciate some confirmation if someone sees this.

**Comment by LucaGuerra** [comment]
@Molter73 AFAIK the ASan failures are related to https://github.com/falcosecurity/libs/pull/1992 , I'm writing some tests for those and will merge the PR soon.

**Comment by Molter73** [comment]
No worries, I'll update this PR after you merge!

**Comment by Molter73** [comment]
I'm gonna need some help understanding the last errors I'm getting, seems something has been broken with the legacy rules?

**Comment by FedeDP** [comment]
This is the same error we are gettng on #3283 . Needs further investigation...
Also this and #3283 are basically the same, i'd close one of them (well this is older and we should keep this but the other is on an upstream branch that is much easier to work with to fix the test issues; let me know if you wish to keep this one, i'll close the other!)

**Comment by Molter73** [comment]
Closing in favor of #3283, let me know if any help is needed on that PR!

**Pull request closed without merging**
