### PR TITLE
update(systemd): solve some issues with systemd unit

### PR DESCRIPTION
**Pull request by Andreagit97**
**What type of PR is this?**

/kind bug

/kind cleanup

**Any specific area of the project related to this PR?**

/area engine

**What this PR does / why we need it**:

This PR solves some issues with `systemd` units. 

1. With the actual implementation `systemd restart` and `systemd condrestart` cause:

    ```
    Transaction contains conflicting jobs 'restart' and 'stop' for falcoctl-artifact-follow.service. Probably contradicting requirement dependencies configured.
    ```
    
    This issue is solved by removing the `Conflicts=` directive. The `Conflicts=` directive was here just to protect users from running more than one Falco instance with `systemd`, but since this causes issues we prefer to disable this behavior allowing to use `restart`/`condrestart` commands

2. The PR provides a new environment variable to disable the dialog at installation time `FALCO_FRONTEND`, if you don't want the dialog enabled by default when starting the unit you should use  `FALCO_FRONTEND=noninteractive`. Examples:

    ```
    sudo FALCO_FRONTEND=noninteractive apt install falco 
    sudo FALCO_FRONTEND=noninteractive yum install falco 
    ```

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by FedeDP — APPROVED** [review]
/approve

**Review by leogr — DISMISSED** [review]
/milestone 0.34.0

**Review by FedeDP — APPROVED** [review]
Great Fix!
/approve

**Comment by FedeDP** [comment]
Tested and works like a charm on rpm based distro!

**Review by therealbobo — APPROVED** [review]

**Review by jasondellaluce — APPROVED** [review]

**Pull request merged**
