### PR TITLE
add attestation for falco

### LINKED ISSUE #2649: SLSA Provenance Attestation for Falco
**Motivation**

We have signatures with cosign, and our next step is to add provenance attestations to images and artifacts as well, in the same way we have in Falcoctl

cc @cpanato @developer-guy

### PR DESCRIPTION
**Pull request by cpanato**
**What type of PR is this?**
/kind feature
/kind release

**Any specific area of the project related to this PR?**
/area build

**What this PR does / why we need it**:

- add attestation for falco
we need to hold this PR until the action supports the pushes to non ghcr.io registries
see Issue https://github.com/actions/attest-build-provenance/issues/80

/hold

/assign @LucaGuerra @leogr 

**Which issue(s) this PR fixes**:

Fixes #2649

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
add attestation for falco
```

### CODE REVIEW

**Comment by FedeDP** [comment]
/milestone TBD

(@LucaGuerra feel free to change the milestone!)

**Comment by leogr** [comment]
@cpanato @LucaGuerra 
any news on this?

**Comment by cpanato** [comment]
i was in pto, returned today :) i will re-check this soon

**Comment by leogr** [comment]
@cpanato should we reopen this? :thinking:

**Comment by cpanato** [comment]
PTAL @leogr

**Review by leogr — APPROVED** [review]

**Comment by cpanato** [comment]
PTAL @leogr @LucaGuerra

**Review by LucaGuerra — APPROVED** [review]
Thank you!

**Review by FedeDP — APPROVED** [review]
/approve

**Pull request merged**
