### PR TITLE
Add codespell GitHub Action

### PR DESCRIPTION
**Pull request by invidian**
**What type of PR is this?**

/kind cleanup

**Any specific area of the project related to this PR?**

> /area tests

**What this PR does / why we need it**:

Folllow up to #1961 to prevent common typos to be added to the repo.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jasondellaluce** [comment]
Hey @invidian, I think this is super helpful. I noticed you based this branch on the one of https://github.com/falcosecurity/falco/pull/1961 and now this is causing merge conflict. Would you be able to rebase this to `master`? Thanks!

**Comment by invidian** [comment]
I'll rebase soon, sure.

**Comment by invidian** [comment]
Rebased. Also had to fix some newly added typos to make CI pass again.

**Review by leogr — APPROVED** [review]
Cool, thank you :clap: 

/approve

/milestone 0.32.0

**Review by jasondellaluce — APPROVED** [review]
/approve

**Pull request merged**
