### PR TITLE
Add Xenit AB to adopters

### PR DESCRIPTION
**Pull request by NissesSenap**
Signed-off-by: Edvin Norling <edvin.norling@xenit.se>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

/kind documentation

> /kind failing-test

> /kind feature

> /kind release

> If contributing rules or changes to rules, please make sure to also uncomment one of the following line:

> /kind rule-update

> /kind rule-create

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

> /area engine

> /area rules

> /area tests

> /area proposals

> /area CI

**What this PR does / why we need it**:

Add Xenit AB as adopters of falco

**Which issue(s) this PR fixes**:

Fixes # N/A

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**: No

```release-note
NONE
```

### CODE REVIEW

**Comment by Andreagit97** [comment]
/milestone 0.34.0
cc @leogr

**Review by leogr — APPROVED** [review]
:hugs:

**Comment by leogr** [comment]
Update: I've fixed the release note block. @poiana should merge the PR now

**Comment by leogr** [comment]
Closing and reopening to trigger the CI :crossed_fingers: 
/close

**Pull request merged**
