### PR TITLE
new(config): explicitly add the `simulate_drops` config

### PR DESCRIPTION
**Pull request by Andreagit97**
**What type of PR is this?**

/kind cleanup

**Any specific area of the project related to this PR?**

**What this PR does / why we need it**:

This PR adds a config that can be used for debugging purposes, the `simulate_drops` config. This PR is just a proposal maybe there is a particular reason why we don't expose it directly to the user, any feedback is welcome :)

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
new(config): explicitly add the `simulate_drops` config
```

### CODE REVIEW

**Review by leogr — CHANGES_REQUESTED** [review]
It is already supported? 
Could you link the relevant PR (or code parts) that implement this feature?

**Comment by leogr** [comment]
> It is already supported? Could you link the relevant PR (or code parts) that implement this feature?

Sorry I pushed "Request change" by mistake :(

**Review by leogr — COMMENTED** [review]
trying to remove the "Request changes"

**Review by jasondellaluce — APPROVED** [review]

**Pull request merged**
