### PR TITLE
vote: add sgaist to OWNERS

### PR DESCRIPTION
**Pull request by sgaist**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

/kind documentation

> /kind failing-test

> /kind feature

> /kind release

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

> /area engine

> /area tests

> /area proposals

> /area CI

**What this PR does / why we need it**:

As discussed during the community call, this follows the process to become part of the maintainers of falco.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by incertum** [comment]
Big +1 from my side ❤️ 

Samuel has been helping us tremendously over the past ~7 months, most notably in the following areas:
- Falco outputs
- C++ coding standards / style / hygiene
- Falco metrics Prometheus support
- PR reviews
- General technical guidance

Thrilled to have you officially onboard as core maintainer. Enjoy the ride 🙃!

**Comment by FedeDP** [comment]
Big +1 from me! He already proved to be able to easily scale on the project and contributed many improvements and worked with Melissa on the new metrics framework.
We need people like you :) 
Also, he doesn't mind writing good C++ code and that alone is worth it :laughing:

**Comment by leogr** [comment]
Big :+1:  from me, too. I second what Melissa and Fede already wrote. Also, I want to thank you again for the significant contributions you have made in the last few months.

**Comment by Andreagit97** [comment]
+1! Welcome on board :rocket:!

**Comment by LucaGuerra** [comment]
+1! 🚀

**Comment by jasondellaluce** [comment]
Definitely +1!

**Review by leogr — APPROVED** [review]

**Review by FedeDP — APPROVED** [review]
/approve

**Review by jasondellaluce — APPROVED** [review]
/approve

**Pull request merged**
