### PR TITLE
fix: output hostname when `json_output` is enabled and correct env var name

### LINKED ISSUE #1520: Hostname of alert origin not present in HTTP output
**Motivation**

When configuring falco to send alerts to falcosidekick using the falco HTTP output the hostname of the originating machine/node is not present. This makes it near impossible to follow-up on alerts that don't have any Kubernetes metadata attached.

I am not sure if the hostname is already sent over the HTTP output and whether it is simply not sent to the destination medium (in my case Slack).

**Feature**

I would like to be able to see the hostname of the machine/node that triggered an alert.

**Alternatives**

N/A

**Additional context**

N/A

### PR DESCRIPTION
**Pull request by leogr**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

/kind cleanup

**Any specific area of the project related to this PR?**

/area engine

**What this PR does / why we need it**:

https://github.com/falcosecurity/falco/pull/1989 did not actually fix the problem as reported in  https://github.com/falcosecurity/falco/issues/1520#issuecomment-1221598987 by @adnankobir :pray: 

I have also fixed the naming of the env var that can be used to override the hostname value.

**Which issue(s) this PR fixes**:

Fixes #1520

**Special notes for your reviewer**:

/milestone 0.33.0

cc @adnankobir

**Does this PR introduce a user-facing change?**:

```release-note
fix: hostname was not present when `json_output: true`
update: use `FALCO_HOSTNAME` env var to override the hostname value
```

### CODE REVIEW

**Review by jasondellaluce — DISMISSED** [review]
/approve

**Review by jasondellaluce — APPROVED** [review]
/approve

**Review by FedeDP — APPROVED** [review]
/approve

**Pull request merged**
