### PR TITLE
update(script): makes user able to pass custom option to driver-loade…

### LINKED ISSUE #1896: Create env variable to add options when loading the driver
**Motivation**

I have a usecase of Falco where I have a workflow that compiles Falco kernel module and upload it in Artifactory. 
When I download it, I have to pass credentials in the header of the request so I need to add options in the curl command in the falco-driver-loader script.

**Feature**

I would like an environment variable to pass options to the curl command that download Falco kernel module

**Alternatives**

Add an environment variable like FALCO_DRIVER_CURL_CUSTOM_OPTIONS because FALCO_DRIVER_CURL_OPTIONS already exists

**Additional context**

### PR DESCRIPTION
**Pull request by andreabonanno**
…r curl command

Signed-off-by: Andrea Bonanno <andrea@bonanno.cloud>

**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

**What this PR does / why we need it**:

Makes possible for the user to pass additional custom options to the `curl` command invoked by `falco-driver-loader`, appending them to the ones usually used.

**Which issue(s) this PR fixes**:

Fixes #1896 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by tspearconquest** [comment]
As a user with security concerns in mind, I would like to see that this does not allow passing arbitrary curl options, and instead would prefer if the environment variable was targeted toward the specific use case you have in mind.

**Comment by japui** [comment]
update(script): torna o usuário capaz de passar a opção personalizada para o driver-loade

**Comment by tspearconquest** [comment]
Hi @leogr will there be a release before this becomes rotten?

**Comment by leogr** [comment]
> Hi @leogr will there be a release before this becomes rotten?

I apologize I had lost track of this. 
I believe we can merge it, but perhaps we should fix the env vat naming. 

cc @jasondellaluce 

/remove-lifecycle stale

**Review by leogr — APPROVED** [review]

**Review by Andreagit97 — APPROVED** [review]
/approve

**Pull request merged**
