### PR TITLE
update(cmake): bump libs to 0.17.2 and sync merge 0.38.1 PRs

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind release

**Any specific area of the project related to this PR?**

/area build

**What this PR does / why we need it**:

Bumps libs to 0.17.2 for the upcoming Falco 0.38.1 patch release.
Also, cherry picks:
* https://github.com/falcosecurity/falco/pull/3230
* https://github.com/falcosecurity/falco/pull/3232
* https://github.com/falcosecurity/falco/pull/3236
* https://github.com/falcosecurity/falco/pull/3238
* https://github.com/falcosecurity/falco/pull/3239
* https://github.com/falcosecurity/falco/pull/3228

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
update(cmake): bump libs to 0.17.2
```

### CODE REVIEW

**Comment by FedeDP** [comment]
/hold
Will also cherry pick 0.38.1 PRs.

**Review by LucaGuerra — APPROVED** [review]
I would change PR title and description because it does not match with the content :)

**Review by jasondellaluce — APPROVED** [review]

**Review by leogr — APPROVED** [review]

**Comment by FedeDP** [comment]
Thanks Luke, you are right!

**Pull request merged**
