### PR TITLE
Fix some typos

### PR DESCRIPTION
**Pull request by invidian**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

/kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

> If contributing rules or changes to rules, please make sure to also uncomment one of the following line:

> /kind rule-update

> /kind rule-create

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

> /area engine

> /area rules

> /area tests

> /area proposals

**What this PR does / why we need it**:

Fixing some typos found while browsing other projects shipping the rules.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

Found by running the following command:
codespell -f -H -L aks,creat,chage -S .git

I can also add a GitHub Action using the command above to prevent more typos being added in the future.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by jasondellaluce — APPROVED** [review]
/approve

Thank you for this! 😄  I think adding a GitHub Action for this would be a great contribution. Would you like to open a PR for it to gather some feedback? 🙏🏼

**Comment by invidian** [comment]
>Thank you for this! smile I think adding a GitHub Action for this would be a great contribution. Would you like to open a PR for it to gather some feedback? 🙏🏼

Thanks for review and approval. I opened #1962 then ;)

**Review by leogr — APPROVED** [review]
/approve

**Pull request merged**
