### PR TITLE
Added the OpenSSF Scorecard Badge

### PR DESCRIPTION
**Pull request by harshitasao**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:
This PR adds OpenSSF Scorecard Badge in the README file.

The project already has the Scorecard GitHub Action running, so adding the scorecard badge would be quite handy. So that the results can be shown as a badge in the repository's README. This badge serves as a quick indicator of the project's security posture, helping users and contributors evaluate the project's security practices quickly.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**: N/A

**Does this PR introduce a user-facing change?**: N/A

```release-note
NONE
```

### CODE REVIEW

**Comment by LucaGuerra** [comment]
Thank you! I have just a question, if you look at the preview this OpenSSF badge style looks different from the other OpenSSF badge we already have, is it possible to apply the same style to both? Thanks!

**Comment by leogr** [comment]
> Thank you! I have just a question, if you look at the preview this OpenSSF badge style looks different from the other OpenSSF badge we already have, is it possible to apply the same style to both? Thanks!

I guess we have just to add `style=for-the-badge`

@harshitasao could you address that please? :pray:

**Comment by harshitasao** [comment]
Sorry for the delay. I have styled the badge as mentioned and converted the scorecard link from JSON to Standard (human readable) format.

**Review by LucaGuerra — APPROVED** [review]
Thank you for the contribution!

**Review by FedeDP — APPROVED** [review]
/approve

**Pull request merged**
