### PR TITLE
feat(metrics): sync libs metrics collector refactor

### PR DESCRIPTION
**Pull request by incertum**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

/kind cleanup

/kind design

> /kind documentation

> /kind failing-test

> /kind feature

> /kind release

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

/area engine

> /area tests

> /area proposals

> /area CI

**What this PR does / why we need it**:

Sync libs

Includes a handful of naming changes. A notice to https://falco.org/docs/metrics/falco-metrics/ will be added well in advance of Falco 0.38.0.

```
falco.hostname -> evt.hostname to be consistent with the newer evt.hostname filtercheck
cpu_usage_perc_total_host -> host_cpu_usage_perc
memory_used_host -> host_memory_used_kb (or host_memory_used_mb)
procs_running_host -> host_procs_running
open_fds_host -> host_open_fds
memory_rss -> memory_rss_kb (or memory_rss_mb)
memory_pss -> memory_pss_kb (or memory_pss_mb)
memory_vsz -> memory_vsz_kb (or memory_vsz_mb)
container_memory_used -> container_memory_used_bytes (or container_memory_used_mb)
```

**Which issue(s) this PR fixes**:

Fixes #

https://github.com/falcosecurity/libs/issues/1463

Requires merged https://github.com/falcosecurity/libs/pull/1652 plus a libs bump.

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
feat(metrics): coherent metrics stats model  including few metrics naming changes
```

### CODE REVIEW

**Comment by incertum** [comment]
New example output:


```yaml
{
  "hostname": "test",
  "output": "Falco metrics snapshot",
  "output_fields": {
    "evt.hostname": "test",
    "evt.source": "syscall",
    "evt.time": 1709705243681512818,
    "falco.container_memory_used_mb": 0.0,
    "falco.cpu_usage_perc": 1.6,
    "falco.duration_sec": 144,
    "falco.evts_rate_sec": 126065.4,
    "falco.host_boot_ts": 1708753667000000000,
    "falco.host_cpu_usage_perc": 2.3,
    "falco.host_memory_used_mb": 10169.4,
    "falco.host_num_cpus": 20,
    "falco.host_open_fds": 21272,
    "falco.host_procs_running": 3,
    "falco.kernel_release": "6.6.7-200.fc39.x86_64",
    "falco.memory_pss_mb": 135.8,
    "falco.memory_rss_mb": 138.0,
    "falco.memory_vsz_mb": 1125.3,
    "falco.n_added_fds": 287251,
    "falco.n_added_threads": 2479,
    "falco.n_cached_fd_lookups": 2799364,
    "falco.n_cached_thread_lookups": 3202933,
    "falco.n_containers": 2,
    "falco.n_drops_full_threadtable": 0,
    "falco.n_failed_fd_lookups": 21283,
    "falco.n_failed_thread_lookups": 4297,
    "falco.n_fds": 147123,
    "falco.n_missing_container_images": 0,
    "falco.n_noncached_fd_lookups": 567716,
    "falco.n_noncached_thread_lookups": 444988,
    "falco.n_removed_fds": 189764,
    "falco.n_removed_threads": 706,
    "falco.n_retrieve_evts_drops": 693392,
    "falco.n_retrieved_evts": 249868,
    "falco.n_store_evts_drops": 0,
    "falco.n_stored_evts": 251335,
    "falco.n_threads": 1772,
    "falco.num_evts": 3397379,
    "falco.num_evts_prev": 3271130,
    "falco.outputs_queue_num_drops": 0,
    "falco.start_ts": 1709705099677741260,
    "falco.version": "0.38.0-121+5185f15",
    "scap.engine_name": "bpf",
    "scap.evts_drop_rate_sec": 0.0,
    "scap.evts_rate_sec": 132035.8,
    "scap.n_drops": 0,
    "scap.n_drops_buffer_clone_fork_enter": 0,
    "scap.n_drops_buffer_clone_fork_exit": 0,
    "scap.n_drops_buffer_close_exit": 0,
    "scap.n_drops_buffer_connect_enter": 0,
    "scap.n_drops_buffer_connect_exit": 0,
    "scap.n_drops_buffer_dir_file_enter": 0,
    "scap.n_drops_buffer_dir_file_exit": 0,
    "scap.n_drops_buffer_execve_enter": 0,
    "scap.n_drops_buffer_execve_exit": 0,
    "scap.n_drops_buffer_open_enter": 0,
    "scap.n_drops_buffer_open_exit": 0,
    "scap.n_drops_buffer_other_interest_enter": 0,
    "scap.n_drops_buffer_other_interest_exit": 0,
    "scap.n_drops_buffer_proc_exit": 0,
    "scap.n_drops_buffer_total": 0,
    "scap.n_drops_bug": 0,
    "scap.n_drops_page_faults": 0,
    "scap.n_drops_perc": 0.0,
    "scap.n_drops_prev": 0,
    "scap.n_drops_scratch_map": 0,
    "scap.n_evts": 3436380,
    "scap.n_evts_prev": 3304152,
    "scap.page_fault_kern.avg_time_ns": 0,
    "scap.page_fault_kern.run_cnt": 0,
    "scap.page_fault_kern.run_time_ns": 0,
    "scap.page_fault_user.avg_time_ns": 0,
    "scap.page_fault_user.run_cnt": 0,
    "scap.page_fault_user.run_time_ns": 0,
    "scap.sched_process_e.avg_time_ns": 2066,
    "scap.sched_process_e.run_cnt": 719,
    "scap.sched_process_e.run_time_ns": 1485896,
    "scap.sched_switch.avg_time_ns": 0,
    "scap.sched_switch.run_cnt": 0,
    "scap.sched_switch.run_time_ns": 0,
    "scap.signal_deliver.avg_time_ns": 0,
    "scap.signal_deliver.run_cnt": 0,
    "scap.signal_deliver.run_time_ns": 0,
    "scap.sys_enter.avg_time_ns": 117,
    "scap.sys_enter.run_cnt": 7641969,
    "scap.sys_enter.run_time_ns": 896903922,
    "scap.sys_exit.avg_time_ns": 123,
    "scap.sys_exit.run_cnt": 7642055,
    "scap.sys_exit.run_time_ns": 946918695
  },
  "priority": "Informational",
  "rule": "Falco internal: metrics snapshot",
  "source": "internal",
  "time": "2024-03-06T06:07:23.681512818Z"
}
```

**Comment by incertum** [comment]
To the reviewers: `libs` PR should be ready soon ...

See https://github.com/falcosecurity/falco/issues/3131 -> There needs to be a significant refactor to expand the Falco metrics following our `libs` refactor. Therefore, I would regard this PR as merely intending to sync libs and assume that the falco metrics interface will be refactored very soon anyway.

CC @sgaist

**Comment by FedeDP** [comment]
Bumped libs to 0.15.1 and rebased on top of master.

**Review by Andreagit97 — APPROVED** [review]
/approve

**Review by FedeDP — APPROVED** [review]
/approve

**Pull request merged**
