### PR TITLE
Enable docker cache layer in circleci

### PR DESCRIPTION
**Pull request by rajibmitra**
Signed-off-by: rajib <rajib.jolite@gmail.com>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

 /kind feature

> If contributing rules or changes to rules, please make sure to also uncomment one of the following line:

> /kind rule-update

> /kind rule-create

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

> /area engine

> /area examples

> /area rules

> /area integrations

> /area tests

> /area proposals

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by fntlnz** [comment]
Looks like we can’t have that @rajibmitra - circle says we need to upgrade plan

**Comment by leodido** [comment]
Screenshot 2020-01-28 at 14 24 56

/hold

**Comment by leodido** [comment]
Close for now.

In case we'll switch to a paid circleci plan, we'll re-open this.

**Pull request closed without merging**
