### PR TITLE
update(cmake): update libs to latest RC

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind cleanup

**Any specific area of the project related to this PR?**

/area build

**What this PR does / why we need it**:

Bumps libs to latest RC: 0.10.0-rc1
Bumps driver to latest RC: 4.0.0-rc1+driver

**Which issue(s) this PR fixes**:

NONE 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
update(cmake): bump libs and driver to latest RC.
```

### CODE REVIEW

**Comment by FedeDP** [comment]
We've got a couple of issues:
* one seems to depend upon the `strerror` rework that was done in scap:
```
/build/release/falcosecurity-libs-repo/falcosecurity-libs-prefix/src/falcosecurity-libs/userspace/libscap/strerror.c: In function 'scap_errprintf_unchecked':
/build/release/falcosecurity-libs-repo/falcosecurity-libs-prefix/src/falcosecurity-libs/userspace/libscap/strerror.c:41:3: error: ignoring return value of 'strerror_r', declared with attribute warn_unused_result [-Werror=unused-result]
   strerror_r(errnum, err_buf, sizeof(err_buf));
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/build/release/falcosecurity-libs-repo/falcosecurity-libs-prefix/src/falcosecurity-libs/userspace/libscap/strerror.c: At top level:
cc1: error: unrecognized command line option '-Wno-stringop-truncation' [-Werror]
cc1: all warnings being treated as errors
```
* the other seems a sporadic sigsegv on a corrupted free:
```
 Comparing engine fields checksum in falco_engine.h to actual fields
Thu Nov 24 13:56:03 2022: Falco version: 0.0.0 (x86_64)
Thu Nov 24 13:56:03 2022: Falco initialized with configuration file: /source/falco/falco.yaml
*** Error in `./falco': free(): invalid pointer: 0x0000000003014b20 ***
======= Backtrace: =========
```
Can't reproduce either of them locally; the latter seems only reproducible using our falco-builder image; the former seems reproduced only in circleci env.

**Comment by FedeDP** [comment]
The `strerror` one should be fixed now.

**Comment by FedeDP** [comment]
Updated to properly test libs 031e2082c45c46c79bde6ba37b9843b3d195ed6c commit (https://github.com/falcosecurity/libs/pull/736).

**Review by Andreagit97 — APPROVED** [review]
/approve

**Comment by FedeDP** [comment]
Bumped again to 81652de434948b6512fc0fef219a943b7907c47f. :P

**Comment by FedeDP** [comment]
`tests-integration-static` are now failing :(

**Review by jasondellaluce — APPROVED** [review]
/approve

**Review by leogr — APPROVED** [review]

**Review by jasondellaluce — COMMENTED** [review]
LGTM, but there is an uncovered `return` statement at line 176.

Just an idea: I'm wondering if it would not be easier to have a small construct automatically invoking the start/stop method to make sure that we never lose a call. Something like:

```cpp
class capture_controller
{
public:
	capture_controller(capture_controller&&) = default;
	capture_controller& operator = (capture_controller&&) = default;
	capture_controller(const capture_controller&) = delete;
	capture_controller& operator = (const capture_controller&) = delete;
	capture_controller(std::shared_ptr<sinsp> i): m_inspector(i)
	{
		m_inspector->start_capture();
	}
	~capture_controller()
	{
		m_inspector->stop_capture();
	}

private:
	std::shared_ptr<sinsp> m_inspector;	
};
```

Allocating one of these on `do_inspect`'s stack will always make sure that we call `stop_capture` when we get out of scope.

**Comment by Andreagit97** [comment]
@jasondellaluce at the end we put the `stop_capture` in the inspector destructor https://github.com/falcosecurity/libs/pull/755 in this way we can also avoid the class

**Review by leogr — APPROVED** [review]
:parrot:

**Pull request merged**
