### PR TITLE
adding frame.io quotes

### PR DESCRIPTION
**Pull request by srivastavaabhinav**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

/kind documentation

> /kind failing-test

> /kind feature

> /kind flaky-test

> If contributing rules or changes to rules, please make sure to also uncomment one of the following line:

> /kind rule-update

> /kind rule-create

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

> /area engine

> /area examples

> /area rules

> /area integrations

> /area tests

**What this PR does / why we need it**:

Adding Frame.io name in the list of Adopters.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mfdii** [comment]
@srivastavaabhinav would you please sign off on your commit? 

`git commit -s --amend`

**Comment by leodido** [comment]
Any news on this?

**Comment by leodido** [comment]
In case y'all agree I'm going to copy this PR (since I cannot modify its branch in the original fork, and no feedback from the author since 2 weeks).

What y'all think?

**Comment by fntlnz** [comment]
@leodido please do!

**Pull request closed without merging**
