### PR TITLE
fix(userspace/engine): fix memory leak

### PR DESCRIPTION
**Pull request by therealbobo**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

> /kind release

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

/area engine

> /area tests

> /area proposals

> /area CI

**What this PR does / why we need it**:

This fixes a memory leak: `compiler.compile()` allocates a `sinp_filter` but never destroys it.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
fix(userspace/engine): fix memory leak
```

### CODE REVIEW

**Review by incertum — APPROVED** [review]
/approve

I'll gladly test deploy soon and let's see. Evidence that it also happened when using Falco only for the k8s plugins suggests this is in the right area of the code base.

At the same time tons of servers do not show any memory leaks ... This is the puzzling part. It's nothing consistent or easy to find so to say.

**Review by FedeDP — APPROVED** [review]
/approve

**Comment by FedeDP** [comment]
/milestone 0.37.0 
There are conflicts; and i don't think this is that important to need custom code in the release branch.

**Pull request merged**
