### PR TITLE
update(.github): integrate Go regression tests

### PR DESCRIPTION
**Pull request by jasondellaluce**
**What type of PR is this?**

/kind cleanup

**Any specific area of the project related to this PR?**

/area tests

/area CI

**What this PR does / why we need it**:

This brings ring the Go regression tests of https://github.com/falcosecurity/testing into this repo and run them in the Github Actions CI.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
update(.github): integrate Go regression tests
```

### CODE REVIEW

**Comment by jasondellaluce** [comment]
This should now be ready for review. cc @FedeDP (the GHA CI man).

Once this is reviewed/accepted/merged, I'd propose opening a follow-up PR for deprecating the current Python regression tests (and the `falco-tester` image, accordingly), since they perform the same checks as the Go testing suite.

**Comment by FedeDP** [comment]
>  CI Build / test-dev-packages (static) / test-packages (pull_request) Failing after 12s 

:negative_squared_cross_mark:

**Comment by FedeDP** [comment]
Changes LGTM! Do we need to fix up the CI here?

**Comment by FedeDP** [comment]
Once this enters, i will update my #2532 to add also the static test on arm64; then i will bump number of nodes for arm64 on prow cluster and we can merge that too!

**Review by FedeDP — APPROVED** [review]
/approve

**Review by Andreagit97 — APPROVED** [review]
/approve

**Pull request merged**
