### PR TITLE
update(integration): move `/integration` to `contrib` repo

### LINKED ISSUE #1145: Move "integrations" to another repo
**Motivation**

As discussed during the 2020-04-15 community call, we agreed that [integrations](https://github.com/falcosecurity/falco/tree/master/integrations) should be community maintained so not officially supported for every release.

**Feature**
 
~~First, ensure all related PRs are merged: #1044 #1136 #1140~~ DONE

~~Finally, when the new repo has been created,~~ Move [integrations](https://github.com/falcosecurity/falco/tree/master/integrations) to the new [contrib repo](https://github.com/falcosecurity/contrib), see :point_right:  https://github.com/falcosecurity/contrib/pull/3 (thanks @maxgio92 for taking care of that!).

Finally, remove the `/integration` folder from this repo.

**Alternatives**

**Additional context**

- @kris-nova should submit a PR to [falco-website](https://github.com/falcosecurity/falco-website)  in order to clean up non-official installation methods from docs :point_right: https://github.com/falcosecurity/falco-website/pull/184
- #1114

/assign

### PR DESCRIPTION
**Pull request by leogr**
Signed-off-by: Leonardo Grasso <me@leonardograsso.com>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

/kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

> If contributing rules or changes to rules, please make sure to also uncomment one of the following line:

> /kind rule-update

> /kind rule-create

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

> /area engine

> /area examples

> /area rules

/area integrations

> /area tests

> /area proposals

**What this PR does / why we need it**:
As discussed with the community we want to move `/integrations` to the [contrib](https://github.com/falcosecurity/contrib). Thus we have to clean it up here.

**Which issue(s) this PR fixes**:

Fixes #1145

**Special notes for your reviewer**:
:point_right: https://github.com/falcosecurity/contrib/pull/3
/hold 

/milestone 0.23.0

**Does this PR introduce a user-facing change?**:

```release-note
update(integration): move `/integrations` to `contrib` repo
```

### CODE REVIEW

**Comment by leogr** [comment]
@kris-nova 
I will cancel "hold" as soon as https://github.com/falcosecurity/falco-website/pull/184 gets done

**Comment by fntlnz** [comment]
🧹🧹🧹🧹🧹🧹 Cleaning!

**Comment by leogr** [comment]
As per https://github.com/falcosecurity/falco/pull/1184

**Comment by JPLachance** [comment]
Quick question: Did someone create a new repository for the Falco Puppet module? Did someone update the Puppet forge readme? 😄

**Comment by leogr** [comment]
> Quick question: Did someone create a new repository for the Falco Puppet module? Did someone update the Puppet forge readme?

Hi @JPLachance 

the Puppet module was moved [here](https://github.com/falcosecurity/evolution/tree/master/integrations/puppet-module) and is currently in [sandbox level](https://github.com/falcosecurity/evolution#sandbox).
/cc @maxgio92 

The [Puppet forge readme](https://forge.puppet.com/sysdig/falco) seems to be outdated :)
Not sure who can help out with that :eyes:

**Comment by warmfusion** [comment]
For those who find themselves here trying to find things like puppet modules;

The 'contrib' repos mentioned all over the place are in fact now called 'Falcon Evolution' are found here

https://github.com/falcosecurity/evolution

**Pull request merged**
