### PR TITLE
build: add minimal and statically linked builds

### PR DESCRIPTION
**Pull request by leogr**
**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

/area build

/area engine

**What this PR does / why we need it**:

This PR follows https://github.com/draios/sysdig/pull/1682 up and introduces two building options:
- `MINIMAL_BUILD` allows making a stripped-down version of the Falco binary containing only the engine and basic input/output
- `MUSL_OPTIMIZED_BUILD` allows making a statically linked binary (using musl)

The two options can be used separately. 

Finally, this PR adds a new step in the CI pipeline to build and publish a new kind of artifact: a TGZ package containing the statically linked binary of Falco.

**Special notes for your reviewer**:

TODOs:
- [x] enable publishing the new TGZ for git tag (~~currently enabled on the master branch only - dev release~~) done by https://github.com/falcosecurity/falco/pull/1377/commits/a19e759c33d7c1f9d982fe9fc09d3a2ad292f0e3
- [x] ~~list the new TGZ in the README.md~~ not needed, since the binary link points to both static and non-static tgzs
- [x] mark the minimal build as experimental (we will not publish it)
- [x] with `-DMINIMAL_BUILD=True`, the sysdig dependency produces a reduced set of fields thus [this check](https://github.com/falcosecurity/falco/blob/430ba2b9d8a336fab8e60967d11d7db278b69802/userspace/falco/verify_engine_fields.sh#L7) will fail :point_right: disable the checksum for minimal build (as discussed with @leodido and @fntlnz)
- [x] add CI step for minimal build
- [x] use the static build (musl) as default binary for the TGZ
- [x] use the static build (musl) as default for the `falcosecurity/no-driver` container image
- [x] https://github.com/draios/sysdig/pull/1682 needs to be merged
- [x] sysdig version must be updated here, once :point_up: that gets merged (see the comment in the code)
- [x] push the modified falco-tester to the latest tag, and update the reference here (see the comment in the code)

- [x] document the new building options in https://github.com/falcosecurity/falco-website

/hold
/milestone 0.26.0

**Does this PR introduce a user-facing change?**:

```release-note
new: tgz (tarball) containing the statically-linked (musl) binary of Falco is now automatically built and published on bintray
update: falcosecurity/falco-no-driver image now uses the statically-linked Falco
```

### CODE REVIEW

**Comment by kris-nova** [comment]
Should we expect any changes with the signal handler with this? I ran @fntlnz's static binary from some time ago and I noticed that Falco was no longer respecting `^C` signals from my keyboard. I had to `kill -9` the PID in order to exit the program.

Screenshot from 2020-09-02 16-10-38

**Comment by fntlnz** [comment]
@kris-nova that might be a problem in the binary I generated back then. I just tested this with the latest commit and the signal handlers are having the right behavior. 
image

**Comment by leogr** [comment]
> Should we expect any changes with the signal handler with this? I ran @fntlnz's static binary from some time ago and I noticed that Falco was no longer respecting `^C` signals from my keyboard. I had to `kill -9` the PID in order to exit the program.
> 
> Screenshot from 2020-09-02 16-10-38

Hey Kris,

I did not notice this problem in the statically linked build.

BTW, the one in your screenshot should not be a build from this branch since from version 0.25.0 Falco prints out the version number (can you see that in the @fntlnz screenshot).

**Review by leodido — APPROVED** [review]
🧨

**Review by fntlnz — APPROVED** [review]

**Pull request merged**
