### PR TITLE
drop Falco luajit module, use the one provied by libs

### PR DESCRIPTION
**Pull request by FedeDP**
```
Signed-off-by: Federico Di Pierro <nierro92@gmail.com>

Co-authored-by: Leonardo Grasso <me@leonardograsso.com>
Co-authored-by: Jason Dellaluce <jasondellaluce@gmail.com>
```

**What type of PR is this?**

/kind cleanup

**Any specific area of the project related to this PR?**

/area build

**What this PR does / why we need it**:

The PR allows Falco to build using luaJIT provided by libs.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by FedeDP** [comment]
We still need to rebase this PR to falco master once https://github.com/falcosecurity/falco/pull/1782 is merged.

**Comment by FedeDP** [comment]
Rebased!

**Review by leogr — APPROVED** [review]
/approve

**Review by mstemm — APPROVED** [review]

**Pull request merged**
