### PR TITLE
rule update (Delete or rename shell history): whitelist shell processes

### PR DESCRIPTION
**Pull request by Kaizhe**
Signed-off-by: kaizhe <derek0405@gmail.com>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

> If contributing rules or changes to rules, please make sure to also uncomment one of the following line:

 /kind rule-update

> /kind rule-create

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

> /area engine

 /area rules

> /area tests

> /area proposals

**What this PR does / why we need it**:

Resolve the FP that caused by shell processes update shell history themselves.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

rule(Delete or rename shell history): whitelist shell processes

```

### CODE REVIEW

**Comment by mstemm** [comment]
lgtm! This is nice as it will prevent events when bash itself writes the history when the shell exits.

**Comment by leodido** [comment]
@Kaizhe is this PR ready to be merged in?

**Comment by leodido** [comment]
@Kaizhe any news on this?

**Comment by Kaizhe** [comment]
I will close it for now

**Pull request closed without merging**
