### PR TITLE
docs: add jasondellaluce to OWNERS

### PR DESCRIPTION
**Pull request by jasondellaluce**
Signed-off-by: Jason Dellaluce <jasondellaluce@gmail.com>

**What type of PR is this?**

/kind documentation

**Any specific area of the project related to this PR?**

**What this PR does / why we need it**:

I would like propose myself as a maintainer of `falcosecurity/falco`.

After actively contributing to this repository over the past three months, I want to commit to spend my time working on it. I think my case meets the criteria of the _process for becoming a maintainer_ from [falcosecurity governance](https://github.com/falcosecurity/.github/blob/master/GOVERNANCE.md#process-for-becoming-a-maintainer). As such, I would happily to take on the maintainer duties to support Falco's growth and to assist other contributors too.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
docs: add jasondellaluce to OWNERS
```

### CODE REVIEW

**Comment by leogr** [comment]
big +1 for me, as I already said [here](https://kubernetes.slack.com/archives/CMWH3EH32/p1639155337464200?thread_ts=1639154830.463600&cid=CMWH3EH32).

Just waiting for hearing from @falcosecurity/falco-maintainers before giving my approval to this PR :)

**Comment by danpopnyc** [comment]
+1

**Comment by mstemm** [comment]
+1 from me!

**Comment by kris-nova** [comment]
If you meet the criteria there isn’t really much we can say. From a distance i’m fine with it, although it might be worthwhile trying to find some non-sysdig maintainers in the future as well. 

Otherwise welcome aboard as far as i’m concerned. 🎉

**Comment by kris-nova** [comment]
/approve 

😅

**Review by leogr — APPROVED** [review]

**Review by mstemm — APPROVED** [review]

**Comment by fntlnz** [comment]
@jasondellaluce from the other comments above looks like your organization association (the company who pays your work on this project is with Sysdig). If this is true, please make sure this is reflected here https://github.com/falcosecurity/.github/blob/0773f4bab64ed180d5963eb71363e028e1294a9c/maintainers.yaml#L231

That file is used by CNCF’s devstats and for organizational voting. Please read here https://github.com/falcosecurity/.github/blob/master/GOVERNANCE.md


And welcome onboard! And thanks for the work and effort  you are  putting in the project.

**Comment by jasondellaluce** [comment]
Hey @fntlnz, thank you for noticing! My name was already in the list, but apparently I was removed by mistake sometime ago. I just opened a PR on `test-infra` to re-add my record: https://github.com/falcosecurity/test-infra/pull/587

**Comment by fntlnz** [comment]
Cool cool, thank you @jasondellaluce

**Pull request merged**
