### PR TITLE
feat(userspace/outputs_http): Add option for mTLS

### PR DESCRIPTION
**Pull request by annadorottya**
**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

/area engine

**What this PR does / why we need it**: Currently there is no mTLS option for the HTTP output, it would be more secure to have this feature.

**Which issue(s) this PR fixes**:  

Fixes https://github.com/falcosecurity/falco/issues/2632

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
new(falco/config): add new configurations for http_output that allow mTLS
```

### CODE REVIEW

**Comment by jasondellaluce** [comment]
cc @alacuku

**Comment by incertum** [comment]
This seems very useful, are we on track to allocate time for review and feature finalization? Thank you! @leogr?

**Comment by leogr** [comment]
> This seems very useful, are we on track to allocate time for review and feature finalization? Thank you! @leogr?

I agree this is useful. I believe we are still in time. Let's try to merge this for Falco 0.36.
cc @Andreagit97 @FedeDP

**Comment by Andreagit97** [comment]
I've tested it and it works, thank you for this! Could you rebase please @annadorottya?

**Review by leogr — DISMISSED** [review]

**Comment by annadorottya** [comment]
Sorry I accidentally merged the master branch into my branch, which removed the lgtm and approved labels, can you approve again @leogr ? 🙇

**Comment by incertum** [comment]
No worries even with a direct rebase all previous approvals are removed. Leo and Andrea will approve tomorrow Europe time.

**Review by Andreagit97 — APPROVED** [review]
/approve
Thank you!

**Pull request merged**
