### PR TITLE
update(cmake): bump falcoctl to v0.8.0-rc4

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind release

**Any specific area of the project related to this PR?**

/area build

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by incertum — DISMISSED** [review]
/approve

**Review by leogr — APPROVED** [review]

**Comment by FedeDP** [comment]
>  CI Build / test-dev-packages / test-packages (pull_request) Failing after 4m 

The test is failing because new falcoctl has different strings when eBPF and kmod gets compiled.
Also, kmod building is failing because a fix is needed on driverkit and needs to be ported back to falcoctl (v0.8.0-rc4 i assume).
/hold
Will bump to falcoctl 0.8.0-rc4 once it's ready.

**Comment by FedeDP** [comment]
Opened driverkit PR: https://github.com/falcosecurity/driverkit/pull/343

**Comment by FedeDP** [comment]
For completeness, i also tried to run the same test passing the `LSAN_OPTIONS` that we also specify in our reusable workflow: https://github.com/falcosecurity/falco/blob/master/.github/workflows/reusable_test_packages.yaml#L56C11-L56C23

Still success.

**Review by jasondellaluce — APPROVED** [review]
/approve

**Review by incertum — APPROVED** [review]
/approve

**Pull request merged**
