### PR TITLE
cleanup(test): remove python regression tests

### PR DESCRIPTION
**Pull request by jasondellaluce**
**What type of PR is this?**

/kind cleanup

**Any specific area of the project related to this PR?**

/area tests

/area CI

**What this PR does / why we need it**:

Following up the contribution of the `testing` repository (https://github.com/falcosecurity/evolution/issues/246), this PR deprecates and removes the python-based regression testing suite, no more used. Now that they have no purpose anymore, the following have been removed:
- CircleCI jobs
- `builder`, `tester`, and `local` docker images files
- Github Action workflow that used to bump the `builder` and `tester` images

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by FedeDP — APPROVED** [review]
/approve

**Review by incertum — APPROVED** [review]
/approve

**Review by LucaGuerra — APPROVED** [review]

**Pull request merged**
