### PR TITLE
fix: adopt new libsinsp logger

### PR DESCRIPTION
**Pull request by therealbobo**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

/kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

> /kind release

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

> /area engine

> /area tests

> /area proposals

> /area CI

**What this PR does / why we need it**:

This adopts the new logger from libs.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by Andreagit97 — DISMISSED** [review]
/approve

**Comment by Andreagit97** [comment]
before this, we need to bump Falco to the latest libs commit

**Comment by incertum** [comment]
Could we take care of this next? To make Falco compatible with current libs master?

**Review by incertum — DISMISSED** [review]
/approve

/unhold

**Comment by FedeDP** [comment]
Engine checksum must be updated ;)

**Comment by jasondellaluce** [comment]
@therealbobo the checksum change must also include a version bump

**Review by jasondellaluce — APPROVED** [review]
/approve

**Review by FedeDP — APPROVED** [review]
/approve

**Pull request merged**
