### PR TITLE
cleanup(OWNERS): remove inactive approvers

### PR DESCRIPTION
**Pull request by jasondellaluce**
**What type of PR is this?**

/kind cleanup

/kind documentation

**Any specific area of the project related to this PR?**

/area engine

**What this PR does / why we need it**:

For https://github.com/falcosecurity/evolution/issues/157, this PR moves inactive approvers (who had very little or zero contributions over the past 6 months) from `approvers` to `emeritus_approvers` in OWNERS.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by fntlnz — CHANGES_REQUESTED** [review]
Please restore https://github.com/falcosecurity/falco/issues/2115#issuecomment-1176045086

**Review by leodido — CHANGES_REQUESTED** [review]
https://github.com/falcosecurity/falco/issues/2115#issuecomment-1176048415

**Review by leogr — COMMENTED** [review]
This PR has been on hold for 13 days now. It has been blocked because of the pending "change requests" (and the reviewer decided to step down). In any case, the change looks legit to me since I have not seen any relevant activity from them in the last 6 months (as per our governance), and in the last year in general.

I think all the remaining maintainers agree (cc @mstemm @jasondellaluce @FedeDP ). So, I'd ask @jasondellaluce to close this PR and open a new one.

**Comment by jasondellaluce** [comment]
> This PR has been on hold for 13 days now. It has been blocked because of the pending "change requests" (and the reviewer decided to step down). In any case, the change looks legit to me since I have not seen any relevant activity from them in the last 6 months (as per our governance), and in the last year in general.
> 
> I think all the remaining maintainers agree (cc @mstemm @jasondellaluce @FedeDP ). So, I'd ask @jasondellaluce to close this PR and open a new one.

I agree and confirm my standpoint as in https://github.com/falcosecurity/evolution/issues/157. Considering that the reviewers expressed their will to step down, I'm closing this in favor of #2134.

/close

**Pull request closed without merging**
