### PR TITLE
rules: the required_engine_version is now on by default

### LINKED ISSUE #1272: Falco rules file should have `required_engine_version: 6`
**Describe the bug**

Hi, I noticed that https://github.com/falcosecurity/falco/commit/70b9bfe1d6bf4d44e7ad000d726603418ad37342#diff-6acd8aa2e534d1ed83e275bf658d936b added a new rule Container Drift Detected (open+create) that requries falco engine version 6. However, the rules file itself doesn’t have any required_engine_version block. There’s a commented out version here: https://github.com/falcosecurity/falco/blob/master/rules/falco_rules.yaml#L26. 

If users tried to load this rules file with older falco versions, they wouldn't be able to load the file, as the new field `evt.is_open_exec` doesn't work with older falco engine versions.

I'd suggest at least updating the required_engine_version to 6 in the rules file.

**How to reproduce it**

**Expected behaviour**

**Screenshots**

**Environment**

- Falco version:

- System info:

- Cloud provider or hardware configuration:
- OS:

- Kernel:

- Installation method:

**Additional context**

### PR DESCRIPTION
**Pull request by fntlnz**
Co-Authored-By: Leonardo Di Donato <leodidonato@gmail.com>
Signed-off-by: Lorenzo Fontana <lo@linux.com>

**What type of PR is this?**
/kind feature

> If contributing rules or changes to rules, please make sure to also uncomment one of the following line:

/kind rule-update

**Any specific area of the project related to this PR?**

/area rules

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #1272

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
update: the required_engine_version is now on by default 
rule(Container Drift Detected (open+create)): specify that rule is only enabled with engine 6
rule(Create Disallowed Pod): required_engine_version 5
rule(Create Privileged Pod): required_engine_version 5
rule(Create Sensitive Mount Pod): required_engine_version 5
rule(Create HostNetwork Pod): required_engine_version 5
rule(Pod Created in Kube Namespace): required_engine_version 5
rule(ClusterRole With Wildcard Created): required_engine_version 5
rule(ClusterRole With Write Privileges Created): required_engine_version 5
rule(ClusterRole With Pod Exec Created): required_engine_version 5

```

### CODE REVIEW

**Comment by fntlnz** [comment]
Now that we are scoping the engine version we probably need to do a review and add this to older rules that were subject to an engine version increase too.

**Comment by fntlnz** [comment]
While working on this @leodido and I also took a stub and went back in time to update the minimum engine version in all the rules we have.

This is Falco 0.20.0 (engine version 5) if you try to use a rule of the current master (engine version 6)
```
root@9e5db6db2068:/# falco -r /rules/falco_rules.yaml  -r /rules/k8s_audit_rules.yaml 
2020-06-23T10:11:15+0000: Falco initialized with configuration file /etc/falco/falco.yaml
2020-06-23T10:11:15+0000: Loading rules from file /rules/falco_rules.yaml:
2020-06-23T10:11:15+0000: Runtime error: Rules require engine version 6, but engine version is 5
---
- rule: Container Drift Detected (open+create)
  desc: New executable created in a container due to open+create
  required_engine_version: 6
  condition: >
    evt.type in (open,openat,creat) and
    evt.is_open_exec=true and
    container and
    not runc_writing_exec_fifo and
    not runc_writing_var_lib_docker and
    evt.rawres>=0
  output: Drift detected (open+create), new executable created in a container (user=%user.name command=%proc.cmdline filename=%evt.arg.filename name=%evt.arg.name mode=%evt.arg.mode event=%evt.type)
  priority: ERROR
# Application rules have moved to application_rules.yaml. Please look
# there if you want to enable them by adding to
# falco_rules.local.yaml.
---. Exiting.
root@9e5db6db2068:/# ^C
root@9e5db6db2068:/# falco --version                                                  
Falco version: 0.20.0+d77080a

```


This is Falco 0.15.0 (engine version 3) if you try to load a rule with engine version 5.
```
root@c19b49f0bec2:/# falco -r /rules/falco_rules.yaml -r /rules/k8s_audit_rules.yaml 
2020-06-23T10:15:14+0000: Falco initialized with configuration file /etc/falco/falco.yaml
2020-06-23T10:15:14+0000: Loading rules from file /rules/falco_rules.yaml:
2020-06-23T10:15:15+0000: Loading rules from file /rules/k8s_audit_rules.yaml:
2020-06-23T10:15:15+0000: Runtime error: Error loading rules: [string "-- Copyright (C) 2016-2018 Draios Inc dba Sys..."]:222: Rules require engine version 5, but engine version is 3. Exiting.
```

**Comment by fntlnz** [comment]
/hold 

There is something going on with the integration tests.
Looks like `required_engine_version` changes the tests behavior in unexpected ways. @leodido and I tested locally and looks like it complains about loading the driver (which should not be necessary at all here)

**Comment by Kaizhe** [comment]
Does it mean we have a global `#- required_engine_version: 2` and required_engine_version per rule?

**Comment by fntlnz** [comment]
Yes @Kaizhe - every rule inherits the global requirements while specific rules can specify an higher requirement if they contain a field that was added on a specific engine version.

**Comment by leogr** [comment]
I might have found the problem with the integration test. I'm working on it.
/assign

**Comment by leogr** [comment]
cc @leodido @fntlnz 
This PR still needs some rework, moreover, I can confirm https://github.com/falcosecurity/falco/issues/1315 affects this PR, so I propose to reschedule for the 0.25.0 milestone

**Comment by leogr** [comment]
Rebased on the current master. Working on it.
/assign

**Comment by leogr** [comment]
> Yes @Kaizhe - every rule inherits the global requirements while specific rules can specify an higher requirement if they contain a field that was added on a specific engine version.

Unfortunately, that is not true. I have discovered that [rule loader](https://github.com/falcosecurity/falco/blob/36de713033520ce11c0e8e6cdcfc391ecd47fbc0/userspace/engine/lua/rule_loader.lua) supports `required_engine_version` at document level only.

It was not immediately apparent because when the `required_engine_version` property is found in any object, the loader just overrides the engine version of the context (i.e., the YAML document) with no errors nor warnings. Moreover, any object that contains `required_engine_version` is not further inspected; thus, if a `rule` contains `required_engine_version`, it will just not loaded (same behavior in case of `list` and `macro` as well).

I've formatted the Lua code to make the [if/elseif chain](https://github.com/falcosecurity/falco/blob/36de713033520ce11c0e8e6cdcfc391ecd47fbc0/userspace/engine/lua/rule_loader.lua#L314) (that implements the above behavior) clearer. 

For these reasons, I've converted the `required_engine_version` of this PR into comments by https://github.com/falcosecurity/falco/pull/1273/commits/490a67c23a7ea0c0a26c649f6080c08def6b10d5

Although this PR does not introduce significant changes eventually, IMHO it worths merging this anyway since that comments and code formatting will help folks to understand how to use rules properly).

**Comment by leogr** [comment]
Rebased again to solve conflicts with the master branch.

I believe this is ready to be reviewed now.

/hold cancel

**Comment by leodido** [comment]
Hey /poiana, hello my friend 😄

**Comment by leogr** [comment]
Hey @fntlnz 

I'd propose to close this PR since it cannot fix the original problem and it just introduces some comment and indentation (and because of that, it's conflicting every time a rule file is changed).

WDYT?
cc @leodido

**Comment by leogr** [comment]
> Hey @fntlnz
> 
> I'd propose to close this PR since it cannot fix the original problem and it just introduces some comment and indentation (and because of that, it's conflicting every time a rule file is changed).
> 
> WDYT?
> cc @leodido

Just proposing again to close this, since https://github.com/falcosecurity/falco/pull/1381 got merged.
/hold

**Pull request closed without merging**
