### PR TITLE
rules: add OpenSSH private key to macro private_key_or_password

### PR DESCRIPTION
**Pull request by oscr**
**What type of PR is this?**

/kind feature
/kind rule-update

**Any specific area of the project related to this PR?**

/area rules

**What this PR does / why we need it**:

I noticed the rules macro `private_key_or_password` didn't check for OpenSSH private keys so I added it.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
rules(macro: private_key_or_password): now also check for OpenSSH private keys 
```

### CODE REVIEW

**Comment by darryk10** [comment]
LGTM

**Review by darryk10 — APPROVED** [review]
Thanks for contributing. It looks good to me 👍🏻

**Review by jasondellaluce — APPROVED** [review]
/approve

**Review by leogr — APPROVED** [review]

**Review by Kaizhe — APPROVED** [review]

**Comment by leogr** [comment]
Closing and reopening to trigger the CI
/close

**Pull request merged**
