### PR TITLE
[BREAKING CHANGE]: cleanup(falco.yaml)!: remove some deprecated configs

### PR DESCRIPTION
**Pull request by Andreagit97**
**What type of PR is this?**

/kind cleanup

**Any specific area of the project related to this PR?**

/area engine

**What this PR does / why we need it**:

As previously described in this issue https://github.com/falcosecurity/falco/issues/2840, this PR removes the deprecated features

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
cleanup(falco.yaml)!: remove some deprecated configs
```

### CODE REVIEW

**Review by FedeDP — APPROVED** [review]
Love this cleanup!
/approve

**Comment by FedeDP** [comment]
The win32 failure:
```
D:\a\falco\falco\userspace\falco\configuration.cpp(138,19): error C2065: 'PATH_MAX': undeclared identifier [D:\a\falco\falco\build\userspace\falco\falco_application.vcxproj]
D:\a\falco\falco\userspace\falco\configuration.cpp(144,24): error C2065: 'PATH_MAX': undeclared identifier [D:\a\falco\falco\build\userspace\falco\falco_application.vcxproj]
```

**Review by FedeDP — APPROVED** [review]
/approve

**Comment by Andreagit97** [comment]
we need to change also the corresponding tests in `falco-testing` :face_exhaling:

**Comment by Andreagit97** [comment]
This should be ready now!

**Review by incertum — APPROVED** [review]
/approve

**Pull request merged**
