### PR TITLE
replace ".." concatenation with table.concat

### PR DESCRIPTION
**Pull request by VadimZy**
When testing exceptions with a large number of auto-generated values we faced an issue with Falco validator memory starvation. That was due to the code performing string concatenation with ".." operator.  Due to the string immutability, each of such operations creates a new copy of the result string keeping the old one in the memory till the GC is run, and the GS won't run at least until the function returns. The above generates a snowball of allocated and unused memory. Rough estimates could give at least an N^2 growth rate. In our tests a ~1MB rules YAML required between 1-2 GB of memory to be parsed.

**What type of PR is this?**

>/kind bug

> /kind design

**Any specific area of the project related to this PR?**

> /area engine

**What this PR does / why we need it**:

fix memory mismanagement when converting exceptions

**Which issue(s) this PR fixes**:

fixes memory mismanagement when converting exception

Fixes #

fixes memory mismanagement when converting exception

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
NONE

original code formating is not consistent 3/4 spaces per indent.
indentation changed to 4 spaces. 
please use ignore whitespace when reviewing. 

```release-note
NONE
```

### CODE REVIEW

**Review by mstemm — APPROVED** [review]
@VadimZy is going to add some comments to the PR that provide more context on why these changes result in more efficient management of exceptions.

But the changes look good to me and thanks for finding the problem and providing a fix!

**Comment by jasondellaluce** [comment]
@VadimZy Thanks for the contribution, this is definitely an issue and the contribution looks promising. Can you [sign-off](https://github.com/falcosecurity/.github/blob/master/CONTRIBUTING.md#developer-certificate-of-origin) your commits? That's a requirement as for our governance.

**Review by leodido — COMMENTED** [review]
LGTM

**Comment by VadimZy** [comment]
just pushed the message for both commits but one still mentioned as not signed off.

**Comment by VadimZy** [comment]
I see it either/or have dco or tests passed

**Review by mstemm — APPROVED** [review]

**Review by leogr — APPROVED** [review]
/approve

**Pull request merged**
