### PR TITLE
update(userspace/engine): support jsonpointer escaping in rule parser

### LINKED ISSUE #1691: jsonpointer expression does not support slash escaping
**Description**

The documentation states that jevt.value uses json pointer expressions. This works for normal cases, but when tilde escaping is required, it throws a syntax error

**Reproduction**

Add the following macro to a rule file:

```
- macro: authzDecision
  condition: (jevt.value["/annotations/authorization.k8s.io~1decision"] in (["allow"]))
```

run the validation command:

```
falco -V your_rule_file.yaml
```

**Expected behaviour**

no validation errors, as ~1 is the official json pointer escape sign for /

**Screenshots**

N/A

**Environment**

- Falco version:
Falco version: 0.28.2
Driver version: 13ec67ebd23417273275296813066e07cb85bc91

- System info:
{
  "machine": "x86_64",
  "nodename": "<removed>",
  "release": "3.10.0-1062.1.2.el7.x86_64",
  "sysname": "Linux",
  "version": "#1 SMP Mon Sep 30 14:19:46 UTC 2019"
}

- Cloud provider or hardware configuration:
- OS:
CentOS Linux 7 (Core)
- Kernel:
3.10.0-1062.1.2.el7.x86_64 #1 SMP Mon Sep 30 14:19:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Installation method:
RPM

**Additional context**

### PR DESCRIPTION
**Pull request by jasondellaluce**
Signed-off-by: Jason Dellaluce <jasondellaluce@gmail.com>

**What type of PR is this?**

/kind bug

**Any specific area of the project related to this PR?**

/area engine

**What this PR does / why we need it**:
This PR updates the Falco rule parser to properly support jsonpointer escaping in field arguments. The escaping requires the `~` character, which was not supported in our grammar. This has been fixed by adding `~` as a supported characters for field arguments in the `Index` grammar production. Since the `PathString` terminal is not just path-related anymore, it has been renamed to `ArgString` for a better conceptual generality.

**Which issue(s) this PR fixes**:
Fixes #1691 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
update(userspace/engine): support jsonpointer escaping in rule parser
```

### CODE REVIEW

**Comment by mstemm** [comment]
The code changes look good, can you add a test where a rules file uses jevt.value[<some json pointer with escaping>], as an example?

**Comment by jasondellaluce** [comment]
A test has been added to the k8s audit test suite to check that the json pointer works correctly.

**Review by leogr — APPROVED** [review]
LGTM, great fix. Thank you!

/approve

**Review by mstemm — APPROVED** [review]

**Pull request merged**
