### PR TITLE
sync: release 0.39.1

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind release

**Any specific area of the project related to this PR?**

/area engine

**What this PR does / why we need it**:

Cherry picks 
* https://github.com/falcosecurity/falco/pull/3363
* https://github.com/falcosecurity/falco/pull/3368
* https://github.com/falcosecurity/falco/pull/3372
from master

Plus, it updates the changelog in a standalone commit ready to be cherry picked on master.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by FedeDP** [comment]
/hold
Will use this very same PR to also update the changelog.

**Comment by FedeDP** [comment]
Bumped the changelog (in its own commit that will be cherry picked into master)
/unhold

**Review by leogr — DISMISSED** [review]

**Comment by FedeDP** [comment]
/hold
we want to merge https://github.com/falcosecurity/falco/pull/3372 too.

**Review by leogr — APPROVED** [review]

**Review by LucaGuerra — APPROVED** [review]

**Pull request merged**
