### PR TITLE
build: bump driver version and updated plugins to latest versions adding platform name to artifact url

### PR DESCRIPTION
**Pull request by FedeDP**
Signed-off-by: Federico Di Pierro <nierro92@gmail.com>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

/kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

> If contributing rules or changes to rules, please make sure to also uncomment one of the following line:

> /kind rule-update

> /kind rule-create

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area build

> /area engine

> /area rules

> /area tests

> /area proposals

**What this PR does / why we need it**:

Updates plugins to latest versions; updated libs to latest version.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
update(build): updated libs to 319368f1ad778691164d33d59945e00c5752cd27 for upcoming Falco 0.31 release.
```

### CODE REVIEW

**Comment by leogr** [comment]
Closing and reopening to trigger the CI
/close

**Comment by leogr** [comment]
Hey @FedeDP 

Could you add a line in the release note block regarding the new driver version? :pray: 
(it's likely the last driver bump in this release, so we need it in the changelog)

**Review by jasondellaluce — APPROVED** [review]
/approve

Thanks @FedeDP!

**Review by leogr — APPROVED** [review]
/approve

thank you!

**Pull request merged**
