### PR TITLE
chore(ci): enable aarch64 falco driver loader tests.

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind cleanup

**Any specific area of the project related to this PR?**

/area CI

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by FedeDP** [comment]
> E: Unable to locate package linux-headers-5.10.201
> E: Couldn't find any package by glob 'linux-headers-5.10.201'

It seems like the node is running on an outdated kernel release?

**Comment by FedeDP** [comment]
/hold
It seems we are not able to find correct headers for now: 
> E: Couldn't find any package by glob 'linux-headers-5.10.201'

**Comment by FedeDP** [comment]
Ported same workaround as in https://github.com/falcosecurity/libs/pull/1566

**Comment by FedeDP** [comment]
Ci did pass; squashed in a single commit; ready to get merged!

**Review by leogr — APPROVED** [review]

**Review by Andreagit97 — APPROVED** [review]
/approve

**Pull request merged**
