### PR TITLE
fix(ci,build): fixes for 0.35.x release branch

### PR DESCRIPTION
**Pull request by LucaGuerra**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug
/area build
/area ci

**What this PR does / why we need it**:

Changes for build issue identified on the Falco 0.35.x release branch

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by jasondellaluce — APPROVED** [review]
/approve

**Review by FedeDP — APPROVED** [review]
/approve

**Comment by FedeDP** [comment]
/milestone 0.35.0

This is the very same patch as https://github.com/falcosecurity/falco/pull/2621.
To speed up, we are opening the PR against the release branch.

**Comment by FedeDP** [comment]
>  tide — In merge pool. 

Please tide.

**Pull request merged**
