### PR TITLE
Sample integration of Eco-CI to Falco Pipelines

### PR DESCRIPTION
**Pull request by ArneTR**
This is a draft PR to illustrate an integration of an energy / carbon measurement plugin. Discussed in https://github.com/cncf-tags/green-reviews-tooling/issues/55

**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

/area CI

### CODE REVIEW

**Review by incertum — COMMENTED** [review]
This is awesome, thank you!

Question: We created a dedicated repo here: https://github.com/falcosecurity/cncf-green-review-testing perhaps we should expand that repo to be "All Things Green Review"? However, we don't yet have any CI really setup in that repo.

CC @leogr @maxgio92 @LucaGuerra awaiting guidance on how we would like to expand our infra in this regards. Thanks.

**Comment by maxgio92** [comment]
Hi @ArneTR, which parts of the CI pipeline this measurement applies to?

In any case generally I think that improving the observability around the resource consumption like other reports per CI run I think is right to have it here in this repo @incertum. WDYT?

**Comment by ArneTR** [comment]
Hey @maxgio92 

I have posted the details in the linked issue, but I guess it would have been better to also post them here :)

Here it goes:

- Examplary Workflow chosen (Scorecard): https://github.com/falcosecurity/falco/actions/workflows/scorecard.yaml
- Generated data by Eco-CI: https://metrics.green-coding.io/ci.html?repo=green-coding-solutions/falco&branch=master&workflow=87453986

Eco-CI is integrated here by encapsulating all the steps that are originally done in the *Scorecard* workflow. By design it cannot capture the boot up of the VM and / or the removal. Eco-CI only starts measuring as the first step of a Github / Gitlab workflow.

A bit more details how it works you can find here: https://github.com/green-coding-solutions/eco-ci-energy-estimation

I also would like to add that this is mainly a Draft PR to illustrate the concept and advance the discussin in the CNCF TAG ENV group. Happy to extend this PR to a  full fledged one though or even move it rather to a different repor where you see a try-out integration of Eco-CI more applicable.

**Comment by FedeDP** [comment]
Any news on this one?
/remove-lifecycle stale

**Comment by ArneTR** [comment]
Oh my, seems like I missed to make the DCO.

I rebased the branched and added it.

Also updated Eco-CI and pinned the version, as you also do it with the other GitHub extensions you use.

For questions please follow up. All description and infos I posted in the message from April are still current.

**Comment by leogr** [comment]
> I rebased the branched and added it.
Hey @ArneTR 

I guess your changes are out from the branch due to a wrong rebase (and for this reason, GitHub closed this PR). May you fix it or open a new PR pls?

**Pull request closed without merging**
