### PR TITLE
sync falco 0.34.1

### PR DESCRIPTION
**Pull request by alacuku**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

/kind release

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

> /area engine

> /area tests

> /area proposals

> /area CI

**What this PR does / why we need it**:

This PR cherrypicks the commits introduced by the following PRs:

* #2418 
* #2412 

to `release/0.34.x` branch.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by alacuku** [comment]
#2421

**Review by Andreagit97 — APPROVED** [review]
/approve

**Comment by alacuku** [comment]
/hold 
I wait for libs to be tagged and bump the version into Falco.

**Comment by alacuku** [comment]
/unhold
Libs version has been bumped.

**Review by Andreagit97 — APPROVED** [review]
/approve

**Review by jasondellaluce — APPROVED** [review]
/approve

**Pull request merged**
