### PR TITLE
fix(ci): fetch version step, download rpms/debs, minor change

### PR DESCRIPTION
**Pull request by LucaGuerra**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area CI

**What this PR does / why we need it**:

* A new job `fetch-version` was added to detect the Falco version, but not all dependent jobs were updated.
* Fixed downloading of artifacts since we were trying to use a wildcard which isn't really supported 😅
* Minor fix (security best practice) with handling the secret

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by FedeDP — DISMISSED** [review]
/approve

**Comment by FedeDP** [comment]
/milestone 0.35.0

Refs #2501

**Comment by LucaGuerra** [comment]
I think this change is right but not enough to fix the latest error though

**Comment by LucaGuerra** [comment]
Added a couple more things:
* fixed downloading of artifacts since we were trying to use a wildcard which isn't really supported 😅
* minor change with the `GPG_KEY` env variable use, instead of using it in all jobs it's only imported only in the two steps that actually use it. This is a security best practice but does not change the functionality of the jobs.

**Review by Andreagit97 — APPROVED** [review]
/approve

**Review by FedeDP — APPROVED** [review]
/approve
Thank you!

**Review by leogr — APPROVED** [review]
:+1:

**Pull request merged**
