### PR TITLE
Add GKE default pod into allowlist in Mount Launched of Privileged Container rule 

### PR DESCRIPTION
**Pull request by hi120ki**
Signed-off-by: Hi120ki <12624257+hi120ki@users.noreply.github.com>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

> /kind release

> If contributing rules or changes to rules, please make sure to also uncomment one of the following line:

/kind rule-update

> /kind rule-create

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

> /area engine

/area rules

> /area tests

> /area proposals

> /area CI

**What this PR does / why we need it**:

In GKE cluster, a system container `gce-pd-driver` that manages Persistent Disk is running.
But the rule `Mount Launched of Privileged Container` detects as false positive.

```
Process: mount -t ext4 -o defaults /dev/disk/by-id/google-pvc-<id> /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-<id>/globalmount
```

This container runs in `kube-system` namespace, and image is from `gke.gcr.io/gcp-compute-persistent-disk-csi-driver`.
I added it into allowlist(macro : `user_known_mount_in_privileged_containers `).

I'm waiting for your comments on adding it into allowlist and my proposed changes.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Add GKE default pod into allowlist in Mount Launched of Privileged Container rule 
```

### CODE REVIEW

**Comment by darryk10** [comment]
Hi @hi120ki ,
thanks for helping with FPs we really need this type of contribution :) 
The only suggestion from my side is to create a new macro related to GKE. The macros like `user_known_mount_in_privileged_containers` are usually used as macros that each user can customise based on their environment. If we find something related to a specific technology we use to create a new macro related to it. :) 
Thanks

**Comment by hi120ki** [comment]
@darryk10 I see. I revert and add new macro `macro: known_gke_mount_in_privileged_containers` as allowlist.
Cloud you check it?

**Review by darryk10 — APPROVED** [review]
Thanks @hi120ki
LGTM

**Review by jasondellaluce — APPROVED** [review]
/approve

**Review by Kaizhe — APPROVED** [review]

**Comment by leogr** [comment]
Closing and reopening to trigger the CI
/close

**Comment by leogr** [comment]
/reopen

/hold
for the CI to complete

**Pull request merged**
