### PR TITLE
rule(macro user_know_remote_file_copy_tools_in_container_conditions)

### PR DESCRIPTION
**Pull request by mobouchardcoveo**
**What type of PR is this?**

/kind rule-update

**Any specific area of the project related to this PR?**

/area rules

**What this PR does / why we need it**:

With this we will be able to create custom condition. We have a special use case with a tool called Rosco.

**Which issue(s) this PR fixes**:

None

**Special notes for your reviewer**:

None

**Does this PR introduce a user-facing change?**:

```release-note
rule(macro user_known_remote_file_copy_tools_in_container_conditions): Allow custom condition for remote file copy tools
```

### CODE REVIEW

**Review by leodido — COMMENTED** [review]
It seems a reasonable macro to add for exclusions.

Not sure though if we want its name to be `user_known_remote_file_copy_tools_in_container_conditions` or just something like `user_known_remote_file_copy_tools`.

I'd wait for @Kaizhe opinion anyway!

**Comment by Kaizhe** [comment]
@mobouchardcoveo I know there some places using `user_known_xxx_conditions`, but his one is too long, let's use `user_known_remote_file_copy_activities`

**Comment by Kaizhe** [comment]
And thank you for making the change! Really apprecaite!

**Comment by mobouchardcoveo** [comment]
Thanks for the comment and yes I think it's better with your name. I just did the change.

**Review by Kaizhe — APPROVED** [review]

**Review by leodido — APPROVED** [review]

**Pull request merged**
