### PR TITLE
Add Logz.io to Falco's adopters list ADOPTERS.md

### PR DESCRIPTION
**Pull request by ghost**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

> If contributing rules or changes to rules, please make sure to also uncomment one of the following line:

> /kind rule-update

> /kind rule-create

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

> /area engine

> /area rules

> /area tests

> /area proposals

**What this PR does / why we need it**:
updating ADOPTERS.md with a new adopter details

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```
/assign @fntlnz

Signed-off-by: Dotan Horovits <dotan.horovits@gmail.com>

### CODE REVIEW

**Comment by fntlnz** [comment]
@horovits1 this LGTM but please look into[ signing your commits ](https://github.com/falcosecurity/falco/blob/master/CONTRIBUTING.md#developer-certificate-of-origin)

**Comment by leogr** [comment]
Hey everyone

I have noticed that @horovits1 is now a deleted user ( @ghost ) which can neither reply nor sign-off

cc @horovits are you the same user? If so could you please make this PR again, please? 

Thanks in advance

**Comment by horovits** [comment]
hey @leogr yes I transferred accounts, apologies for the mess.
the pull request source is now horovits:update-adopters-logzio
and the signoff stated in the pull request remains unchanged:
Signed-off-by: Dotan Horovits dotan.horovits@gmail.com
can we go ahead with approving the merge? adding Logz to adopters list?
redoing the same PR may mess things up, as it appears on the @horovits account.
Thanks,
Dotan

> Hey everyone
> 
> I have noticed that @horovits1 is now a deleted user ( @ghost ) which can neither reply nor sign-off
> 
> cc @horovits are you the same user? If so could you please make this PR again, please?
> 
> Thanks in advance

**Comment by leogr** [comment]
> hey @leogr yes I transferred accounts, apologies for the mess.
> the pull request source is now horovits:update-adopters-logzio
> and the signoff stated in the pull request remains unchanged:
> Signed-off-by: Dotan Horovits [dotan.horovits@gmail.com](mailto:dotan.horovits@gmail.com)
> can we go ahead with approving the merge? adding Logz to adopters list?
> redoing the same PR may mess things up, as it appears on the @horovits account.
> Thanks,
> Dotan

Hi @horovits 

we need the sign-off on the commit otherwise we cannot merge it. 

Could you `git commit --amend --signoff` and then force push to [horovits:update-adopters-logzio](https://github.com/horovits/falco/tree/update-adopters-logzio)?
That would be ok too to merge this PR.

**Comment by horovits** [comment]
hi @leogr I did the PR again per request, see #1266, assigned to you.
https://github.com/falcosecurity/falco/pull/1266
Thanks


> Hey everyone
> 
> I have noticed that @horovits1 is now a deleted user ( @ghost ) which can neither reply nor sign-off
> 
> cc @horovits are you the same user? If so could you please make this PR again, please?
> 
> Thanks in advance

**Comment by leogr** [comment]
Thank you!

**Pull request closed without merging**
