### PR TITLE
new(ci): sign releases with cosign

### PR DESCRIPTION
**Pull request by LucaGuerra**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind feature
/area CI

**What this PR does / why we need it**:

Add signatures with cosign upon releases!

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
new(release): released container images are now signed with cosign
```

### CODE REVIEW

**Review by FedeDP — APPROVED** [review]
Love this!
/approve

**Comment by LucaGuerra** [comment]
/hold

until the master CI is stable again :)

**Comment by FedeDP** [comment]
"Stable" is such an old-fashioned word though. 
:rofl:

**Comment by LucaGuerra** [comment]
I did edit the message :rofl:

**Review by Andreagit97 — APPROVED** [review]
/approve

**Pull request merged**
