### PR TITLE
fix: use base name in docker-entrypoint.sh

### PR DESCRIPTION
**Pull request by aarroyoc**
**What type of PR is this?**

/kind bug

**Any specific area of the project related to this PR?**

/area build

**What this PR does / why we need it**:

It uses the base path in the docker-entrypoint.sh. This is needed because when you build Falco from source along with the driver, it tries to create a link with destination /usr/src//host/usr/src/XXX which is wrong and should be /usr/src/XXX 

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
fix(docker): use base name in docker-entrypoint.sh
```

### CODE REVIEW

**Comment by aarroyoc** [comment]
I thought this was included in Falco 0.20, but no, and I still get the same error that made me create this PR:

```
cxb0290@mac-510116 baikal2 % k logs falco-7c9wn falco -n baikal-system
* Setting up /usr/src links from host
ln: failed to create symbolic link '/usr/src//host/usr/src/linux-azure-headers-4.15.0-1066': No such file or directory
ln: failed to create symbolic link '/usr/src//host/usr/src/linux-azure-headers-4.15.0-1071': No such file or directory
ln: failed to create symbolic link '/usr/src//host/usr/src/linux-headers-4.15.0-1066-azure': No such file or directory
ln: failed to create symbolic link '/usr/src//host/usr/src/linux-headers-4.15.0-1071-azure': No such file or directory
* Unloading falco-probe, if present
* Running dkms install for falco
Error! echo
Your kernel headers for kernel 4.15.0-1066-azure cannot be found at
/lib/modules/4.15.0-1066-azure/build or /lib/modules/4.15.0-1066-azure/source.
* Running dkms build failed, couldn't find /var/lib/dkms/falco/0.20.0+d77080a/build/make.log
* Trying to load a system falco-probe, if present
* Trying to find precompiled falco-probe for 4.15.0-1066-azure
Found kernel config at /host/boot/config-4.15.0-1066-azure
* Trying to download precompiled module from https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/falco-probe-0.20.0%2Bd77080a-x86_64-4.15.0-1066-azure-c07e1b0c69c599054b906a7da9e219bb.ko
curl: (22) The requested URL returned error: 404 Not Found
Download failed, consider compiling your own falco-probe and loading it or getting in touch with the Falco community
2020-02-24T17:43:31+0000: Falco initialized with configuration file /etc/falco/falco.yaml
2020-02-24T17:43:31+0000: Loading rules from file /etc/falco/falco_rules.yaml:
2020-02-24T17:43:31+0000: Unable to load the driver. Exiting.
```
(Check the first lines)

**Comment by fntlnz** [comment]
Thanks @aarroyoc ! This looks very good :)

**Comment by fntlnz** [comment]
reopening to let poiana take this

**Pull request merged**
