### PR TITLE
fix(cmake/modules): update driver to support kernels 5.6.y

### LINKED ISSUE #1173: Falco drivers does not support Linux kernel 5.6.y
**Describe the bug**

The Falco driver does not build on Linux kernel 5.6.y due to the fact it no longer includes the old 32-bit `timeval` structures.

**How to reproduce it**

Try to build it on a kernel 5.6.y

**Expected behaviour**

To build and to run ok.

### PR DESCRIPTION
**Pull request by leodido**
Co-authored-by: Lorenzo Fontana <lo@linux.com>
Signed-off-by: Leonardo Di Donato <leodidonato@gmail.com>

**What type of PR is this?**

/kind bug

**Any specific area of the project related to this PR?**
/area build

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #1173 
Refs https://github.com/draios/sysdig/pull/1621

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
fix: support Falco driver on Linux kernels 5.6.y
```

### CODE REVIEW

**Comment by kris-nova** [comment]
So I think this broke our driver build.

Has anyone been able to compile the driver with this new version?

**Comment by fntlnz** [comment]
@kris-nova - Can you post more details? You mean the process of building a driver from source or our automated driver building process?

I tested with against the longterm kernels and @nathan-b - the actual patch author also tested in their environment: https://github.com/draios/sysdig/pull/1621#issuecomment-621869556

**Comment by fntlnz** [comment]
Also thanks for testing this out @kris-nova we definitely need to understand what happened to your build before we release because releasing a broken driver might be a huge deal for the project

**Comment by nathan-b** [comment]
Our automated tests have been running with this change (both eBPF and kmod) for nearly a week now. I'm not saying that I didn't break anything, but I don't think I broke _everything_ ;)

**Comment by fntlnz** [comment]
So this is ready to ship into the next Falco release! Thanks for the fix @nathan-b !

**Pull request merged**
