### PR TITLE
[WIP] Make output rate limiting optional

### PR DESCRIPTION
**Pull request by irozzo-1A**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

/kind feature

> If contributing rules or changes to rules, please make sure to also uncomment one of the following line:

> /kind rule-update

> /kind rule-create

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

/area engine

> /area rules

> /area tests

> /area proposals

**What this PR does / why we need it**:
This PR partially address #1333, in particular it allows to disable output throttling.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
I profited to refactor a bit the token bucket to:

- Use monotonic clock instead of wall time.
- Having a raw interface where timestamps are provided explicitly and a facade that generates the timestamps automatically, mixing the two does not seem to be a good idea, especially if different types of clocks can be used.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by irozzo-1A** [comment]
Not finished, but if someone has the time to make a first pass would be great to have early feedback. ;-)

**Review by leodido — COMMENTED** [review]
Hello Iacopo, thanks for submitting this.

I like the idea of separating the responsibility about which clock to use.
Even if, there's no real use case for it in this codebase. Since we have to use the timestamp coming from sinsp for performance reasons.

ANyways, looking forward to this PR completion!

A nitpick: could you please revert the lines changes that only contain formatting?
We have to work on code conventions, I agree. But that's a task for separate PRs/working groups.
Having here only those changes coherent with this PR will help the maintainers to review it.

Thanks again!

**Comment by irozzo-1A** [comment]
@leodido Thx for your feedback.

> I like the idea of separating the responsibility about which clock to use.
> Even if, there's no real use case for it in this codebase. Since we have to use the timestamp coming from sinsp for performance reasons.

Interesting, let me expand a bit on my reasoning. I saw `token_bucket` is used in two places with different patterns:

https://github.com/falcosecurity/falco/blob/6beb9838d6309dc9d754cae481eaaf38f0a97878/userspace/falco/event_drops.cpp#L90
https://github.com/falcosecurity/falco/blob/6beb9838d6309dc9d754cae481eaaf38f0a97878/userspace/falco/falco_outputs.cpp#L147

In the first use case, the timestamp used in `claim` is provided from outside, and the second is "standard" usage. I thought that from a pure API design standpoint it's better to separate the two for clarity and to reduce the possibility of misusage. Concretely speaking what I did does not bring a lot of benefits :-) at the moment.

Secondly, I noticed that [sinsp_utils::get_current_time_ns](https://github.com/draios/sysdig/blob/8855f4505dc42ad9e328ef6df94c61984cf657e7/userspace/libsinsp/utils.cpp#L920-L926) makes use of [gettimeofday](https://man7.org/linux/man-pages/man2/gettimeofday.2.html), but as we are interested in computing elapsed time would be more convenient to use [clock_gettime](https://man7.org/linux/man-pages/man2/clock_gettime.2.html) with `CLOCK_MONOTONIC ` as it guarantees time is linearly increasing (note that at the moment I used `std::chrono::steady_clock` for convenience). AFAIU your claim is that `gettimeofday` in general is faster, isn't it?
I'll try to benchmark it (just out of curiosity, not for mistrust :smile:).

If you estimate that the benefit is not significant of course I'm open to removing this from the PR as it is not strictly needed/related with the issue :wink:.

> A nitpick: could you please revert the lines changes that only contain formatting?
> We have to work on code conventions, I agree. But that's a task for separate PRs/working groups.
> Having here only those changes coherent with this PR will help the maintainers to review it.

Definitely, I agree with you it was not intended. I'll clean it up.

**Comment by leodido** [comment]
> Interesting, let me expand a bit on my reasoning. I saw `token_bucket` is used in two places with different patterns:
> 
> https://github.com/falcosecurity/falco/blob/6beb9838d6309dc9d754cae481eaaf38f0a97878/userspace/falco/event_drops.cpp#L90
> 
> 
> https://github.com/falcosecurity/falco/blob/6beb9838d6309dc9d754cae481eaaf38f0a97878/userspace/falco/falco_outputs.cpp#L147
> 
> In the first use case, the timestamp used in `claim` is provided from outside, and the second is "standard" usage. I thought that from a pure API design standpoint it's better to separate the two for clarity and to reduce the possibility of misusage. Concretely speaking what I did does not bring a lot of benefits :-) at the moment.

Yup, exactly what I meant. :)
Anyways, in case the problem to solve was "reduce the possibility of misusage", there was also a simpler way to do it. 
However, as said, I like it from an API design standpoint.

> Secondly, I noticed that [sinsp_utils::get_current_time_ns](https://github.com/draios/sysdig/blob/8855f4505dc42ad9e328ef6df94c61984cf657e7/userspace/libsinsp/utils.cpp#L920-L926) makes use of [gettimeofday](https://man7.org/linux/man-pages/man2/gettimeofday.2.html), but as we are interested in computing elapsed time would be more convenient to use [clock_gettime](https://man7.org/linux/man-pages/man2/clock_gettime.2.html) with `CLOCK_MONOTONIC ` as it guarantees time is linearly increasing (note that at the moment I used `std::chrono::steady_clock` for convenience). AFAIU your claim is that `gettimeofday` in general is faster, isn't it?
> I'll try to benchmark it (just out of curiosity, not for mistrust 😄).

To clarify my claim was that our optimization time is better spent somewhere else.

Lemme try to explain.
Last summer, we've benchmarked various timers a bit.
As far as I remember, whether `gettimeofday` is faster/slower than `clock_gettime` largely depends on whether the CPU models you run on have a synchronized TSC.
In fact, in this case, modern Linux kernels use a userspace TSC-based `gettimeofday` (the vdso pulls in an implementation that applies an offset to `rdtsc`'s value, thus computing the time of day without entering the kernel).

Also, `steady_clock` already uses `CLOCK_MONOTONIC` ([ref](https://github.com/gcc-mirror/gcc/blob/3defceaa1a2987fa90296abfbcc85d7e9ad59684/libstdc%2B%2B-v3/src/c%2B%2B11/chrono.cc#L80-L95)) (even if not always).

Finally, while `m_notifications_tb::claim` is called inside every `handle_event`, `m_bucket::claim` is called inside `process_event` when there have been drops.

So, is probably better first quantify those two frequencies and understand which time resolution are we exposed too.

Because we could also use `CLOCK_MONOTIC_COARSE` in case we don't mind losing resolution.

I've not rechecked things that I remember from last summer and that I wrote here (sadly I don't find numbers in my notes), so maybe I remember them completely wrong. In that case, be kind to me :)



> Definitely, I agree with you it was not intended. I'll clean it up.

Yup, please remove the only-formatting changes, if you don't mind.

**Comment by irozzo-1A** [comment]
Thx for the insights @leodido! I'm a bit busy at the moment, but I'll finalize this ;-)

> Also, `steady_clock` already uses `CLOCK_MONOTONIC` ([ref](https://github.com/gcc-mirror/gcc/blob/3defceaa1a2987fa90296abfbcc85d7e9ad59684/libstdc%2B%2B-v3/src/c%2B%2B11/chrono.cc#L80-L95)) (even if not always).

That's what I expected, but I did not verify ;-)

**Comment by irozzo-1A** [comment]
@leodido I removed the formatting-related changes and put the token bucket refactoring in a dedicated commit so that I can easily get rid of it if you don't need/want it.
I won't have much time to work on this in the near future. If you need some changes and you cannot wait for me feel free to close this and take ownership (you can reuse part of the code I did of course).

**Comment by japui** [comment]
WIP] Tornar a limitação da taxa de saída opcional

**Comment by jasondellaluce** [comment]
Might be superseded by https://github.com/falcosecurity/falco/pull/2080, which removes the output rate limiter entirely.

**Comment by irozzo-1A** [comment]
> Might be superseded by #2080, which removes the output rate limiter entirely.

Ok, l close it. Thanks for letting me know @jasondellaluce 😉

**Pull request closed without merging**
