### PR TITLE
docs(RELEASE.md): link the ecr images in releases

### PR DESCRIPTION
**Pull request by fntlnz**
Signed-off-by: Lorenzo Fontana <lo@linux.com>

**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Did this change to the release docs so that we don't forget to link the new ECR images in releases.

See https://github.com/falcosecurity/falco/pull/1512

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by fntlnz** [comment]
/milestone 0.28.0
/hold
Hold until release 0.27.0 is done

**Review by leogr — APPROVED** [review]

**Review by leodido — APPROVED** [review]

**Comment by fntlnz** [comment]
Reopening to let CI do it's thing again.

**Pull request merged**
