### PR TITLE
update(userspace/engine): support alternative plugin version requirements in checks

### LINKED ISSUE #2150: improve rule engine plugin dependencies
**Motivation**

Since rule engine version 10, Falco allows specifying in each ruleset a list of required plugin and their version. Example (https://github.com/falcosecurity/plugins/blob/fd296e843f7516939fe6201bf2f4646eb0485055/plugins/k8saudit/rules/k8s_audit_rules.yaml#L20):
```yaml
- required_plugin_versions:
  - name: k8saudit
    version: 0.1.0
  - name: json
    version: 0.3.0
```

This is good for automatically tracking down and verifying that all dependencies are satisfied. However, this is not sufficient due to https://falco.org/docs/plugins/#plugin-event-sources-and-interoperability:
> Events returned by plugins with event sourcing capability have an event source that describes the event's information. This is distinct from the plugin name to allow for multiple plugin implementations to generate the same kind of events.

We have few problems:
- Each ruleset can only specify a **conjunction** of required plugin names and versions, and does not support alternatives (e.g. `k8saudit` or `eks-k8saudit`, `gke-k8saudit`, etc)
- In the plugin system we don't have an explicit naming for the "set of supported fields of the plugin", so we can only rely either on the plugin name or on its event source (if available).

**Feature**

Make the rule engine more expressive and support either:
- Specifying more than one plugin name/version in disjunction, so that users can configure Falco with plugin alternatives
- Specifying event sources to depend on (those are not versioned though)
- Both

**Alternatives**

Not yet, I'm wide open for discussion.

### PR DESCRIPTION
**Pull request by jasondellaluce**
**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

/area engine

/area tests

**What this PR does / why we need it**:

This PR updates the rule engine to support multiple alternatives plugin version requirements definitions in rulesets. The problem was first mentioned in https://github.com/falcosecurity/plugins/pull/134#discussion_r935806326, and documented in the #2150 issue.

Given that a new feature is added, the rule engine version has been bumped (to v15). Moreover, unit tests have been introduced to make sure that the plugin version checks work as expected.

**Which issue(s) this PR fixes**:

Fixes #2150

**Special notes for your reviewer**:

In this proposal, rulesets will be able to support the following syntax:
```yaml
- required_plugin_versions:
  - name: k8saudit
    version: 0.1.0
    alternatives:
      - name: k8saudit-other
        version: 0.4.0
```

Here, `alternatives` represents a list of alternative plugin name-version pairs to be checked as alternatives to the primary one. Maintaining a primary plugin requirement definition, and making `alternatives` optional, allow backward compatibile definitions such as:
```yaml
- required_plugin_versions:
  - name: k8saudit
    version: 0.1.0
```

Given so, `required_plugin_versions` now implicitly defines a CNF ([Conjunctive Normal Form](https://en.wikipedia.org/wiki/Conjunctive_normal_form). Rulesets are correctly loaded if **all** the `required_plugin_versions` definitions are satisfied. Each entry is satisfied if **at least one** of its alternatives is satisfied.

**Does this PR introduce a user-facing change?**:

```release-note
update(userspace/engine): support alternative plugin version requirements in checks
```

### CODE REVIEW

**Review by leogr — APPROVED** [review]
Thank you!

/milestone 0.33.0

**Comment by FedeDP** [comment]
I understood it correctly that we are expected to ship proper `alternatives` in default config when we support multiple plugins offering similar functionalities?

**Comment by jasondellaluce** [comment]
> I understood it correctly that we are expected to ship proper alternatives in default config when we support multiple plugins offering similar functionalities?

By `default config` do you mean `default rulesets`? If so, yes, in our default rulesets we'll provide all the officially-supported known plugin alternatives for the rulesets we maintain. A first-class example are `k8saudit` and `k8saudit-eks` that's in the working (https://github.com/falcosecurity/plugins/pull/134).

**Comment by FedeDP** [comment]
Uh yes! thank you! Makes sense!

**Review by FedeDP — APPROVED** [review]
/approve

**Pull request merged**
