### PR TITLE
fix(ci): sign arm64 rpm packages.

### LINKED ISSUE #2064: CircleCI: Add SHA256 signature to aarch64 rpm packages
**Describe the bug**

New ARM64 packages don't seem to be processed by the rpm-sign CircleCI job and therefore they are not signed.

**How to reproduce it**

$ rpm -qi -p ./falco-0.32.0-30*rpm | grep -e Name -e Version -e Architecture -e Signature
Name        : falco
Version     : 0.32.0_30+85f91a3
Architecture: aarch64
Signature   : (none)

Name        : falco
Version     : 0.32.0_30+85f91a3
Architecture: x86_64
Signature   : RSA/SHA256, Mon 13 Jun 2022 09:22:35 AM UTC, Key ID 9f76b25b3672ba8f

**Expected behaviour**

Both x86_64 and aarch64  RPM packages should be signed to make possible its verification at installation time.

**Screenshots**

See above

**Environment**

I've tested it on RHEL9 but the same result should be obtained on previous versions.

- Falco version:
0.32.0_30+85f91a3

- System info:

- Cloud provider or hardware configuration: n/a
- OS: n/a
- Kernel: n/a
- Installation method: RPM

**Additional context**

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

> If contributing rules or changes to rules, please make sure to also uncomment one of the following line:

> /kind rule-update

> /kind rule-create

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area build

> /area engine

> /area rules

> /area tests

> /area proposals

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #2064

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by vjjmiras** [comment]
Despite the change directory statement, the execution of the sign script, and the verification of the signature, wouldn't it make more sense to add the rest to `Prepare` like:

- Create a `~/sign` script instead of `./sign`, and grant it permissions
- Import the `GPG_KEY` only once (I believe the GPG ring will be the same in both `run:` sections and the second time it'll complain it was already imported)

And on the signing `run:` sections:
- Execution would be` ~/sign *.rpm`

This way there'd be less duplicity of code but still 2 independent stages.

**Comment by vjjmiras** [comment]
LGTM

**Review by leogr — APPROVED** [review]
/milestone 0.32.1

/approve

**Review by jasondellaluce — APPROVED** [review]
/approve

**Comment by vjjmiras** [comment]
We forgot to change the location of the ~/sign file when creating it.
I opened a new [PR](https://github.com/falcosecurity/falco/pull/2072) to fix it (and I hope it also cleans up the code a bit).

**Pull request merged**
