### PR TITLE
Check keepalive first, and throttle try_pop

### LINKED ISSUE #1126: High CPU usage when grpc is enable
**Describe the bug**

When grpc is enabled in falco 0.21.0 there is a huge increase in cpu usage on some pods on kops cluster, k8s 1.16, debian nodes.

grpc disabled
NAME                   CPU(cores)   MEMORY(bytes)
falco-htqvd            7m           16Mi
falco-hzxvx            7m           16Mi
falco-lw9f7            7m           16Mi
falco-nmvqq            7m           16Mi
falco-phz9d            8m           16Mi
falco-scbcr            9m           16Mi
falco-snwqj            8m           16Mi
falco-svswf            7m           16Mi
falco-tgsq8            8m           16Mi

grpc enabled
NAME                   CPU(cores)   MEMORY(bytes)
falco-48zhv            8m           17Mi
falco-8prq5            7m           17Mi
falco-9wtl4            8m           17Mi
falco-ckfl4            1930m        18Mi
falco-fwlzc            1833m        17Mi
falco-gpx6g            7m           17Mi
falco-hrfv8            1825m        18Mi
falco-tv4f2            1004m        17Mi
falco-wx8dx            1003m        17Mi
**How to reproduce it**

Install falco using the stable helm chart with grpc enabled.
`grpc:
   enabled: true
   bind_address: "0.0.0.0:5060"
   threadiness: 8
   private_key: /etc/falco/certs/server.key
   cert_chain: /etc/falco/certs/server.crt
   root_certs: /etc/falco/certs/ca.crt

grpc_output:
      enabled: true`

**Expected behaviour**

CPU usage should be consistent across all nodes, and should be at a reasonable level.

**Screenshots**

**Environment**

k8s 1.16 deployed via kops, standard debian nodes.

- Falco version:
0.21.0
- System info:

- Cloud provider or hardware configuration:
AWS
- OS:
`Distributor ID: Debian
Description:    Debian GNU/Linux 9.11 (stretch)
Release:        9.11
Codename:       stretch
`
- Kernel:
4.4.0-1052-aws
- Installation method:
Kubernetes

**Additional context**

### PR DESCRIPTION
**Pull request by scallopboat**
Signed-off-by: Chris Meyer <scallopboat@gmail.com>

**What type of PR is this?**
/kind bug

**Any specific area of the project related to this PR?**
/area engine

**What this PR does / why we need it**:
Reduces the CPU usage of falco when the grpc server is enabled to ~15%.

**Which issue(s) this PR fixes**:
Fixes #1126 

**Special notes for your reviewer**:
Submitted as a potential (short term?) fix.  It'd likely be better to refactor such that a sleep isn't needed by using a local queue as suggested on 05-20-20 call, but wanted to submit this option regardless.

**Does this PR introduce a user-facing change?**:
NONE

```release-note
fix: High CPU usage when grpc server is enabled [#1126]
```

### CODE REVIEW

**Comment by scallopboat** [comment]
What the profiler captured when falco::grpc::server_impl::subscribe is active.
Screenshot from 2020-05-28 10-46-07

**Comment by fntlnz** [comment]
Thanks a lot for showing us this approach @scallopboat 

@leodido and I are trying to change the server architecture a little bit to avoid the try_pop in a while loop situation at all.


Here's the motivation: https://github.com/falcosecurity/falco/issues/1240
Here's a possible implementation: https://github.com/falcosecurity/falco/pull/1241

We still need to plot some gperftools and gprof graphs.

**Comment by leodido** [comment]
Hey @scallopboat thanks a lot for submitting this, I really appreciated it! 🙏

Anyways PR #1241 is ready to be merged in and it shows serious improvements reducing the CPU consumption when gRPC Falco Outputs are on.

Thus we'll close this in favor of that PR.

**Pull request closed without merging**
