### PR TITLE
fix(build): do not show plugin options in musl optimized builds

### PR DESCRIPTION
**Pull request by LucaGuerra**
Signed-off-by: Luca Guerra <luca@guerra.sh>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

/kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

> If contributing rules or changes to rules, please make sure to also uncomment one of the following line:

> /kind rule-update

> /kind rule-create

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area build

> /area engine

> /area rules

> /area tests

> /area proposals

**What this PR does / why we need it**:

Falco can be built with musl-libc but won't have plugin support in that case. Do not display the relevant option in the command line help. Likewise, do not include plugin directories as they cannot be used.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jasondellaluce** [comment]
This addresses the issue at 👉🏼  https://github.com/falcosecurity/falco/issues/1857#issuecomment-1022216209

**Review by leogr — APPROVED** [review]
/approve

**Review by jasondellaluce — APPROVED** [review]
/approve

**Comment by leogr** [comment]
Closing and reopening to trigger our beloved @poiana :heart: 

/close

**Pull request merged**
