### PR TITLE
update(scripts): add option for regenerating signatures of all dev and release packages

### PR DESCRIPTION
**Pull request by jasondellaluce**
**What type of PR is this?**

/kind cleanup

/kind feature

**Any specific area of the project related to this PR?**

/area CI

**What this PR does / why we need it**:

This PR adds a new `-s` optional parameter to the `publish-deb` and `publish-rpm` scripts that we use in our CI to upload and sign both dev and release packages on https://download.falco.org/?prefix=packages/. The flag is responsible of re-generating all the existing packages' signatures along with the newly-added ones.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
update(scripts): add option for regenerating signatures of all dev and release packages
```

### CODE REVIEW

**Review by FedeDP — APPROVED** [review]
Clean and nice :lab_coat: 
/approve

**Review by FedeDP — DISMISSED** [review]
/approve

**Comment by jasondellaluce** [comment]
Note: this will force the CI to re-sign all the existing packages at release time. Will turn off the flag after Falco 0.34.0.

**Review by FedeDP — DISMISSED** [review]
/approve

**Comment by jasondellaluce** [comment]
Now ready for review!

**Review by leogr — APPROVED** [review]

**Pull request merged**
