### PR TITLE
Fix various typos in markdown files.

### PR DESCRIPTION
**Pull request by didier-durand**
Hi there, 

As per title, just fixing typos in various .md files.

Didier

Signed-off-by: Didier Durand <durand.didier@gmail.com>

/kind documentation

**What this PR does / why we need it**:

Just some language cleanup

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
NO

```release-note
NONE
```

### CODE REVIEW

**Review by leogr — APPROVED** [review]
Thank you!

**Comment by didier-durand** [comment]
@leogr: it is my pleasure to contribute. Didier

**Review by leodido — APPROVED** [review]
Thanks Didier 🤗 

These fixes will go in the next release

**Comment by didier-durand** [comment]
@leodido : my pleasure to contribute! Didier

**Review by leogr — APPROVED** [review]
Hey @didier-durand 

I have rebased the PR for you and ported the `GOVERNANCE.md` correction to https://github.com/falcosecurity/.github/pull/26 (since the file had been moved).

Ofc, approved again. Thank you! :+1:

**Review by leodido — APPROVED** [review]

**Review by fntlnz — APPROVED** [review]

**Pull request merged**
