### PR TITLE
update(userspace/falco): make webserver threadiness configurable

### PR DESCRIPTION
**Pull request by jasondellaluce**
**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

/area engine

**What this PR does / why we need it**:

This improves the webserver by making the thread pool size configurable (by default equal to the number of online cores).

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
update(userspace/falco): make webserver threadiness configurable
```

### CODE REVIEW

**Comment by jasondellaluce** [comment]
Splitted this PR so that zlib support is now contributed in https://github.com/falcosecurity/falco/pull/2125

**Review by leogr — DISMISSED** [review]
:+1:

**Review by FedeDP — APPROVED** [review]
/approve

**Comment by jasondellaluce** [comment]
Closing and reopening to trigger the CI

/close

**Review by FedeDP — APPROVED** [review]
/approve

**Review by leogr — APPROVED** [review]

**Pull request merged**
