### PR TITLE
Add Fairwinds to ADOPTERS.md

### PR DESCRIPTION
**Pull request by sudermanjr**
Signed-off-by: Andrew Suderman <andrew@sudermanjr.com>

**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Fairwinds is adopting Falco

**Does this PR introduce a user-facing change?**:
Nope

```release-note
Add [Fairwinds](https://fairwinds.com) to the adopters list
```

### CODE REVIEW

**Comment by sudermanjr** [comment]
Build error looks like maybe it's due to an outage somewhere:

`Error uploading workspace archive: store-client upload workspace: the response from POST /api/v2/output/workspace was 503 (Service Unavailable) (14 attempts)`

**Review by jasondellaluce — APPROVED** [review]
/approve

**Review by leogr — APPROVED** [review]
/approve

**Pull request merged**
