### PR TITLE
build: hotfix for release 0.31.0

### PR DESCRIPTION
**Pull request by FedeDP**
Signed-off-by: Federico Di Pierro <nierro92@gmail.com>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

> If contributing rules or changes to rules, please make sure to also uncomment one of the following line:

> /kind rule-update

> /kind rule-create

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area build

> /area engine

> /area rules

> /area tests

> /area proposals

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by leogr — APPROVED** [review]
/approve

**Review by jasondellaluce — DISMISSED** [review]
/approve

**Comment by leogr** [comment]
@FedeDP thank you :pray: 

For the records: this PR tries to fix the issue we are having in the CI with the release pipeline :point_down: 
https://app.circleci.com/pipelines/github/falcosecurity/falco/2056/workflows/86c23e3b-6bf8-4127-b984-2b571190f16f/jobs/18820

**Review by jasondellaluce — APPROVED** [review]
/approve

**Comment by leogr** [comment]
Closing and reopening to trigger the CI
/close

**Pull request merged**
