### PR TITLE
new(.github): add dependabot configuration for updating git submodules

### PR DESCRIPTION
**Pull request by jasondellaluce**
**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

/area CI

**What this PR does / why we need it**:

Since we introduced git submodules in this repo after the migration of the default rules to falcosecurity/rules, I thought it would be helpful to setup dependabot to periodically open PRs for updating the submodules.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
new(.github): add dependabot configuration for updating git submodules
```

### CODE REVIEW

**Comment by FedeDP** [comment]
Fully agree!

**Review by FedeDP — APPROVED** [review]
/approve

**Review by leogr — APPROVED** [review]
Nice!

**Pull request merged**
