### PR TITLE
update(cmake): bumped libs to 0.17.0-rc1 and falcoctl to v0.8.0-rc6.

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind release

**Any specific area of the project related to this PR?**

/area build

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by LucaGuerra — APPROVED** [review]

**Review by Andreagit97 — APPROVED** [review]
/approve

**Comment by FedeDP** [comment]
We triggered some errors:
```
Error: engine_v4_k8s_audit_rules.yaml: Invalid
        	            	1 Errors:
        	            	In rules content: (engine_v4_k8s_audit_rules.yaml:0:0)
        	            	    rule 'ClusterRole With Pod Exec Created': (engine_v4_k8s_audit_rules.yaml:266:2)
        	            	    rule condition: (engine_v4_k8s_audit_rules.yaml:268:13)
        	            	    condition expression: ("kevt and (role or...":269:61)
        	            	------
        	            	... clusterrole) and kcreate and ka.req.role.rules.resources contains "pods/exec"
        	            	                                                                                ^
        	            	------
        	            	LOAD_ERR_COMPILE_CONDITION (Error compiling condition): filter error: 'contains' operator not supported list filters
```
cc @jasondellaluce (?)

**Comment by FedeDP** [comment]
Opened pr to fix: https://github.com/falcosecurity/testing/pull/58

**Pull request merged**
