### PR TITLE
feat(userspace/falco): print version at startup

### LINKED ISSUE #1302: Add the Falco version at the very beginning of the log
**Motivation**

Since there's no way to match logs reported by the users with the corresponding Falco version, I'd like Falco to print its version out at the beginning of the log.

It can be advantageous when debugging issues. The version reported by the user might be wrong for several reasons (by mistake, wrong copy/paste, cached container image, etc.)

**Feature**

Print the Falco and driver versions (similar to the output of `--version`) at the very beginning of the output.

**Alternatives**

Simply nothing :)

**Additional context**

IMHO, no other information should be printed out (for example, the gcc version, dependency version, and so on) to avoid mixing build-time metadata with run-time one. The goal here is just to match the log with a specific Falco version, not to provide detailed debugging information. Also, note that the version may contain the commit ID when Falco has not built from a tag matching a release. 

/cc @leodido 
/cc @fntlnz 

/assign

/milestone 0.24.0

### PR DESCRIPTION
**Pull request by leogr**
**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

/area engine

**What this PR does / why we need it**:

See #1302

**Which issue(s) this PR fixes**:

Fixes #1302

**Special notes for your reviewer**:

/milestone 0.24.0
/cc @fntlnz 
/cc @leodido 
/cc @kris-nova 

**Does this PR introduce a user-facing change?**:

```release-note
new(userspace/falco): print the Falco and driver versions at the very beginning of the output.
```

### CODE REVIEW

**Comment by leogr** [comment]
> SGTM!
> 
> Anyway, I have a question.
> 
> Why do not stick with the usual two-line version (line 626-627) logs we use for the `--version` flag in order to be more consistent?
> 
> There's a particular reason to print Falco version and driver version this way when Falco runs?

Lines 626-627 uses `printf`, here I use the initialized logger. Moreover, I have found just one-line output briefer.
No other reasons. 
Let me know if you prefer a two-line, and I will change it shortly.

**Comment by leodido** [comment]
I don't have particular preferences honestly.

I was just asking if there was a ratio behind putting both versions on the same line. That's all!

**Comment by leodido** [comment]
Moving this to next release because it hasn't reached 2 approvals

/milestone 0.25.0

**Comment by fntlnz** [comment]
Approved, I think we can get this in now!

**Pull request merged**
