### PR TITLE
update(engine): allow using -p to pass a format to plugin events

### LINKED ISSUE #3237: Falco 0.38.0 crashes with -pc/-pk and any plugin loaded
**Describe the bug**

Deploy Falco 0.38.0 with any configuration that has `-pc` or `-pk` and enable a plugin, such as k8s_audit

```
Defaulted container "falco" out of: falco, falcoctl-artifact-follow, falco-driver-loader (init), falcoctl-artifact-install (init)
Tue Jun  4 08:56:33 2024: Using deprecated config key 'rules_file' (singular form). Please use new 'rules_files' config key (plural form).
Tue Jun  4 08:56:33 2024: Falco version: 0.38.0 (x86_64)
Tue Jun  4 08:56:33 2024: Falco initialized with configuration files:
Tue Jun  4 08:56:33 2024:    /etc/falco/falco.yaml
Tue Jun  4 08:56:33 2024: System info: Linux version 5.15.0-72-generic (buildd@lcy02-amd64-035) (gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #79-Ubuntu SMP Wed Apr 19 08:22:18 UTC 2023
Tue Jun  4 08:56:33 2024: Loading plugin 'k8saudit' from file /usr/share/falco/plugins/libk8saudit.so
Tue Jun  4 08:56:33 2024: Loading plugin 'json' from file /usr/share/falco/plugins/libjson.so
Tue Jun  4 08:56:33 2024: Loading rules from file /etc/falco/falco_rules.yaml
Tue Jun  4 08:56:33 2024: Loading rules from file /etc/falco/k8s_audit_rules.yaml
Error: /etc/falco/k8s_audit_rules.yaml: Invalid
1 Errors:
In rules content: (/etc/falco/k8s_audit_rules.yaml:0:0)
    rule 'Disallowed K8s User': (/etc/falco/k8s_audit_rules.yaml:122:2)
    rule output: (/etc/falco/k8s_audit_rules.yaml:125:10)
------
  output: K8s Operation performed by user not in allowed list of users (user=%ka.user.na...
          ^
------
LOAD_ERR_COMPILE_OUTPUT (Error compiling output): invalid formatting token container.id container_image=%container.image.repository container_image_tag=%container.image.tag container_name=%container.name k8s_ns=%k8s.ns.name k8s_pod_name=%k8s.pod.name
``` 

If you think about it, this is actually the same concept as https://github.com/falcosecurity/falco/issues/466

### PR DESCRIPTION
**Pull request by LucaGuerra**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area engine

**What this PR does / why we need it**:

For Falco 0.38.1 we wish to fix a rule loader error when using `-pk` with k8s_audit plugin enabled. However, we may still wish to let people using plugins use `-p` to customize the output. So, following @sboschman 's suggestion we can enable `-p` for all sources and keep `-pc`, `-pk` etc for syscall sources.

**Which issue(s) this PR fixes**:

Fixes #3237

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
update(engine): enable -p option for all sources, -pk, -pc etc only for syscall sources
```

### CODE REVIEW

**Comment by LucaGuerra** [comment]
@falcosecurity/falco-maintainers what do you think? Is it an acceptable compromise for 0.38.1?

**Review by incertum — APPROVED** [review]
/approve

Nice!

**Review by FedeDP — APPROVED** [review]
/approve

**Pull request merged**
