### PR TITLE
update(docker): remove `minimal` image

### PR DESCRIPTION
**Pull request by leogr**
Signed-off-by: Leonardo Grasso <me@leonardograsso.com>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

/kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

> If contributing rules or changes to rules, please make sure to also uncomment one of the following line:

> /kind rule-update

> /kind rule-create

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area build

> /area engine

> /area examples

> /area rules

> /area integrations

> /area tests

> /area proposals

**What this PR does / why we need it**:

As per "Falco Artifacts Scope" proposal :point_right: #1184

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

- There's no reference to it on the web site (except for the changelog part of two [blog posts](https://github.com/falcosecurity/falco-website/search?q=minimal&unscoped_q=minimal)
- It is not used by integrations nor examples
- The helm chart does not use it

PS
Since the multi-stage build approach used by this minimal image seems still valid to me, I would propose - in another PR - to refactor the current `docker/slim/Dockerfile` in the same way but once we have decided the proper naming of these images.

/cc @fntlnz 
/cc @kris-nova 
/cc @leodido 

**Does this PR introduce a user-facing change?**:

```release-note
update(docker): remove `minimal` image
```

### CODE REVIEW

**Comment by leogr** [comment]
/hold
for #1184

**Comment by leogr** [comment]
Rebased.

**Comment by leogr** [comment]
/honk 
:eagle:

**Comment by JPLachance** [comment]
I just found this PR and it makes me a little bit sad.

This image was a cool experiment made @mfdii. The goal was to reduce the amount of packages shipped in the Falco container image to easily pass container images scanners like Clair or Snyk.

A quick scan with Snyk of the falcosecurity/falco:0.22.1-slim Docker image reveals there are 103 known vulnerabilities in the image. The "minimal" image fixed that.

**Comment by leogr** [comment]
Hey @JPLachance 
this PR was just an intermediate step, the content of the old `minimal` will be re-published as `falcosecurity/falco-no-driver` as proposed here https://github.com/falcosecurity/falco/blob/master/proposals/20200506-artifacts-scope-part-2.md#images

I believe we can do this before the next release.
So the only breaking change will be just to change the image name.
WDYT?

**Comment by JPLachance** [comment]
Great then! I'll be happy to test te new image once we will have a way to load the probe :D

https://github.com/falcosecurity/falco/issues/897

**Pull request merged**
