### PR TITLE
fix(ci): fixed docker manifest circleci.

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind bug

**Any specific area of the project related to this PR?**

/area build

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by jasondellaluce — APPROVED** [review]
/approve

**Review by leogr — APPROVED** [review]
/approve

**Pull request merged**
