### PR TITLE
debian package: use systemd if available

### PR DESCRIPTION
**Pull request by juju4**
**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

NONE

**What this PR does / why we need it**:

#484

```release-note
* switch to systemd if available in debian package
* hardened systemd settings
```

### CODE REVIEW

**Comment by fntlnz** [comment]
Hi @juju4 - Thanks for your PR :) We really need this!

Please send your PR against the `dev` branch. `master` is unused now and we have to work on making it the new default, but `dev` is the default now.

**Comment by juju4** [comment]
I believe branch+rebase and signoff should be fine now. hopefully not too messed-up.

**Comment by leodido** [comment]
Ok, I cleaned up the wrong rebase.

Now this branch is candidate to merge as soon everything looks 👌

**Comment by fntlnz** [comment]
Closing and reopening to let poiana handle this

**Comment by leogr** [comment]
Hey @juju4 

Are you still working on this PR? Any updates?

**Comment by juju4** [comment]
> As described, send against `dev`

don't see any dev branch currently when editing PR

**Comment by juju4** [comment]
I'm pretty sure I did dco but https://github.com/falcosecurity/falco/blob/master/CONTRIBUTING.md is dead
seeing the long list of signoff needed, I think I need some rebase...

**Review by leogr — COMMENTED** [review]
Hey @juju4 

Unfortunately, this PR has been opened for a long time, and many things have changed.
I see a lot of merge-commits (that we don't allow to be merged in), and those commits have been not signed off.
So, I believe there are only two options here: rebasing this PR on top of the current master (removing all merge-commits) or creating a new PR.

Btw, recently I noticed that a new similar PR (#1448) was opened, which aims to migrate both RPM and DEB packages. At this point, perhaps it is worth collaborating with the author of the other PR?

**Comment by leogr** [comment]
PS
The contribution guideline has been moved here :point_down: 
https://github.com/falcosecurity/.github/blob/master/CONTRIBUTING.md

**Comment by leogr** [comment]
Closing this since https://github.com/falcosecurity/falco/pull/1448 has been merged.

**Pull request closed without merging**
