### PR TITLE
Add darryk10 as rules OWNERS as reviewer

### PR DESCRIPTION
**Pull request by darryk10**
Signed-off-by: darryk10 <stefano.chierici@sysdig.com>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

/kind documentation

> /kind failing-test

> /kind feature

> If contributing rules or changes to rules, please make sure to also uncomment one of the following line:

> /kind rule-update

> /kind rule-create

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

> /area engine

/area rules

> /area tests

> /area proposals

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
I would like propose myself as a reviewer of rules in falcosecurity/falco.

After actively working and contributing to this repository over the past year and a half with new falco rules and proactively reviewing new PRs related to rules, I want to propose myself as a reviewer of rules and spend more time working on falco rules, helping the project grows.

**Does this PR introduce a user-facing change?**:

```release-note
docs: add darryk10 to rules OWNERS as reviewer
```

### CODE REVIEW

**Review by Kaizhe — APPROVED** [review]

**Comment by Kaizhe** [comment]
@darryk10 has been actively helping the community (reviewing PRs and asking questions in the slack channel), I would love to see him step up as a Falco rule reviewer. With his expertise and dedication, we will all be beneficials.

**Comment by loresuso** [comment]
As a contributor of Falco and some of its rules, I think @darryk10 really deserves this, +1 from my side!

**Comment by jasondellaluce** [comment]
As said in the community call, I'm a strong supporter of this. +1 for me 👍🏼

**Comment by leogr** [comment]
+1 for me too!

Since we reached a consensus, I'll invite @darryk10 to the org, then we can merge this :)

**Comment by darryk10** [comment]
> +1 for me too!
> 
> Since we reached a consensus, I'll invite @darryk10 to the org, then we can merge this :)

Thanks @leogr and Thanks all for the support. I accepted the invite :)

**Review by leogr — APPROVED** [review]
/approve

**Comment by leogr** [comment]
Closing and reopening to trigger the CI

/close

**Comment by leogr** [comment]
/hold

Waiting for the CI

**Pull request merged**
