### PR TITLE
update(falco): updates usage description for -o, --option

### LINKED ISSUE #1898: Help message for `-o, --option` is not accurate
**Describe the bug**

The `falco --help` message reports an outdated description for the `-o` options :point_down: 

```
 -o, --option <key>=<val>      Set the value of option <key> to <val>. Overrides values in configuration file.
                               <key> can be a two-part <key>.<subkey>
```
The message says that one can use `<key>.<subkey>` (1 level nesting), but since https://github.com/falcosecurity/falco/pull/1792 arbitrary-depth nested values in configuration should be supported.

**How to reproduce it**

Run `falco --help`.

**Expected behaviour**

A clear and concise description of what users can do with `-o`.

**Screenshots**

**Environment**

- Falco version: 0.31.0
- System info:

- Cloud provider or hardware configuration:
- OS:

- Kernel:

- Installation method:

**Additional context**

Currently, only the `plugins` configuration node has more than one nesting level. So the only way I found to test that nesting is working:
```
❯ falco -o "plugins[0].library_path=non-existing.so" --list-plugins
Sat Feb 12 18:44:17 2022: Falco version 0.31.0 (driver version 319368f1ad778691164d33d59945e00c5752cd27)
Sat Feb 12 18:44:17 2022: Falco initialized with configuration file /etc/falco/falco.yaml
Sat Feb 12 18:44:17 2022: Loading plugin (cloudtrail) from file /usr/share/falco/plugins/non-existing.so
Sat Feb 12 18:44:17 2022: Runtime error: cannot load plugin /usr/share/falco/plugins/non-existing.so: error loading plugin /usr/share/falco/plugins/non-existing.so: /usr/share/falco/plugins/non-existing.so: cannot open shared object file: No such file or directory. Exiting.
```

### PR DESCRIPTION
**Pull request by andreabonanno**
Signed-off-by: Andrea Bonanno <andrea@bonanno.cloud>

**What type of PR is this?**

**Any specific area of the project related to this PR?**

**What this PR does / why we need it**:

Updates Falco  usage text for `-o, --option`, so it reflects the update of  #1792 

**Which issue(s) this PR fixes**:
Fixes #1898 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jasondellaluce** [comment]
Thank you @andreabonanno! I would also explicit the fact that array-like notations can be used too. For example, the following is allowed: `plugins[0].init_config="hello"`.

**Review by leogr — APPROVED** [review]
/approve

**Review by jasondellaluce — APPROVED** [review]

**Pull request merged**
