### PR TITLE
sync: cherry picks from master for release 0.36.0

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

/area build

**What this PR does / why we need it**:

Cherry picks from master:
- https://github.com/falcosecurity/falco/pull/2834
- https://github.com/falcosecurity/falco/pull/2812
- https://github.com/falcosecurity/falco/pull/2828
- https://github.com/falcosecurity/falco/pull/2829
- https://github.com/falcosecurity/falco/pull/2826
- https://github.com/falcosecurity/falco/pull/2830
- https://github.com/falcosecurity/falco/pull/2831
- https://github.com/falcosecurity/falco/pull/2833

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by LucaGuerra — DISMISSED** [review]

**Review by Andreagit97 — DISMISSED** [review]
/approve

**Comment by FedeDP** [comment]
This is the last sync needed ;)

**Review by Andreagit97 — APPROVED** [review]
/approve

**Review by leogr — APPROVED** [review]

**Pull request merged**
