### PR TITLE
Build Falco on ppc64le

### PR DESCRIPTION
**Pull request by sarveshtamba**
Signed-off-by: sarveshtamba <sarvesh.tamba@ibm.com>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

/kind feature

> If contributing rules or changes to rules, please make sure to also uncomment one of the following line:

> /kind rule-update

> /kind rule-create

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area build

> /area engine

> /area rules

> /area tests

> /area proposals

**What this PR does / why we need it**: Support to build Falco on ppc64le.

**Which issue(s) this PR fixes**: Support to build Falco on ppc64le.

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Support to build Falco on ppc64le.
```

### CODE REVIEW

**Comment by fntlnz** [comment]
Once this is ready, I think that we can add a test runner for docker using `--platform=linux/ppc64le` in order to let our test run for ppc too.

**Comment by kris-nova** [comment]
Next steps:

@sarveshtamba 
 - Test moonjit vs raptorjit for the Power PC use case 
    - Does it work with both?
    - Does it work with only moonjit?

@fntlnz 
 - Test moonjit with CircleCI to see if the tests pass/fail

**Comment by shirodkara** [comment]
> Next steps:
> 
> @sarveshtamba
> 
>     * Test moonjit vs raptorjit for the Power PC use case
>       
>       * Does it work with both?
>       * Does it work with only moonjit?
> 
@kris-nova @fntlnz I wasn't able to build raptorjit on PowerPC , so on power, falco builds only with moonjit.

**Comment by fntlnz** [comment]
I tested this and works very well. Moonjit is the right option in my opinion.

**Pull request closed without merging**
