### PR TITLE
vote: update(OWNERS): add Andrea Terzolo to owners

### PR DESCRIPTION
**Pull request by Andreagit97**
**What type of PR is this?**

/kind documentation

**Any specific area of the project related to this PR?**

None

**What this PR does / why we need it**:

Hi folks :vulcan_salute:  As said in today's community call, I propose myself as a maintainer for Falco core repo.
I have been highly involved in various activities linked to Falco and its surrounding projects and I tried my best to help review code and help people all around the community, I'm looking forward to helping also here :)
Please if you have any suggestions or concerns feel free to share!
Thank you!

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by leogr** [comment]
Per our governance, this requires a [majority vote](https://github.com/falcosecurity/evolution/blob/main/GOVERNANCE.md#majority-vote). So, @falcosecurity/falco-maintainers cast your vote, please :smiley: 

Hold until we get the majority.
/hold

**Comment by leogr** [comment]
Ofc, big +1 from me :smile:

**Comment by jasondellaluce** [comment]
+1

**Review by leogr — APPROVED** [review]
The majority has been reached :partying_face: 

/unhold

**Review by jasondellaluce — APPROVED** [review]
/approve

**Pull request merged**
