### PR TITLE
Also copy ruleset when copying falco source

### PR DESCRIPTION
**Pull request by mstemm**
In the copy constructor and assignment operator for falco_source, also copy the ruleset along with factories/name.

Signed-off-by: Mark Stemm <mark.stemm@gmail.com>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

> /kind release

> If contributing rules or changes to rules, please make sure to also uncomment one of the following line:

> /kind rule-update

> /kind rule-create

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

/area engine

> /area rules

> /area tests

> /area proposals

> /area CI

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Ensure that a ruleset object is copied properly in falco_engine::add_source().
```

### CODE REVIEW

**Comment by mstemm** [comment]
I understand why falco itself is okay, the ruleset for the source is created from the factory in load_rules(): https://github.com/falcosecurity/falco/blob/master/userspace/engine/falco_engine.cpp#L194. A ruleset for the source is *also* created in add_source: https://github.com/falcosecurity/falco/blob/master/userspace/engine/falco_engine.cpp#L406, but that one is not copied properly.

I think this crash can only occur if you call complete_rule_loading without ever calling load_rules(). So not a real problem, but would still be a good corner case to fix.

**Review by FedeDP — APPROVED** [review]
/approve

**Review by jasondellaluce — APPROVED** [review]
/approve

**Pull request merged**
