### PR TITLE
fix(scripts): fixed falco-driver-loader driver download url.

### PR DESCRIPTION
**Pull request by FedeDP**
Signed-off-by: Federico Di Pierro <nierro92@gmail.com>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

/kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

> If contributing rules or changes to rules, please make sure to also uncomment one of the following line:

> /kind rule-update

> /kind rule-create

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

> /area engine

> /area rules

> /area tests

> /area proposals

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

This is part of a bigger change on how we store drivers on s3 bucket.
Next changes need to be made in test-infra driverkit makefile and will come in the next days.

**Does this PR introduce a user-facing change?**:

```release-note
fix(scripts): falco-driver-loader script will now seek for drivers in driver/${ARCH}/ for x86_64 too.
```

### CODE REVIEW

**Review by jasondellaluce — APPROVED** [review]
/approve

/bark

❤️

**Comment by FedeDP** [comment]
Poiana is love, poiana is life :heart:

**Review by leogr — APPROVED** [review]
I assume we will publish the driver with the new directory structure in time :) 

@FedeDP we have to update the documentation too :point_down: 
https://falco.org/docs/getting-started/installation/#install-driver

**Pull request merged**
