### PR TITLE
remove unused files in test directory

### PR DESCRIPTION
**Pull request by jasondellaluce**
Signed-off-by: Jason Dellaluce <jasondellaluce@gmail.com>

**What type of PR is this?**

/kind cleanup

**Any specific area of the project related to this PR?**

/area tests

**What this PR does / why we need it**:

This cleans up the `test` directory by removing some legacy scripts that seem to not be used anymore by Falco.
- `run_performance_tests.sh`
- `plot-live.r`
- `plot-traces.r`
- `cpu_monitor.sh`

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by leogr — APPROVED** [review]
:partying_face: 

/milestone 0.31.0
/approve

**Review by mstemm — APPROVED** [review]
Thanks--I originally added them a long long time ago when we were doing a round of falco performance testing. They're potentially useful if we want to do another round of performance testing, but I'm fine with removing them from the tree for now.

**Pull request merged**
