### PR TITLE
Correct linting issue in rules

### PR DESCRIPTION
**Pull request by stephanmiehe**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

/kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

> If contributing rules or changes to rules, please make sure to also uncomment one of the following line:

> /kind rule-update

> /kind rule-create

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

> /area engine

/area rules

> /area tests

> /area proposals

**What this PR does / why we need it**: Fixes a linting issue in the rules yaml

**Which issue(s) this PR fixes**: None

Fixes # 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**: No

```release-note
NONE
```

### CODE REVIEW

**Comment by jasondellaluce** [comment]
Closing and reopening to trigger the CI

/close

**Comment by jasondellaluce** [comment]
@stephanmiehe thank you for this! Can you please rebase your branch to master? That should be enough to make the CI jobs succeed!

**Comment by stephanmiehe** [comment]
Moved to https://github.com/falcosecurity/falco/pull/2055

**Pull request closed without merging**
