### PR TITLE
refactor(userspace/engine): reduce allocations during rules loading

### PR DESCRIPTION
**Pull request by jasondellaluce**
**What type of PR is this?**

/kind cleanup

**Any specific area of the project related to this PR?**

/area engine

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

When loading large rulesets, I noticed a spike of allocations that could be mitigated with few changes.

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
refactor(userspace/engine): reduce allocations during rules loading
```

### CODE REVIEW

**Review by FedeDP — APPROVED** [review]
/approve

**Review by Andreagit97 — APPROVED** [review]
/approve

**Review by leogr — APPROVED** [review]

**Pull request merged**
