### PR TITLE
Address rules fps

### PR DESCRIPTION
**Pull request by mstemm**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

> If contributing rules or changes to rules, please make sure to also uncomment one of the following line:

/kind rule-update

> /kind rule-create

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

> /area engine

> /area examples

/area rules

> /area integrations

> /area tests

> /area proposals

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Address several rules FPs observed in live environments
```

### CODE REVIEW

**Comment by mstemm** [comment]
Yay for regression tests! I fixed the rules and they’re passing now.

**Comment by fntlnz** [comment]
This looks good as always @mstemm .
We need better release notes for this before the merge or at least before the next release.

See: https://github.com/falcosecurity/falco/blob/dev/CONTRIBUTING.md#rule-type

**Comment by mstemm** [comment]
Okay, updated the release notes with the rule names and changes.

**Comment by fntlnz** [comment]
Thank you @mstemm !

**Pull request merged**
