### PR TITLE
Sync/release 0.35.0

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind release

**Any specific area of the project related to this PR?**

/area build

**What this PR does / why we need it**:

* Cherry picks https://github.com/falcosecurity/falco/pull/2618
* Updated changelog for release 0.35.0

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
new(docs): updated changelog for 0.35.0
```

### CODE REVIEW

**Review by Andreagit97 — APPROVED** [review]
/approve

**Comment by FedeDP** [comment]
The changelog commit will be then cherry picked into master branch too!

**Review by jasondellaluce — APPROVED** [review]
/approve

**Review by leogr — APPROVED** [review]

**Pull request merged**
