### PR TITLE
Add CodeQL Security Scanning

### PR DESCRIPTION
**Pull request by caniszczyk**
**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

/area build

**What this PR does / why we need it**:

This PR introduces CodeQL security scanning to Falco.

### How to try it out

Visit https://github.com/falcosecurity/falco/security/code-scanning

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

/hold

**Does this PR introduce a user-facing change?**:

```release-note
Add CodeQL security scanning
```

Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>

### CODE REVIEW

**Review by leodido — COMMENTED** [review]
Hello @caniszczyk, thanks for submitting this. It's really needed.

Would you please fill the PR template anyway to help us (and the community) understand its scope?

**Comment by caniszczyk** [comment]
@leodido updated the PR based on your template

**Pull request closed without merging**
