### PR TITLE
update: add allowed types to falcoctl artifact follow service

### PR DESCRIPTION
**Pull request by loresuso**
Signed-off-by: Lorenzo Susini <susinilorenzo1@gmail.com>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

/kind feature

> /kind release

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

> /area engine

> /area tests

> /area proposals

> /area CI

**What this PR does / why we need it**:

Ensure the falcoctl service can follow only rulesfiles.
Waiting falcoctl version bump so the we can bump the version also here.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
build: upgrade to `falcoctl` v0.4.0
```

### CODE REVIEW

**Review by Andreagit97 — APPROVED** [review]
/approve

**Review by leogr — APPROVED** [review]
:crossed_fingers:

**Review by Andreagit97 — APPROVED** [review]
/approve

**Pull request merged**
