### PR TITLE
chore(ci): use actuated get-kernel-sources action.

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind cleanup

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area CI

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by FedeDP** [comment]
>  CI Build / test-dev-packages-arm64 / test-packages (pull_request) In progress — This check has started... 

I don't get why yesterday it was working, and today it is not (it's just hanging).

**Review by Andreagit97 — APPROVED** [review]
/approve

**Comment by FedeDP** [comment]
/close
Since the `test-dev-packages-arm64` falco-driver-loader part is troublesome, i am going to revert it and drop it.

**Pull request closed without merging**
