### PR TITLE
rules update(Change thread namespace and Set Setuid or Setgid bit): d…

### PR DESCRIPTION
**Pull request by Kaizhe**
…isable by default

Signed-off-by: Kaizhe Huang <derek0405@gmail.com>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

> If contributing rules or changes to rules, please make sure to also uncomment one of the following line:

 /kind rule-update

> /kind rule-create

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

> /area engine

 /area rules

> /area tests

> /area proposals

**What this PR does / why we need it**:

The falco rules `Change thread namespace` and `Set Setuid or Setgid bit` are known to be noisy. Disable these two rules by default. 

**Which issue(s) this PR fixes**:

Reduce FP.

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
rules update(Change thread namespace and Set Setuid or Setgid bit): disable by default

```

### CODE REVIEW

**Review by mstemm — DISMISSED** [review]

**Comment by Kaizhe** [comment]
@mstemm , did I miss anything on changing the test side?

**Comment by leogr** [comment]
> @mstemm , did I miss anything on changing the test side?

Hey @Kaizhe 

it seems to me that a few [integration tests](https://app.circleci.com/pipelines/github/falcosecurity/falco/1492/workflows/93e3a6ab-0c80-4328-83f4-95026c6a592b/jobs/12418) are expecting those rules to be enabled.

**Comment by Kaizhe** [comment]
Finally, @leodido @leogr can you please take a look?

**Review by fntlnz — APPROVED** [review]

**Review by leodido — APPROVED** [review]

**Review by leogr — APPROVED** [review]
/approve

**Pull request merged**
