### PR TITLE
update(cmake): bump libs and driver to 5b4e28d4 

### PR DESCRIPTION
**Pull request by jasondellaluce**
**What type of PR is this?**

/kind cleanup

/kind release

**Any specific area of the project related to this PR?**

/area engine

/area tests

**What this PR does / why we need it**:

This adjusts Falco for compiling with the newest libs and and drivers and bumps their dependency.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
update(cmake): bump libs and driver to 5b4e28d4 
```

### CODE REVIEW

**Review by FedeDP — APPROVED** [review]
/approve

**Comment by jasondellaluce** [comment]
Seems like the we have issues with the MUSL static build. This seems to be the offending PR -- https://github.com/falcosecurity/libs/pull/1394

Any ideas @LucaGuerra, @jcpittman144?

**Review by incertum — APPROVED** [review]
/approve

**Pull request closed without merging**
