### PR TITLE
fix(scripts): fixed falco-driver-loader kmod cleanup

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind bug

**Any specific area of the project related to this PR?**

**What this PR does / why we need it**:

Properly cleanup leftover kmod files under /lib/modules.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
fix(scripts): properly cleanup all kmod leftover instances
```

### CODE REVIEW

**Review by leogr — COMMENTED** [review]
As discussed privately, the root cause should be the usage of `modprobe` introduced by https://github.com/falcosecurity/falco/pull/2242/files#diff-7adb35e11672e18c2abdb4b2a7a9e24758301c4080499fa6b47379710b10bd49.

IIRC, in the past, `modprobe` was removed in favor of `insmod` because the latter ensures that the correct build of the module will be loaded.

My proposal is to revert that change, and use only locally built drivers for deb and rpm packages. In this way, the kmod is only tracked by dkms, and no other moving parts will be involved (as it was before).

**Comment by FedeDP** [comment]
Fully agree with you @leogr ! I am going to revert some of the changes you highlighted! 
Thank you!
/close

**Pull request closed without merging**
