### PR TITLE
fix(ci): fixed bump-libs workflow syntax.

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind bug

**Any specific area of the project related to this PR?**

/area CI

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by FedeDP** [comment]
The fix works fine: https://github.com/falcosecurity/falco/actions/runs/11214452899/job/31169562643 and https://github.com/falcosecurity/falco/pull/3370

**Comment by FedeDP** [comment]
/hold 
it does not actually: https://github.com/falcosecurity/falco/pull/3370/files

**Review by leogr — DISMISSED** [review]

**Comment by FedeDP** [comment]
Ok works fine now: https://github.com/falcosecurity/falco/actions/runs/11214764080/job/31170518646 and https://github.com/falcosecurity/falco/pull/3370/files

/unhold

**Review by leogr — APPROVED** [review]

**Pull request merged**
