### PR TITLE
fix(engine): logical issue in exceptions condition

### PR DESCRIPTION
**Pull request by mrgian**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

> /kind release

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

/area engine

/area tests

> /area proposals

> /area CI

**What this PR does / why we need it**:
Fixes handling of rules using exceptions and conditions with `or` operator

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
fix(engine): logical issue in exceptions condition
```

### CODE REVIEW

**Review by jasondellaluce — APPROVED** [review]
/approve

**Review by FedeDP — APPROVED** [review]
/approve

**Pull request merged**
