### PR TITLE
fix(gha): disable branch protection rule trigger for scorecard

### PR DESCRIPTION
**Pull request by LucaGuerra**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area CI

**What this PR does / why we need it**:

As per attached screenshot, which is not supposed to happen:
image

I'm not completely sure what triggers it (but 99% is test-infra checking if repos need to be updated) but I believe it's safe to disable it for now.

Thanks @Andreagit97 @FedeDP for the heads up and taking a look at our pipelines!

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by FedeDP** [comment]
> but 99% is test-infra checking if repos need to be updated

Pretty sure it is :) great catch!

**Review by FedeDP — APPROVED** [review]
/approve

**Review by Andreagit97 — APPROVED** [review]
/approve

**Pull request merged**
