### PR TITLE
fix(tests): make tests run locally (take 2)

### PR DESCRIPTION
**Pull request by LucaGuerra**
Signed-off-by: Luca Guerra <luca@guerra.sh>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> If contributing rules or changes to rules, please make sure to also uncomment one of the following line:

> /kind rule-update

> /kind rule-create

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

> /area engine

> /area rules

/area tests

> /area proposals

**What this PR does / why we need it**:

In an attempt to make it easier for people to run tests locally I messed up the bash script which currently does not report failed tests correctly. This reverts the change and adds correct instructions to the README about how to run it. As it turns out, I was missing an option or badly specified it before.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jasondellaluce** [comment]
Closing and reopening to trigger the CI

/close

**Review by jasondellaluce — APPROVED** [review]
/approve

**Comment by leogr** [comment]
/close

Closing and reopening to trigger the CI

**Review by leogr — APPROVED** [review]

**Pull request merged**
