### PR TITLE
update(cmake): bump plugin versions

### PR DESCRIPTION
**Pull request by loresuso**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

> /kind release

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

> /area engine

> /area tests

> /area proposals

> /area CI

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
update(cmake): bump plugins to latest versions
```

### CODE REVIEW

**Review by FedeDP — COMMENTED** [review]
We need to update hashes too! :)

**Comment by loresuso** [comment]
Yeah ofc, I was just waiting :)

**Review by FedeDP — APPROVED** [review]
/approve

**Comment by jasondellaluce** [comment]
At line 17:
```
set(PLUGINS_DOWNLOAD_BUCKET "dev")
```
Should be set to `"stable"`.

**Review by jasondellaluce — APPROVED** [review]

**Review by FedeDP — APPROVED** [review]
/approve

**Pull request merged**
