### PR TITLE
fix(scripts): force rpm postinstall script to always show dialog, even on upgrade

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind bug

**Any specific area of the project related to this PR?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by Andreagit97 — APPROVED** [review]
/approve

**Comment by FedeDP** [comment]
Can confirm the dialog is now shown on upgrade too!

**Review by jasondellaluce — APPROVED** [review]
/approve

**Pull request merged**
