### PR TITLE
cleanup(ci): remove some unused jobs and remove some `falco-builder` reference where possible

### PR DESCRIPTION
**Pull request by Andreagit97**
**What type of PR is this?**

/kind cleanup

**Any specific area of the project related to this PR?**

/area CI

**What this PR does / why we need it**:

This PR is a first attempt to remove all `falco-builder` usages.

It removes 2 possible unused jobs from GH:
* `build-ubuntu-bionic` -> `ubuntu-18.04` image is deprecated and I don't see so much value in building Falco on ubuntu bionic :thinking: 
* `build-centos7-debug`-> we already build Falco on centos 7 in circle ci, so why we need to duplicate the job here :thinking: 

It modifies 2 jobs in circleCI:
* `quality-static-analysis` now uses ubuntu.22-04
* `rpm-sign` now uses a simple centos7 image, we don't need the falco-builder, or am I missing something?

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by FedeDP — APPROVED** [review]
Fully agree; making CI quicker is always good, when we do not lose any build /test.
/approve

**Review by leogr — APPROVED** [review]

**Pull request merged**
