### PR TITLE
update(falco): update libs to dc02e50

### PR DESCRIPTION
**Pull request by LucaGuerra**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind feature
/area build

**What this PR does / why we need it**:

Update libs to the latest available version for testing and development.

```release-note
NONE
```

### CODE REVIEW

**Review by leogr — APPROVED** [review]

**Comment by LucaGuerra** [comment]
Hmmm, CI isn't happy 🤔

**Comment by jasondellaluce** [comment]
I think we need to update the driver version to the latest commit hash too.

**Comment by jasondellaluce** [comment]
@LucaGuerra I pushed a commit in libs that should fix the issues with the musl build, I think you just need to bump to the latest hash again.

**Comment by LucaGuerra** [comment]
@jasondellaluce seems like we found the first bug with this bump 😄

**Review by FedeDP — APPROVED** [review]
/approve

**Review by jasondellaluce — APPROVED** [review]
/approve

**Pull request merged**
