### PR TITLE
build: hardening flags

### PR DESCRIPTION
**Pull request by leogr**
**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

/area build

**What this PR does / why we need it**:

This PR explicitly sets common hardening flags to be used by default for building Falco.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

I have opted for `-fstack-protector-strong` over `-fstack-protector-all` to avoid any potential performance penalty (more info can be found :point_right: [here](https://wiki.debian.org/Hardening#DEB_BUILD_HARDENING_STACKPROTECTOR_.28gcc.2Fg.2B-.2B-_-fstack-protector-strong.29))

Tested with [gdb-peda](https://github.com/longld/peda)
```
gdb-peda$ checksec
CANARY    : ENABLED
FORTIFY   : ENABLED
NX        : ENABLED
PIE       : ENABLED
RELRO     : FULL
```

**Does this PR introduce a user-facing change?**:

```release-note
build: enforcing hardening flags by default
```

### CODE REVIEW

**Review by leodido — APPROVED** [review]

**Comment by leogr** [comment]
/hold
to let other PRs get merged

**Review by fntlnz — APPROVED** [review]

**Pull request merged**
