### PR TITLE
Add ECR repository to rules

### PR DESCRIPTION
**Pull request by calvinbui**
Signed-off-by: Calvin Bui <3604363+calvinbui@users.noreply.github.com>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

> If contributing rules or changes to rules, please make sure to also uncomment one of the following line:

/kind rule-update

> /kind rule-create

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Add the official Falco ECR repository to rules
```

### CODE REVIEW

**Comment by Kaizhe** [comment]
@leogr ,do we build the falco image for the public.ecr.aws registry?

**Comment by Kaizhe** [comment]
> References:
> 
> * https://github.com/falcosecurity/falco/blame/master/RELEASE.md#L78
> * [Publish Falco container image to AWS ECR Public registry #1512](https://github.com/falcosecurity/falco/pull/1512)

Great! @calvinbui thanks for making the rule completed!

**Review by Kaizhe — APPROVED** [review]
/lgtm

**Comment by leogr** [comment]
Closing and reopening to trigger the CI
/close

**Review by leogr — APPROVED** [review]
/approve

Thank you!

**Pull request merged**
