### PR TITLE
update(userspace/engine): improve skip-if-unknown-filter YAML field

### PR DESCRIPTION
**Pull request by jasondellaluce**
**What type of PR is this?**

/kind bug

/kind feature

**Any specific area of the project related to this PR?**

/area engine

**What this PR does / why we need it**:

The `skip-if-unknown-filter` YAML field can be used in Falco rules for skipping a rules if it fails compilation due to an unknown filter field. This PR proposes enlarging its scope to also missing fields in rules' outputs (a bug, currently), and also checking for unknown event types (which can occur more frequently, now that plugins can define new value of `evt.type` with async events). The idea is for `skip-if-unknown-filter` to skip rules if "there's something unknown in a rule's filter", with the output being included for parity as it uses the same fields available for rules' filters.

A follow-up PR adding tests is https://github.com/falcosecurity/testing/pull/22.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
update(userspace/engine): improve skip-if-unknown-filter YAML field
```

### CODE REVIEW

**Review by FedeDP — APPROVED** [review]
/approve

**Comment by jasondellaluce** [comment]
Requires https://github.com/falcosecurity/testing/pull/22 to be merged to have tests passing.

**Review by FedeDP — APPROVED** [review]
/approve

**Review by leogr — APPROVED** [review]

**Pull request merged**
