### PR TITLE
update(docker/tester): python 3 support for regression tests

### LINKED ISSUE #1092: Migrate regression tests to Python 3
**Motivation**
Right now, our regression tests are still using Python 2.7

I noticed that it's relatively straightforward to update it to Python 3 because the framework we use, the Avocado Testing Framework, at the LTS version (69) supports Python 3 too.

There are two other major motivations for this:

- [Python 2.7 is now retired](https://www.python.org/dev/peps/pep-0373/#id2)
- Users are already reporting that they can't run the tests locally because it became increasingly difficult to find the right packages in newer distros, see [this comment](https://github.com/falcosecurity/falco/issues/798#issuecomment-526558792) for example

**Feature**

Refactor the code in `test/falco_test.py` to use Python 3.

**Alternatives**

Keep python 2.7

**Additional context**

Just wanted to make easier to contribute new Regression tests!

### PR DESCRIPTION
**Pull request by fntlnz**
Signed-off-by: Lorenzo Fontana <lo@linux.com>

**What type of PR is this?**

/kind cleanup

**Any specific area of the project related to this PR?**

/area tests

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #1092 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by fntlnz** [comment]
Once this gets merged we need to push the new docker image for falco tester.
The current pushed one works for both, the python 2 and python 3 version.

**Comment by leodido** [comment]
/hold

hold this until 0.21.0 is cut

**Pull request merged**
