### PR TITLE
Dynamic builds (mostly)

### LINKED ISSUE #963: Build improvements: Dynamic builds
**What would you like to be added**:

At the moment, the main Falco `CMakeLists.txt` and its children have hard-coded compilation flags to always compile falco as a static binary.

While has its advantages (no extra dependencies), using static binaries as a packaging medium can be cause of any sort of issues, like:

- Big final binary size 
- Difficulties in statically building/linking all the dependencies in various operating systems/kernels/glibc versions
- We don't rely on distributions to take care of patches, and most importantly, security patches in our dependencies (because we don't use OS packages for them)
- The previous point is particularly important, since we have a webserver and a gRPC server. Both need an SSL implementation. We are statically linking OpenSSL to a version that is > 1year old
- It's difficult to keep dependencies updated in general, we would rather declare the versions we work with
- Building is extremely slow and this is BAD contributor experience

Of course, one might say: "Yes but packaging becomes more difficult"

I would argue with that, we have three main distribution mediums:

- rpm packge
- deb package
- container image (aka. docker image)

For the rpm and deb package we can easily declare their dependencies in them instead.

For the container image we can install the needed dependencies directly in the container.

This **does not affect** the kernel module and the bpf probe. FTR I'm trying to refactor the bpf probe in a "compile once and run everywhere" fashion in issue #942 . 

**Why is this needed**:

Because we all deserve better builds.

### PR DESCRIPTION
**Pull request by fntlnz**
Signed-off-by: Lorenzo Fontana <lo@linux.com>

**Work items**
- [x] Change cmake files to build dynamically most of the dependencies (not every dependency can be linked dynamically because  some of them are not OS packaged e.g civetweb)
- [x] All the docker images we have need to be changed to include the system dependencies
- [x] The rpm and deb packages need to be changed to reflect the table in issue #963  regarding dependencies
- [x] Switch to CircleCI
- [x] CI needs to have the dynamic dependencies
- [x] Documentation
  - [x] Change the falco [source documentation ](https://falco.org/docs/source/) to reflect the new build dependencies
  - [x] Warn in the falco source documentation about this paradigm change from all static to dynamic

Doc revamping ongoing into https://github.com/falcosecurity/falco-website/pull/115

**What type of PR is this?**

/kind cleanup

**Any specific area of the project related to this PR?**

/area build

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #963 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
update: falco-builder base image is centos:8 now
update: falco-tester base image is fedora:31 now
build: dependencies are bundled dynamically (by default)
build: switch to CircleCI
```

### CODE REVIEW

**Comment by kris-nova** [comment]
Tested locally

```[nova@nova build-dynamic]$ make all -j8
[  2%] Built target test-trace-connect_localhost.scap
[  4%] Built target njson
[  4%] Built target b64
[  6%] Built target luajit
[  8%] Built target tbb
[  8%] Built target test-trace-ping_sendto.scap
[ 10%] Built target civetweb
[ 11%] Built target test-trace-open-multiple-files.scap
[ 11%] Built target test-trace-cat_write.scap
[ 11%] Built target test-trace-syscall.scap
[ 11%] Built target test-trace-empty.scap
[ 11%] Built target test-trace-delete_configmap.json
[ 11%] Built target test-trace-create_nginx_pod_unsensitive_mount.json
[ 12%] Built target test-trace-create_pod_kube_public_namespace.json
[ 12%] Built target test-trace-create_nginx_pod_sensitive_mount_2nd_container.json
[ 12%] Built target test-trace-create_nginx_pod_sensitive_mount.json
[ 13%] Built target test-trace-create_nginx_pod_privileged.json
[ 13%] Built target test-trace-create_nginx_service_nonodeport.json
[ 13%] Built target test-trace-create_deployment.json
[ 14%] Built target test-trace-delete_cluster_role_kube_aggregator.json
[ 14%] Built target test-trace-create_cluster_role_pod_exec.json
[ 15%] Built target test-trace-create_serviceaccount.json
[ 15%] Built target test-trace-attach_pod.json
[ 16%] Built target test-trace-anonymous_creates_namespace_foo.json
[ 16%] Built target test-trace-create_cluster_role_write_privileges.json
[ 16%] Built target test-trace-delete_namespace_foo.json
[ 16%] Built target test-trace-delete_clusterrolebinding.json
[ 16%] Built target test-trace-attach_cluster_admin_role.json
[ 16%] Built target test-trace-minikube_creates_namespace_foo.json
[ 16%] Built target test-trace-create_cluster_role_wildcard_verbs.json
[ 17%] Built target test-trace-create_cluster_role_wildcard_resources.json
[ 17%] Built target test-trace-create_configmap.json
[ 17%] Built target test-trace-create_nginx_service_nodeport.json
[ 17%] Built target test-trace-create_configmap_no_sensitive_values.json
[ 18%] Built target test-trace-create_clusterrolebinding.json
[ 18%] Built target test-trace-create_pod_kube_system_namespace.json
[ 18%] Built target test-trace-create_service.json
[ 18%] Built target test-trace-create_serviceaccount_kube_public_namespace.json
[ 18%] Built target test-trace-create_clusterrole.json
[ 18%] Built target test-trace-create_serviceaccount_kube_system_namespace.json
[ 18%] Built target test-trace-delete_clusterrole.json
[ 18%] Built target test-trace-create_nginx_pod_hostnetwork.json
[ 19%] Built target test-trace-delete_deployment.json
[ 19%] Built target test-trace-delete_service.json
[ 19%] Built target test-trace-exec_pod.json
[ 19%] Built target test-trace-create_nginx_pod_nohostnetwork.json
[ 20%] Built target test-trace-create_configmap_sensitive_values.json
[ 20%] Built target test-trace-modify_cluster_role_node_problem_detector.json
[ 21%] Built target test-trace-some-user_creates_namespace_foo.json
[ 22%] Built target test-trace-create_nginx_pod_privileged_2nd_container.json
[ 22%] Built target test-trace-create_nginx_pod_unprivileged.json
[ 22%] Built target test-trace-run_as_user_65534_container.scap
[ 22%] Built target test-trace-run_as_user_1000_sec_ctx_30_container.json
[ 24%] Built target test-trace-write_tmp_test.scap
[ 24%] Built target test-trace-delete_serviceaccount.json
[ 24%] Built target test-trace-run_as_user_30_sec_ctx.json
[ 24%] Built target test-trace-run_as_user_1000_sec_ctx.json
[ 25%] Built target test-trace-run_as_user_1000_container.json
[ 25%] Built target test-trace-run_as_user_0_sec_ctx_1000_container.json
[ 26%] Built target test-trace-host_pid.json
[ 26%] Built target test-trace-privilege_escalation.json
[ 26%] Built target test-trace-run_as_user_0_sec_ctx.json
[ 26%] Built target test-trace-host_ipc.json
[ 26%] Built target test-trace-run_as_group_1000_sec_ctx_30_container.json
[ 26%] Built target test-trace-run_as_user_0_container.json
[ 27%] Built target test-trace-capability_add_sys_time.json
[ 27%] Built target test-trace-supplemental_groups_10_20.json
[ 27%] Built target test-trace-host_network_ports.json
[ 27%] Built target test-trace-create_vanilla_nginx_deployment.json
[ 27%] Built target test-trace-capability_add_sys_nice.json
[ 27%] Built target test-trace-host_network.json
[ 27%] Built target test-trace-run_as_user_30_sec_ctx_1000_container.json
[ 28%] Built target test-trace-run_as_user_0_container.scap
[ 28%] Built target test-trace-run_as_user_1000_sec_ctx_0_container.json
[ 28%] Built target test-trace-mount_etc_using_host_path.json
[ 28%] Built target test-trace-proc_mount_type_default.json
[ 29%] Built target test-trace-fs_group.json
[ 31%] Built target test-trace-run_as_user_30_container.json
[ 31%] Built target test-trace-run_as_group_30_container.json
[ 32%] Built target test-trace-privileged.json
[ 32%] Built target test-trace-run_as_group_1000_container.json
[ 32%] Built target test-trace-privileged.scap
[ 33%] Built target test-trace-read_only_root_fs.json
[ 33%] Built target test-trace-flex_volumes.json
[ 33%] Built target test-trace-run_as_group_30_sec_ctx_1000_container.json
[ 33%] Built target test-trace-run_as_group_1000_sec_ctx.json
[ 33%] Built target test-trace-run_as_group_30_sec_ctx.json
[ 33%] Built target test-trace-proc_mount_type_unmasked.json
[ 34%] Generating docker-entrypoint
[ 34%] Built target local-Dockerfile
[ 35%] Built target docker-local-trace-open-multiple-files.scap
[ 35%] Built target docker-local-trace-ping_sendto.scap
[ 35%] Built target docker-local-trace-empty.scap
[ 35%] Built target docker-local-trace-connect_localhost.scap
[ 35%] Built target docker-local-trace-syscall.scap
[ 36%] Built target docker-local-trace-cat_write.scap
[ 36%] Built target local-docker-entrypoint
[ 36%] Built target docker-local-rule-syscalls.yaml
[ 36%] Built target docker-local-rule-tagged_rules.yaml
[ 36%] Built target docker-local-rule-skip_unknown_evt.yaml
[ 36%] Built target docker-local-rule-rule_order.yaml
[ 36%] Built target docker-local-rule-rule_names_with_spaces.yaml
[ 37%] Built target docker-local-rule-rule_names_with_regex_chars.yaml
[ 38%] Built target docker-local-rule-single_rule.yaml
[ 38%] Built target docker-local-rule-rule_append_false.yaml
[ 38%] Built target docker-local-rule-rule_append_failure.yaml
[ 39%] Built target docker-local-rule-override_rule.yaml
[ 39%] Built target docker-local-rule-override_nested_list.yaml
[ 39%] Built target docker-local-rule-override_macro.yaml
[ 39%] Built target docker-local-rule-override_list.yaml
[ 39%] Built target docker-local-rule-multiple_docs.yaml
[ 40%] Built target docker-local-rule-null_output_field.yaml
[ 40%] Built target docker-local-rule-macro_order.yaml
[ 40%] Built target docker-local-rule-macro_append_false.yaml
[ 40%] Built target docker-local-rule-invalid_missing_list_name.yaml
[ 40%] Built target docker-local-rule-invalid_array_item_not_object.yaml
[ 40%] Built target docker-local-rule-invalid_engine_version_not_number.yaml
[ 41%] Built target docker-local-rule-macro_append_failure.yaml
[ 41%] Built target docker-local-rule-invalid_list_without_items.yaml
[ 41%] Built target docker-local-rule-invalid_overwrite_rule.yaml
[ 42%] Built target docker-local-rule-invalid_condition_not_rule.yaml
[ 42%] Built target docker-local-rule-macro_append.yaml
[ 42%] Built target docker-local-rule-invalid_base_macro.yaml
[ 42%] Built target docker-local-rule-skip_unknown_unspec.yaml
[ 42%] Built target docker-local-rule-invalid_base_rule.yaml
[ 42%] Built target docker-local-rule-invalid_append_rule.yaml
[ 43%] Built target docker-local-rule-invalid_macro_without_condition.yaml
[ 43%] Built target docker-local-rule-endswith.yaml
[ 43%] Built target docker-local-rule-rule_append.yaml
[ 43%] Built target docker-local-rule-empty_rules.yaml
[ 43%] Built target docker-local-rule-double_rule.yaml
[ 43%] Built target docker-local-rule-invalid_append_rule_multiple_docs.yaml
[ 44%] Built target docker-local-rule-detect_connect_using_in.yaml
[ 44%] Built target docker-local-rule-invalid_append_macro.yaml
[ 44%] Built target docker-local-rule-single_rule_enabled_flag.yaml
[ 45%] Built target docker-local-rule-invalid_macro_comple_error.yaml
[ 46%] Built target docker-local-rule-list_sub_bare.yaml
[ 46%] Built target docker-local-rule-append_single_rule.yaml
[ 47%] Built target docker-local-rule-invalid_missing_rule_name.yaml
[ 47%] Built target docker-local-rule-catchall_order.yaml
[ 47%] Built target docker-local-rule-invalid_append_macro_multiple_docs.yaml
[ 48%] Built target docker-local-rule-invalid_rule_output.yaml
[ 48%] Built target docker-local-rule-falco_rules_warnings.yaml
[ 48%] Built target docker-local-rule-invalid_rule_without_output.yaml
[ 48%] Built target docker-local-rule-invalid_not_yaml.yaml
[ 49%] Built target docker-local-rule-list_append.yaml
[ 50%] Built target docker-local-rule-invalid_append_macro_dangling.yaml
[ 51%] Built target docker-local-rule-invalid_missing_macro_name.yaml
[ 51%] Built target docker-local-rule-skip_unknown_prefix.yaml
[ 51%] Built target docker-local-rule-invalid_overwrite_macro.yaml
[ 51%] Built target docker-local-rule-list_sub_front.yaml
[ 51%] Built target docker-local-rule-invalid_not_array.yaml
[ 52%] Built target docker-local-rule-invalid_append_rule_without_condition.yaml
[ 52%] Built target docker-local-rule-invalid_unexpected_object.yaml
[ 52%] Built target docker-local-rule-engine_version_mismatch.yaml
[ 53%] Built target docker-local-rule-invalid_overwrite_rule_multiple_docs.yaml
[ 53%] Built target docker-local-rule-invalid_overwrite_macro_multiple_docs.yaml
[ 53%] Built target docker-local-rule-invalid_yaml_parse_error.yaml
[ 53%] Built target docker-local-rule-skip_unknown_error.yaml
[ 53%] Built target docker-local-rule-list_append_failure.yaml
[ 53%] Built target docker-local-rule-list_append_false.yaml
[ 53%] Built target docker-local-rule-list_order.yaml
[ 54%] Built target docker-local-rule-list_sub_whitespace.yaml
[ 54%] Built target docker-local-rule-list_sub_mid.yaml
[ 54%] Built target docker-local-rule-list_sub_end.yaml
[ 54%] Built target docker-local-rule-list_substring.yaml
[ 58%] Built target scap
[ 60%] Built target catch2
[ 62%] Built target fakeit-external
[ 64%] Built target lpeg
[ 66%] Built target lyaml
[ 67%] Built target scap-open
[ 67%] Built target scap-validatebuffer
[ 92%] Built target sinsp
[ 94%] Built target falco_engine
[ 95%] Built target falco_test
[100%] Built target falco
[100%] Built target driver
[nova@nova build-dynamic]$ uname -a
Linux nova 4.19.88-1-MANJARO #1 SMP PREEMPT Thu Dec 5 11:04:44 UTC 2019 x86_64 GNU/Linux
```

:it:

**Comment by kris-nova** [comment]
Also adding this for documentation

```pacman -S zlib jq ncurses yaml-cpp openssl curl c-ares protobuf grpc libyaml
```

**Comment by leodido** [comment]
This is on the right path, but not completed yet.

Anyway we should investigate gRPC behaviour when built on CentOS 7. At the moment it builds but gRPC API does not seems to work as intended.

**Comment by leogr** [comment]
Hi @fntlnz 

Tested locally (archlinux), it worked fine.

```
$ make all -j16
[  2%] Built target luajit
[  4%] Built target tbb
[  7%] Built target njson
[  8%] Built target b64
[ 10%] Built target civetweb
[ 10%] Built target test-trace-connect_localhost.scap
[ 10%] Built target test-trace-ping_sendto.scap
[ 10%] Built target test-trace-empty.scap
[ 11%] Built target test-trace-open-multiple-files.scap
[ 11%] Built target test-trace-syscall.scap
[ 11%] Built target test-trace-delete_configmap.json
[ 11%] Built target test-trace-cat_write.scap
[ 11%] Built target test-trace-create_nginx_pod_unsensitive_mount.json
[ 12%] Built target test-trace-create_pod_kube_public_namespace.json
[ 12%] Built target test-trace-create_nginx_pod_sensitive_mount.json
[ 12%] Built target test-trace-create_nginx_pod_sensitive_mount_2nd_container.json
[ 14%] Built target test-trace-create_nginx_pod_privileged.json
[ 14%] Built target test-trace-create_serviceaccount.json
[ 14%] Built target test-trace-create_deployment.json
[ 14%] Built target test-trace-create_nginx_service_nonodeport.json
[ 15%] Built target test-trace-delete_cluster_role_kube_aggregator.json
[ 15%] Built target test-trace-create_cluster_role_pod_exec.json
[ 15%] Built target test-trace-attach_pod.json
[ 15%] Built target test-trace-delete_clusterrolebinding.json
[ 15%] Built target test-trace-delete_namespace_foo.json
[ 15%] Built target test-trace-attach_cluster_admin_role.json
[ 15%] Built target test-trace-create_cluster_role_write_privileges.json
[ 16%] Built target test-trace-anonymous_creates_namespace_foo.json
[ 16%] Built target test-trace-create_cluster_role_wildcard_verbs.json
[ 16%] Built target test-trace-create_configmap.json
[ 16%] Built target test-trace-minikube_creates_namespace_foo.json
[ 16%] Built target test-trace-create_nginx_service_nodeport.json
[ 17%] Built target test-trace-create_cluster_role_wildcard_resources.json
[ 17%] Built target test-trace-create_configmap_no_sensitive_values.json
[ 18%] Built target test-trace-create_clusterrolebinding.json
[ 18%] Built target test-trace-create_pod_kube_system_namespace.json
[ 18%] Built target test-trace-create_serviceaccount_kube_public_namespace.json
[ 18%] Built target test-trace-create_service.json
[ 18%] Built target test-trace-create_clusterrole.json
[ 18%] Built target test-trace-create_serviceaccount_kube_system_namespace.json
[ 18%] Built target test-trace-delete_clusterrole.json
[ 19%] Built target test-trace-delete_deployment.json
[ 19%] Built target test-trace-create_nginx_pod_hostnetwork.json
[ 20%] Built target test-trace-create_configmap_sensitive_values.json
[ 20%] Built target test-trace-delete_service.json
[ 20%] Built target test-trace-exec_pod.json
[ 20%] Built target test-trace-create_nginx_pod_nohostnetwork.json
[ 20%] Built target test-trace-create_nginx_pod_privileged_2nd_container.json
[ 21%] Built target test-trace-create_nginx_pod_unprivileged.json
[ 22%] Built target test-trace-some-user_creates_namespace_foo.json
[ 23%] Built target test-trace-write_tmp_test.scap
[ 24%] Built target test-trace-modify_cluster_role_node_problem_detector.json
[ 24%] Built target test-trace-delete_serviceaccount.json
[ 24%] Built target test-trace-run_as_user_1000_sec_ctx_30_container.json
[ 24%] Built target test-trace-run_as_user_65534_container.scap
[ 24%] Built target test-trace-run_as_user_30_sec_ctx.json
[ 24%] Built target test-trace-run_as_user_1000_sec_ctx.json
[ 24%] Built target test-trace-run_as_user_0_sec_ctx_1000_container.json
[ 24%] Built target test-trace-run_as_user_0_sec_ctx.json
[ 25%] Built target test-trace-run_as_user_1000_container.json
[ 25%] Built target test-trace-privilege_escalation.json
[ 25%] Built target test-trace-host_ipc.json
[ 25%] Built target test-trace-run_as_group_1000_sec_ctx_30_container.json
[ 26%] Built target test-trace-host_pid.json
[ 26%] Built target test-trace-run_as_user_0_container.json
[ 27%] Built target test-trace-capability_add_sys_time.json
[ 27%] Built target test-trace-supplemental_groups_10_20.json
[ 27%] Built target test-trace-host_network_ports.json
[ 27%] Built target test-trace-create_vanilla_nginx_deployment.json
[ 27%] Built target test-trace-capability_add_sys_nice.json
[ 27%] Built target test-trace-host_network.json
[ 27%] Built target test-trace-run_as_user_1000_sec_ctx_0_container.json
[ 27%] Built target test-trace-run_as_user_30_sec_ctx_1000_container.json
[ 28%] Built target test-trace-run_as_user_0_container.scap
[ 28%] Built target test-trace-mount_etc_using_host_path.json
[ 29%] Built target test-trace-run_as_user_30_container.json
[ 29%] Built target test-trace-proc_mount_type_default.json
[ 30%] Built target test-trace-fs_group.json
[ 31%] Built target test-trace-privileged.json
[ 32%] Built target test-trace-run_as_group_30_container.json
[ 32%] Built target test-trace-run_as_group_1000_container.json
[ 33%] Built target test-trace-read_only_root_fs.json
[ 33%] Built target test-trace-privileged.scap
[ 33%] Built target test-trace-run_as_group_1000_sec_ctx.json
[ 33%] Built target test-trace-flex_volumes.json
[ 33%] Built target test-trace-run_as_group_30_sec_ctx.json
[ 33%] Built target test-trace-proc_mount_type_unmasked.json
[ 33%] Built target test-trace-run_as_group_30_sec_ctx_1000_container.json
[ 34%] Generating docker-entrypoint
[ 34%] Built target local-Dockerfile
[ 35%] Built target docker-local-trace-open-multiple-files.scap
[ 35%] Built target docker-local-trace-connect_localhost.scap
[ 35%] Built target docker-local-trace-empty.scap
[ 35%] Built target docker-local-trace-ping_sendto.scap
[ 35%] Built target docker-local-rule-tagged_rules.yaml
[ 35%] Built target docker-local-trace-syscall.scap
[ 36%] Built target docker-local-trace-cat_write.scap
[ 36%] Built target local-docker-entrypoint
[ 36%] Built target docker-local-rule-rule_order.yaml
[ 36%] Built target docker-local-rule-syscalls.yaml
[ 37%] Built target docker-local-rule-rule_names_with_regex_chars.yaml
[ 37%] Built target docker-local-rule-skip_unknown_evt.yaml
[ 38%] Built target docker-local-rule-single_rule.yaml
[ 38%] Built target docker-local-rule-override_nested_list.yaml
[ 39%] Built target docker-local-rule-override_rule.yaml
[ 39%] Built target docker-local-rule-rule_names_with_spaces.yaml
[ 39%] Built target docker-local-rule-override_macro.yaml
[ 39%] Built target docker-local-rule-rule_append_false.yaml
[ 39%] Built target docker-local-rule-rule_append_failure.yaml
[ 39%] Built target docker-local-rule-override_list.yaml
[ 39%] Built target docker-local-rule-multiple_docs.yaml
[ 40%] Built target docker-local-rule-null_output_field.yaml
[ 40%] Built target docker-local-rule-macro_append_false.yaml
[ 40%] Built target docker-local-rule-macro_order.yaml
[ 40%] Built target docker-local-rule-invalid_engine_version_not_number.yaml
[ 40%] Built target docker-local-rule-invalid_missing_list_name.yaml
[ 40%] Built target docker-local-rule-invalid_list_without_items.yaml
[ 41%] Built target docker-local-rule-macro_append_failure.yaml
[ 41%] Built target docker-local-rule-invalid_array_item_not_object.yaml
[ 41%] Built target docker-local-rule-invalid_overwrite_rule.yaml
[ 41%] Built target docker-local-rule-macro_append.yaml
[ 42%] Built target docker-local-rule-invalid_condition_not_rule.yaml
[ 42%] Built target docker-local-rule-skip_unknown_unspec.yaml
[ 42%] Built target docker-local-rule-invalid_base_rule.yaml
[ 43%] Built target docker-local-rule-endswith.yaml
[ 43%] Built target docker-local-rule-invalid_base_macro.yaml
[ 43%] Built target docker-local-rule-invalid_append_rule.yaml
[ 43%] Built target docker-local-rule-invalid_macro_without_condition.yaml
[ 43%] Built target docker-local-rule-rule_append.yaml
[ 43%] Built target docker-local-rule-empty_rules.yaml
[ 43%] Built target docker-local-rule-single_rule_enabled_flag.yaml
[ 43%] Built target docker-local-rule-invalid_append_rule_multiple_docs.yaml
[ 43%] Built target docker-local-rule-double_rule.yaml
[ 43%] Built target docker-local-rule-invalid_append_macro.yaml
[ 44%] Built target docker-local-rule-detect_connect_using_in.yaml
[ 45%] Built target docker-local-rule-invalid_macro_comple_error.yaml
[ 46%] Built target docker-local-rule-list_sub_bare.yaml
[ 47%] Built target docker-local-rule-invalid_missing_rule_name.yaml
[ 47%] Built target docker-local-rule-append_single_rule.yaml
[ 47%] Built target docker-local-rule-catchall_order.yaml
[ 48%] Built target docker-local-rule-invalid_rule_output.yaml
[ 48%] Built target docker-local-rule-falco_rules_warnings.yaml
[ 48%] Built target docker-local-rule-invalid_not_yaml.yaml
[ 48%] Built target docker-local-rule-invalid_append_macro_multiple_docs.yaml
[ 49%] Built target docker-local-rule-skip_unknown_prefix.yaml
[ 49%] Built target docker-local-rule-invalid_rule_without_output.yaml
[ 50%] Built target docker-local-rule-list_append.yaml
[ 50%] Built target docker-local-rule-list_sub_front.yaml
[ 51%] Built target docker-local-rule-invalid_append_macro_dangling.yaml
[ 51%] Built target docker-local-rule-invalid_missing_macro_name.yaml
[ 51%] Built target docker-local-rule-invalid_not_array.yaml
[ 52%] Built target docker-local-rule-invalid_append_rule_without_condition.yaml
[ 52%] Built target docker-local-rule-invalid_overwrite_macro.yaml
[ 52%] Built target docker-local-rule-engine_version_mismatch.yaml
[ 52%] Built target docker-local-rule-invalid_overwrite_rule_multiple_docs.yaml
[ 52%] Built target docker-local-rule-invalid_unexpected_object.yaml
[ 53%] Built target docker-local-rule-invalid_overwrite_macro_multiple_docs.yaml
[ 53%] Built target docker-local-rule-invalid_yaml_parse_error.yaml
[ 53%] Built target docker-local-rule-list_append_failure.yaml
[ 53%] Built target docker-local-rule-skip_unknown_error.yaml
[ 53%] Built target docker-local-rule-list_append_false.yaml
[ 53%] Built target docker-local-rule-list_order.yaml
[ 54%] Built target docker-local-rule-list_sub_whitespace.yaml
[ 54%] Built target docker-local-rule-list_sub_end.yaml
[ 54%] Built target docker-local-rule-list_sub_mid.yaml
[ 54%] Built target docker-local-rule-list_substring.yaml
[ 58%] Built target scap
[ 60%] Built target catch2
[ 62%] Built target fakeit-external
[ 64%] Built target lpeg
[ 66%] Built target lyaml
[ 67%] Built target scap-open
[ 67%] Built target scap-validatebuffer
[ 92%] Built target sinsp
[ 94%] Built target falco_engine
[ 95%] Built target falco_test
[100%] Built target falco
[100%] Built target driver
```

```
$ uname -a 
Linux pr 5.4.2-arch1-1 #1 SMP PREEMPT Thu, 05 Dec 2019 12:29:40 +0000 x86_64 GNU/Linux
```

**Comment by leodido** [comment]
We are getting closer with this ..

In the meantime
/honk

**Comment by fntlnz** [comment]
We have a problem with OpenSSL.
Now that we don't build it statically anymore, the CentOS 7 builder uses the 1.0.2 version (the only available on CentOS). This means that it creates packages (deb and rpm) that are only compatible with 1.0.2 - In that way, anyone who installs it on a system with 1.1 or later will not be able to have Falco working.


from the OpenSSL policies file

```

    The next version of OpenSSL will be 3.0.0.
    Version 1.1.1 will be supported until 2023-09-11 (LTS).
    Version 1.1.0 will be supported until 2019-09-11.
    Version 1.0.2 will be supported until 2019-12-31 (LTS).
    Version 1.0.1 is no longer supported.
    Version 1.0.0 is no longer supported.
    Version 0.9.8 is no longer supported.

```

CentOS 7 is EOL in 2024.

Systems that don't have openssl 1.0 anymore include:

- All the latest Ubuntu and Debian
- All the container distributions
- Fedora
- CentOS > 8

Why we need OpenSSL:

- Civetwebserver uses it, altough[ I noticed today](https://github.com/falcosecurity/falco/issues/860#issuecomment-575087263) that it dynamically links at runtime the system OpenSSL right now (that is also breaking the experience for some users)
- libscap needs it
- gRPC needs it

What could we do:

- Continue statically building OpenSSL but keep it updated and track CVEs - we need some automation to help us keep it updated. This will lead to very slow builds again (which was one of the purposes of this PR) -  **(high effort)**
- Drop CentOS 7 support and move the builder to CentOS 8 **(low effort)**
- Build a separate package for CentOS 7 and have multiple builders - if we do this we also will need to adapt the packages release mechanism which is actually NOT OWNED by Falco (but by Sysdig) - we could start the process of owning that piece while doing this. **(high effort)**

**Comment by fntlnz** [comment]
Should also solve #874

**Comment by leodido** [comment]
greeeeeny 💚 

/honk

**Comment by leodido** [comment]
Ok, release notes ready!

**Pull request merged**
