### PR TITLE
Remove duplicate allowed ecr registry rule

### PR DESCRIPTION
**Pull request by TomKeyte**
**What type of PR is this?**

/kind cleanup
/kind rule-update

**Any specific area of the project related to this PR?**

/area rules

**What this PR does / why we need it**:
Removes a duplicate ECR repo starts_with rule in the allowed_aws_ecr_registry_root_for_eks macro

**Which issue(s) this PR fixes**:

```release-note
NONE
```

### CODE REVIEW

**Review by leogr — APPROVED** [review]
Good catch! Thank you :)

/approve

**Review by leodido — APPROVED** [review]
Falco eyes 👀 

LGTM!

**Pull request merged**
