### PR TITLE
add Yahoo!Japan as an adopter

### PR DESCRIPTION
**Pull request by ukitazume**
Signed-off-by: Yu Kitazume <u.kitazume@gmail.com>

**What type of PR is this?**

/kind documentation

> If contributing rules or changes to rules, please make sure to also uncomment one of the following line:

**Any specific area of the project related to this PR?**

**What this PR does / why we need it**:

Yahoo! Japan uses Falco OSS for AI platform run on Kubernetes. Akira Oiwa from Yahoo! Japan, introduces how to use Falco on the AI platform. I'm filing this PR on behalf of him.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ukitazume** [comment]
cc @danpopSD

**Review by leogr — APPROVED** [review]
:partying_face:

**Review by leodido — APPROVED** [review]

**Pull request merged**
