### PR TITLE
Gitlab

### PR DESCRIPTION
**Pull request by kris-nova**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

/kind documentation

> /kind failing-test

> /kind feature

> If contributing rules or changes to rules, please make sure to also uncomment one of the following line:

> /kind rule-update

> /kind rule-create

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

> /area engine

> /area rules

> /area tests

> /area proposals

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
docs: adding GitLab to adopters 🎉 
```

### CODE REVIEW

**Comment by kris-nova** [comment]
Matching logo PR: https://github.com/falcosecurity/falco-website/pull/223

**Comment by fntlnz** [comment]
Edited the release notes for release, this is not an user facing change.

**Pull request merged**
