### PR TITLE
Cleanup warnings and smart ptrs

### PR DESCRIPTION
**Pull request by federico-sysdig**
**What type of PR is this?**
/kind cleanup

**Any specific area of the project related to this PR?**
/area build

**What this PR does / why we need it**:
This is just a cleanup/refactor on some usages of smart pointers, plus a fix for a warning about a pessimizing `std::move` raised by Clang.
The changes might seem very diverse, but they are very simple and arranged into separate commits if the reviewer prefers to address the task for each topic separately.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Review by jasondellaluce — APPROVED** [review]
/approve

**Comment by FedeDP** [comment]
/milestone 0.38.0
/hold
Since ci is failing.

**Review by LucaGuerra — APPROVED** [review]

**Comment by LucaGuerra** [comment]
Thanks @FedeDP ! Let's see why the CI has some problems (might be a job config)

**Comment by FedeDP** [comment]
/unhold
CI is unrelated.

**Pull request merged**
