### PR TITLE
update(cmake): bump libs to master.

### LINKED ISSUE #3248: [BUILD] URL dependency to c-ares not valid
**Describe the bug**

Falco is not built if libcares is not installed on the system, as the URL

**How to reproduce it**

On an ubuntu with bpftool and its dependencies installed

**Expected behaviour**

Supposed to download c-ares if not found during build

**Screenshots**

**Environment**

- Falco version:
0.38.0
- System info:

- Cloud provider or hardware configuration:
- OS:
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
- Kernel:
5.15.0-112-generic x86_64 x86_64 x86_64 GNU/Linux
- Installation method:
Custom falco installation from github repo source

**Additional context**

Workaround: installing libcares works

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind cleanup

**Any specific area of the project related to this PR?**

/area build

**What this PR does / why we need it**:

This PR bumps libs to master, fixing c-ares build error and thus fixing bundled-deps CI.

**Which issue(s) this PR fixes**:

Fixes #3248 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by Andreagit97 — APPROVED** [review]
/approve

**Review by Andreagit97 — APPROVED** [review]
/approve

**Review by incertum — APPROVED** [review]
/approve

**Pull request merged**
