### PR TITLE
new(build): use a dynamic build for the bin/tgz distribution

### PR DESCRIPTION
**Pull request by LucaGuerra**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

/kind feature

> If contributing rules or changes to rules, please make sure to also uncomment one of the following line:

> /kind rule-update

> /kind rule-create

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area build

> /area engine

> /area rules

> /area tests

> /area proposals

**What this PR does / why we need it**:

Currently, we distribute a static binary as `.tar.gz` which is build with musl libc. The build is as static as it gets but it's not possible to load plugins in such a build because they require dynamic loading to be available which cannot be enabled without a dynamic build based on glibc.

In addition, the nodriver image needs to have the proper libraries installed, I propose `debian-slim` for this.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
new(build): switch to dynamic build for .tar.gz
```

### CODE REVIEW

**Comment by FedeDP** [comment]
I really like this! Great job @LucaGuerra :)

**Review by leogr — APPROVED** [review]
/approve

**Review by jasondellaluce — APPROVED** [review]
/approve

**Pull request merged**
