### PR TITLE
fix: falco-driver-loader source-only print env vars

### LINKED ISSUE #2352: falco-driver-loader --source-only does nothing
**Describe the bug**

I believe `falco-driver-loader --source-only` seems like it should expose bash variables somehow. However it's current behaviour is synonymous with `echo ""`.

**How to reproduce it**
Call 
```sh
$ scripts/falco-driver-loader --source-only

```
(note there's no output above)

**Expected behaviour**

Something like:
```sh
scripts/falco-driver-loader --source-only 
ENABLE_COMPILE=yes
ENABLE_DOWNLOAD=yes
ARCH=x86_64
KERNEL_RELEASE=5.15.0-56-generic
KERNEL_VERSION=62
DRIVERS_REPO="https://download.falco.org/driver"
DRIVER_VERSION="3.0.1+driver"
DRIVER_NAME="falco"
FALCO_VERSION="0.33.0"
DRIVER=bpf
```
(except with the 

**Environment**

- Falco version: FALCO_VERSION="0.33.0" also can reproduce on master.

**Additional context**

### PR DESCRIPTION
**Pull request by steakunderscore**
**What type of PR is this?**

/kind bug

**Any specific area of the project related to this PR?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #2352

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
falco-driver-loader --source-only now prints the values as env vars
```

### CODE REVIEW

**Comment by ggilligan12** [comment]
*endorse*

**Comment by FedeDP** [comment]
Hi! Thanks for this PR!
> echo "  --source-only  skip execution and allow sourcing in another script"

This is from the help of falco-driver-loader. I assume we don't want to print anything in that case; but i fully agree with your idea; we might add a new subcmd, like `--print-env` ?

**Comment by steakunderscore** [comment]
hmm.. I think this diff actually stems from my lack of understanding of bash sourcing [my comment](https://github.com/falcosecurity/falco/issues/2352#issuecomment-1381696583) on #2352.

I'd be happy to convert this to a `--print-env` env flag if you guys think this would be useful? If not, feel free to close this without merging.

**Comment by FedeDP** [comment]
I think it is pretty useful to add the `--print-env` :) 
I'd also print `TARGET_ID` like https://github.com/falcosecurity/falco/blob/master/scripts/falco-driver-loader#L314 does!

**Comment by leogr** [comment]
I like it. I see some failing tests, any clue? :thinking:

**Comment by steakunderscore** [comment]
I'll get this cleaned up. I'll also take a look at the tests.

**Comment by FedeDP** [comment]
I don't think tests are actually your fault; we are having some weird errors lately :/

**Comment by leogr** [comment]
> hmm.. I think this diff actually stems from my lack of understanding of bash sourcing [my comment](https://github.com/falcosecurity/falco/issues/2352#issuecomment-1381696583) on #2352.
> 
> I'd be happy to convert this to a `--print-env` env flag if you guys think this would be useful? If not, feel free to close this without merging.


Hey @steakunderscore 

My vote goes for `--print-env`!

PS
We are close to the Falco release (by the end of this month). If you can't update the PR in time, I will move it to the next milestone.

**Comment by leogr** [comment]
Hey @steakunderscore 

Any update on this?

**Comment by leogr** [comment]
I did not notice that `--print-env` change request was already addressed, so this should be ready for review.

cc @FedeDP @Andreagit97 @therealbobo

**Comment by therealbobo** [comment]
Left a comment but for the rest LGTM! 😄

**Comment by FedeDP** [comment]
LGTM too; i'd wait for Falco patch release 0.35.1 to be out, before going on with this; great refactor though, much more readable script!

**Review by FedeDP — APPROVED** [review]
/approve

**Review by Andreagit97 — APPROVED** [review]
/approve
Thank you andò sorry for the delay!

**Comment by Andreagit97** [comment]
rebased to fix the CI

**Review by FedeDP — APPROVED** [review]
/approve

**Pull request merged**
