### PR TITLE
rule(falco_rules): update evt.type for spawned process macro

### PR DESCRIPTION
**Pull request by Andreagit97**
**What type of PR is this?**

/kind rule-update

**Any specific area of the project related to this PR?**

/area rules

**What this PR does / why we need it**:

As suggested here by we must monitor also `execveat` events to check if a new process is spawned. 

**Which issue(s) this PR fixes**:

Ref. #1857 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
rule(macro spawned_process): monitor also processes spawned by `execveat`
```

### CODE REVIEW

**Comment by jasondellaluce** [comment]
This is great @Andreagit97 ! Thanks. This LGTM, just make sure of using the `rule(...): ...` notation in the release note. Take some older rule-related PR as reference, as that line will be used to generate the changelog of the upcoming release.

**Comment by Andreagit97** [comment]
I fixed it, thank you!

**Review by leogr — APPROVED** [review]
/approve

**Review by jasondellaluce — APPROVED** [review]
/approve

🚀

**Pull request merged**
